### ISSUE TITLE
Node-Red auf CCU3, sofort Server stop nach Installation node-red-contrib-sonnoff

### ISSUE THREAD

**Issue by andreas15366** [rdmtc/RedMatic#158]
Hallo,

neueste Firmware auf der CCU3, Update Node-RED vom 02.03.2019 am 03.03.2019 installiert.

Auf Node-RED SONOFF node installiert und MQTT eingerichtet- Bis dahin alles ok und Sytem lief.
Dann node-red-contrib-sonoff-server 1.0.0 installiert und augenscheinlich eine falsche IP-Adresse dem SONOFF-Server gegeben. - 

Vortan permanentes STOP des Node-Red. 

Frage 1: Gibt es eine Chance ohne Neuinstallation Node-RED wieder laufen zu lassen?
Frage 2: Ich habe SONOFF T1 mit 2 Kanälen in Nutzung. Erhoffe mir Zugriff auf POWER1 und POWER2 sowie mehr Zugriff überhaupt von Node-RED über node-red-contrib-sonoff-server, denn im SONOFF node an sich kam "nur" POWER, brauche aber POWER1 und POWER2.

Logfile (Log Level "fatal" anbei

Viele Grüße aus Berlin

Andreas
 
[redmatic.2019-03-04T06_21_44.056Z.log.txt](https://github.com/HM-RedMatic/RedMatic/files/2924538/redmatic.2019-03-04T06_21_44.056Z.log.txt)

**Comment by hobbyquaker** [comment]
Am einfachsten Du löscht das Verzeichnis `/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonnoff`. Dann wird sich Node-RED zwar beschweren dass es fehlende Nodes gibt, aber es sollte nicht mehr abschmieren.
Grund für den Crash ist übrigens dass diese Nodes versuchen sich auf Port 443 (https) zu binden, der ist aber vom CCU-Webserver belegt. Ist recht unschön, das sollte abgefangen werden anstatt zum Crash zu führen. Am besten ein Issue bei denen aufmachen, hier verlinken, dann lassen wir hier offen bis das in node-red-contrib-sonoff gelöst ist.

**Comment by hobbyquaker** [comment]
Und noch ein Tipp: Ich hab gesehn Du nutzt Node-RED Nodes als MQTT Broker. Ich würde da eher den Mosquitto empfehlen, habe ich auch als Addon paketiert: https://github.com/hobbyquaker/ccu-addon-mosquitto. Und mit der Tasmota Firmware auf den Sonoffs sollte das ganze dann eigentlich garkein Bedarf mehr nach speziellen Sonoff-Nodes haben, das kannst dann ja auch einfach per MQTT alles machen.

**Comment by andreas15366** [comment]
Hallo, 

das mit dem Verzeichnis löschen hat geholfen. 

Danach noch bisschen im FLOW aufgeräumt, SONOFF-Fragmente gelöscht. 

Jetzt ist Node-RED wieder „sauber“! – Danke!

 

Von: Sebastian Raff [mailto:notifications@github.com] 
Gesendet: Montag, 4. März 2019 17:17
An: HM-RedMatic/RedMatic
Cc: andreas15366; Author
Betreff: Re: [HM-RedMatic/RedMatic] Node-Red auf CCU3, sofort Server stop nach Installation node-red-contrib-sonnoff (#158)

 

Am einfachsten Du löscht das Verzeichnis /usr/local/addons/redmatic/var/node_modules/node-red-contrib-sonnoff. Dann wird sich Node-RED zwar beschweren dass es fehlende Nodes gibt, aber es sollte nicht mehr abschmieren.
Grund für den Crash ist übrigens dass diese Nodes versuchen sich auf Port 443 (https) zu binden, der ist aber vom CCU-Webserver belegt. Ist recht unschön, das sollte abgefangen werden anstatt zum Crash zu führen. Am besten ein Issue bei denen aufmachen, hier verlinken, dann lassen wir hier offen bis das in node-red-contrib-sonoff gelöst ist.

**Comment by andreas15366** [comment]
Und noch ein Dank: 

Mosquitto hab ich nun als Zusatzsoftware installiert. Sofort danach haben sich auch die Sonoff´s, via MQT in der Konsole gezeigt, verbunden.

Was aber nun? – Hab ich da jetzt irgendwo ein Tool. Ich finde keine Anleitung…. Gibt´s da noch einen tollen Tip?

 

 

Von: Sebastian Raff [mailto:notifications@github.com] 
Gesendet: Montag, 4. März 2019 17:20
An: HM-RedMatic/RedMatic
Cc: andreas15366; Author
Betreff: Re: [HM-RedMatic/RedMatic] Node-Red auf CCU3, sofort Server stop nach Installation node-red-contrib-sonnoff (#158)

 

Und noch ein Tipp: Ich hab gesehn Du nutzt Node-RED Nodes als MQTT Broker. Ich würde da eher den Mosquitto empfehlen, habe ich auch als Addon paketiert: https://github.com/hobbyquaker/ccu-addon-mosquitto. Und mit der Tasmota Firmware auf den Sonoffs sollte das ganze dann eigentlich garkein Bedarf mehr nach speziellen Sonoff-Nodes haben, das kannst dann ja auch einfach per MQTT alles machen.

**Comment by andreas15366** [comment]
*      ich bin´s nochmal.

*      Habe bisschen in Node-Red rum gespielt und immerhin „connected“ bekommen.

*      Ist die nachfolgende Grafik sichtbar?

*      

 

Für mich wäre es genial, wenn ich erfahren könnte, wo ich eine kleine Anleitung finde.

Primär will ich ja zuerst meine Sonoff Touch mit POWER1 und POWER2 „abgreifen“ und Licht steuern.

 

Viele Grüße

 

Andreas

 

Von: Sebastian Raff [mailto:notifications@github.com] 
Gesendet: Montag, 4. März 2019 17:20
An: HM-RedMatic/RedMatic
Cc: andreas15366; Author
Betreff: Re: [HM-RedMatic/RedMatic] Node-Red auf CCU3, sofort Server stop nach Installation node-red-contrib-sonnoff (#158)

 

Und noch ein Tipp: Ich hab gesehn Du nutzt Node-RED Nodes als MQTT Broker. Ich würde da eher den Mosquitto empfehlen, habe ich auch als Addon paketiert: https://github.com/hobbyquaker/ccu-addon-mosquitto. Und mit der Tasmota Firmware auf den Sonoffs sollte das ganze dann eigentlich garkein Bedarf mehr nach speziellen Sonoff-Nodes haben, das kannst dann ja auch einfach per MQTT alles machen.

**Comment by andreas15366** [comment]
Hallo, hab´s verstanden:

 

Im Node-RED habe ich wieder node-red-contrib-sonoff-tasmota installiert und kann nun auch wieder einen Button erstellen. Beim SONOFF Basic geht sofort ganz brav das ON/OFF.

 

Bleibt bitte die Frage nach den Sonoff-Touch: die ja anstatt POWER nun POWER1 und POWER 2 schicken. Gibt es dazu einen Trick, dass ich die integriere? – Bestimmt. – Oder?

 

Viele Grüße

 

Von: Andreas Geyer [mailto:andreas.geyer@gmx.net] 
Gesendet: Montag, 4. März 2019 23:25
An: 'HM-RedMatic/RedMatic'; 'HM-RedMatic/RedMatic'
Cc: 'Author'
Betreff: AW: [HM-RedMatic/RedMatic] Node-Red auf CCU3, sofort Server stop nach Installation node-red-contrib-sonnoff (#158)

 

Und noch ein Dank: 

Mosquitto hab ich nun als Zusatzsoftware installiert. Sofort danach haben sich auch die Sonoff´s, via MQT in der Konsole gezeigt, verbunden.

Was aber nun? – Hab ich da jetzt irgendwo ein Tool. Ich finde keine Anleitung…. Gibt´s da noch einen tollen Tip?

 

 

Von: Sebastian Raff [mailto:notifications@github.com] 
Gesendet: Montag, 4. März 2019 17:20
An: HM-RedMatic/RedMatic
Cc: andreas15366; Author
Betreff: Re: [HM-RedMatic/RedMatic] Node-Red auf CCU3, sofort Server stop nach Installation node-red-contrib-sonnoff (#158)

 

Und noch ein Tipp: Ich hab gesehn Du nutzt Node-RED Nodes als MQTT Broker. Ich würde da eher den Mosquitto empfehlen, habe ich auch als Addon paketiert: https://github.com/hobbyquaker/ccu-addon-mosquitto. Und mit der Tasmota Firmware auf den Sonoffs sollte das ganze dann eigentlich garkein Bedarf mehr nach speziellen Sonoff-Nodes haben, das kannst dann ja auch einfach per MQTT alles machen.

**Comment by hobbyquaker** [comment]
Ich schließe hier mal, hab mal eine komfortablere Nutzung von Sonoff-Tasmota auf die Todo genommen: https://github.com/rdmtc/RedMatic/issues/173
