### ISSUE TITLE
Text-to-Speech mit HmIP-MP3P

### ISSUE THREAD

**Issue by drMaxxi** [rdmtc/RedMatic#163]
Ist es irgendwie möglich eine Text-to-Speech Ausgabe mittels des HmIP-MP3P über Node-Red zu realisieren? z.B. Es hat zu regnen begonnen und das Fenster im Dachboden ist offen.

**Comment by Hypnos3** [comment]
Interessante Idee.

Mangels HmIP-MP3P kann ich es nicht genau sagen, aber ich vermute mal, dass die MP3 files auf der SD Karte des MP3P liegen müssen und man online da nicht rankommt. Sonst könnte man sich ein MP3 über TTS erzeugen lassen und an das Gerät senden.

Eine alternative wäre fertige Teile als mp3 auf der SD karte abzulegen. Zum Beispiel: "Es hat zu regnen begonnen" und "das Fenster im Dachboden ist offen" und das dann nacheinander abzuspielen.

Die Frage ist am Ende ob man swirklich so viele variable Ansagen hat oder ob man nicht alle möglichen Ansagen fertig auf die SD Karte ablegen kann. Die MP3 files für die SD Karte kann man sich im Internet erzeugen lassen.

**Comment by Hypnos3** [comment]
PS: Derartige Fragen finde ich besser im Homematic Forum aufgehoben, als in einem issue Tracker.

**Comment by drMaxxi** [comment]
Das wär doch ein Vorwand einen kaufen "zu müssen" :) 

So ist momentan mit der Homematicprogrammierlösung - ich frage mich ob ein "echtes" TTS oder zumindest auf Buchstabenbasis möglich ist. Könnte mir so etwas mit Homematic nur schwer vorstellen, mit RedMatic könnte es vielleicht einfacher sein. Mit TTS würde man bei der Umsetzung der einzelnen Funktionen einiges an Zeit sparen, da man nur mehr die Sätze übergeben muss und nicht mehr alle einzelnen Teile aufnehmen, hochladen und dann umständlich aneinandersetzen muss.

**Comment by hobbyquaker** [comment]
Ich halte es nicht für praktikabel auf einem mp3p Laute oder Worte einzeln abzulegen um sich ein "pseudo-tts" zu bauen. Mehr als 10 mp3s können nicht in eine Sequenz gepackt werden und die Pausenzeiten zwischen den einzelnen Dateien machen das ganze glaube ich ziemlich holprig. Ich würde da empfehlen ganze Sätze oder zumindest Teilsätze zu nutzen oder eine ganz andere Lösung für TTS zu nutzen (Sonos Lautsprecher, Android Tablet, ...).
