### ISSUE TITLE
Installation (Update) klappt nicht mehr

### ISSUE THREAD

**Issue by str3000** [rdmtc/RedMatic#166]
Hallo,
vielen Dank für das tolle Projekt! Bin absolut begeistert.

Ich habe jetzt aber ein Problem bei dem ich nicht weiterkomme.
Die Installationen von dem Addon funktionieren bei mir nicht mehr.
seit:
- 3.0.1
- 3.1.0
- 3.1.1
installiert ist 2.9
Es bleibt nach installation immer V2.9 stehen.
Während der Installation kommen immer (seit Anfang an) Fehlerboxen, dass die AddOn nicht mehr reagieren. Habe ich bisher ignoriert
Ich verwende eine CCU3 mit den Addons: Cux, XML, Hue, Mediola und natürlich node-red
Alle SW aktuelle Versionen.
Der mqtt service läuft auf anderer HW. 

Zusatz nur zu Erläuterung :
Seit gestern keine Verbindung mehr zu mqtt. Habe aber noch nicht geschaut woran es liegt.
Desweiteren habe ich auch die Fehler:
- "getRegaVariables Error:"  (Leider finde ich kein logfile in dem der Fehler protokolliert wird)
- Homekit Verbindung fkt nicht mehr seit ca. 10 Tagen. 
  Home App meldet: "67 Geräte Antworten nicht mehr"
  Bin jedoch noch nicht zur Fehlersuche gekommen.

Zusatzfrage:
Kann man die CCU SW incl. AddOns auch auf einem Intel NUC 7 mit i3 Prozessor unter UBUNTU server installieren und zum Laufen bekommen?
Dann würde ich auch gerne auf Mediola verzichten. 

Vorab schon mal Danke für die Unterstützung!

**Comment by spiu16** [comment]
Bin mir nicht sicher ob das mit dem oben beschriebenen Topic zusammenhängt:
Bei mir läuft die Installation zwar durch, aber es kommt keine Abschlussmeldung in RaspberryMatic (Version 3.43.15.20190223) mehr. Auch nach mehr als 20 Minuten bleibt der Screen ausgegraut.
Wenn ich die RaspberryMatic-URL neu lade kann ich mich wieder normal anmelden. 
Im Fenster "RaspberryMatic - Zusatzsoftware" kann ich dann sehen dass die neue RedMatic-Version installiert wurde. Status von RedMatic ist allerdings noch "Stopped" und ich muss RedMatic manuell starten.

**Comment by str3000** [comment]
Danke,
ich vermute das sind unterschiedliche Dinge.

mqtt läuft wieder. War vermutlich nur ein zeitliches Problem.
Auch Homekit habe ich nach dem beschriebenen RESET wieder am Laufen.

Das Update von Redmatic hat aber leider wieder nicht getan.
Ich habe keine Ahnung wie ich da weiterkommen soll.
Schöne Wochenende an alle.
Diese Wochenende haben wir IOT Wetter 👍

**Comment by hobbyquaker** [comment]
Log Dich mal per SSH auf der CCU ein und zeig die Ausgabe von `tail -F /var/log/messages` während eines Updateversuchs. Ich vermute dass das RAM zu knapp ist um das .tar.gz zu entpacken. Könnte helfen Node-RED vor dem Update zu stoppen, wenn möglich Mediola auch. Ich rate auch grundsätzlich eher davon ab RedMatic _und_ Mediola auf einer CCU mit 1GB RAM einzusetzen, beides sind ziemliche Speicherfresser...

> Kann man die CCU SW incl. AddOns auch auf einem Intel NUC 7 mit i3 Prozessor unter UBUNTU server installieren und zum Laufen bekommen?

Joa, hiermit: https://github.com/alexreinert/debmatic/ - allerdings müssen Addons angepasst werden, CUxD gibts glaube ich schon, RedMatic wird es aber nicht geben (man kann aber stattdessen einfach ein "normales" Node-RED mit node-red-contrib-ccu nutzen). Such dazu mal nach Debmatic im Homematic Forum.

**Comment by str3000** [comment]
Hallo hobbyquaker,
ich kann wieder updates machen. Ein stoppen von Redmatic oder mediola (geht gar nicht) hat noch nichts geholfen.
Nach der Deinstallation von Mediola konnte ich das aktuelle Update installieren.
Problem gelöst, vielen Dank!

Ob es am zu wenig Speicher liegt habe ich nicht ermitteln können. Es sind extrem viele messages (Errors ) bei vorhanden. Die Meldungen habe ich erst mal gesichert. Die ssh Verbindung wurde auch kurz nach Aktivierung des Updates geschlossen.
Ich habe vermutlich jetzt ein paar Infos von Problemen die andere auch haben. Werde die, wenn ich dazukommen, in den Thread einstellen. Vielleicht finde ich ja auch selbst etwas raus.

Hauptproblem:
ccu3-webui daemon.err node-red[999]: [ccu-connection:NUC7-mqtt] getRegaPrograms Error: connect ECONNREFUSED 192.168.0.50:8181
(Port ist gar nicht so konfiguriert! - sieht eher nach einem Bug aus)
