### ISSUE TITLE
node-red-contrib-alexa-local: Gerät wird nicht gefunden. Portproblem?

### ISSUE THREAD

**Issue by FordAndii** [rdmtc/RedMatic#167]
Hallo, ich habe mein Problem hier (https://homematic-forum.de/forum/viewtopic.php?f=77&t=48283&start=10#p495751) schon gepostet, aber leider konnte niemand helfen.

Redmatic läuft bei mir in der neuesten Version auf der CCU3. In der Firewall der CCU3 sind (zu Testzwecken) erstmal alle Ports freigegeben. Trotzdem wird der von mir angelegte Alexa-Node nicht gefunden, wenn ich mittels der Alexa-App (auf Android) nach neuen Geräten suche.

Der Node zeigt das Label "discovery (p:40123)" mit einem gelben Punkt.

Ich weiß nicht, ob es sich um ein Redmatic-Problem handelt. Evtl. kann die Alexa-App keine Geräte detektieren? Dagegen spricht, dass es in der App die Option gibt, nach neuen Geräten zu suchen. Leider habe ich kein anderes Alexa-Gerät, mit dem ich die Suche ausprobieren kann, sondern nur Sonos-Lautsprecher, die die Suche nicht unterstützen.

Evtl. handelt es sich auch um ein Redmatic-spezifisches Problem. Mir scheint, als würden die meisten Node Red nicht als Add-On auf der CCU, sondern auf separater Hardware laufen lassen, und diejenigen scheinen keine Probleme mit dem Detektieren neuer Alexa-Geräte zu haben.

**Comment by hobbyquaker** [comment]
> Evtl. handelt es sich auch um ein Redmatic-spezifisches Problem.

Zumindest scheint es kein generelles Problem zu sein, es gibt ja einige User die erfolgreich node-red-contrib-alex-local mit RedMatic einsetzen.

> und diejenigen scheinen keine Probleme mit dem Detektieren neuer Alexa-Geräte zu haben.

Naja, das sehe ich anders, speziell mit dem Discovery über die App wurden bereits Probleme gemeldet:
* https://github.com/originallyus/node-red-contrib-alexa-local/issues/80
* https://github.com/originallyus/node-red-contrib-alexa-local/issues/91

Warum nicht einfach node-red-contrib-alexa-home-skill nutzen? Ist kostenlos und bietet mehr Möglichkeiten als alexa-local.

**Comment by hobbyquaker** [comment]
Am Ende des ersten Issues ist beschrieben warum das mit der App nicht geht:

> No, cannot work without Echo(recently only Echo 1st gen, Echo dot 1st gen, Echo dot 2nd gen, are running smoothly and fully support), the Amazon Echo will talk to the node locally, so that this node named Alexa-Local.
Alexa APP even ask Echo to discovery the Alexa-Local node locally.

**Comment by FordAndii** [comment]
Danke für die Tipps! Ich versuche es mal mit node-red-contrib-alexa-home-skill.
