### ISSUE TITLE
RedMatic Update von 3.0.1 auf 3.3.0

### ISSUE THREAD

**Issue by RedBaron2020** [rdmtc/RedMatic#169]
Hallo,
ich versuche wie in der Anleitung das Update von RedMatic auf meiner CCU3.
Leider ist nach dem Update (drüber installieren) die Version immer noch auf 3.0.1.

Was mache ich falsch???
Deinstallieren soll man ja nicht, ich denke das dann alle meine Folws weg sind!?

Wo kann ich schauen was nicht klappt???

Gruß
Carsten
![2019-03-21 18_06_41-HomeMatic WebUI](https://user-images.githubusercontent.com/48803321/54770818-4738dd80-4c04-11e9-8fbc-fbbc4ebde008.png)

**Comment by hobbyquaker** [comment]
Hab das Update eben nochmal durchgespielt und Screenshots der einzelnen Schritte angefertigt:

1. Nach dem Klick auf Installieren wird das .tar.gz wird hochgeladen: <img width="1303" alt="update1" src="https://user-images.githubusercontent.com/2503307/54775193-c252c180-4c0d-11e9-9d2c-1c85f56dea94.png">
2. Nachdem beim Hochladen die 100% erreicht wurden meldet der Browser "Warten auf..." - das dauert circa **2 Minuten**: <img width="1303" alt="update2" src="https://user-images.githubusercontent.com/2503307/54775252-e0b8bd00-4c0d-11e9-99b1-971af8cdb198.png">
3. Nun erscheint ein Poupup, man klickt den "Installation Starten" Button: <img width="1303" alt="update3" src="https://user-images.githubusercontent.com/2503307/54775290-f6c67d80-4c0d-11e9-9086-07b120d14b5a.png">
4. Es erscheint ein weiteres Popup: <img width="1303" alt="update4" src="https://user-images.githubusercontent.com/2503307/54775331-08a82080-4c0e-11e9-9244-f03d045e9229.png">
5. Nun macht die CCU einen Reboot, es dauert circa **7 Minuten** bis sie wieder erreichbar ist.

Bis zu welchem Schritt bist Du noch gekommen?

Als eine Mögliche Ursache vermute ich zuwenig RAM. Bin mir nicht sicher wie genau der Addon-Installationsprozess abläuft, aber es könnte sein dass das .tar.gz in eine RAM-Disk/tmpfs ausgepackt wird und dadurch viel RAM-Bedarf entsteht, muss ich noch rausfinden. Wenn ich das richtig sehe läuft bei Dir auch Mediola, das fußt wie RedMatic auch auf Node.js, das braucht auch sehr viel RAM. Ich rate auch eher davon ab Mediola _und_ RedMatic gleichzeitig einzusetzen, ich halte das eine Gigabyte RAM der CCU3 dafür für zu knapp.

**Comment by hobbyquaker** [comment]
Bin optimistisch dass dieses Problem mit v4.0.0 aus der Welt ist und schließe hier mal. Falls es erneut zu Problemen bei Installation/Update kommt bitte einen neuen Issue eröffnen.

**Comment by jens-maus** [comment]
@hobbyquaker Siehe hier (https://homematic-forum.de/forum/viewtopic.php?f=77&t=49972&p=501396#p501396): Unter RaspberryMatic läuft der Upload von Dateien via WebUI nicht im RAM (`/var/tmp`) sondern auf der SD bzw. eMMC Karte (`/usr/local/tmp`) ab. D.h. dort sollte es nicht zu dem hier festgestellten Problem kommen.
