### ISSUE TITLE
RedMatic Startet nicht - Context File korrupt

### ISSUE THREAD

**Issue by Jemeins** [rdmtc/RedMatic#171]
Mar 22 18:49:24 Raspberrymatic daemon.err node-red[2741]: Error: Error loading context store: SyntaxError: Unexpected token u in JSON at position 0
Mar 22 18:49:24 Raspberrymatic daemon.err node-red[2741]:     at /usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/context/index.js:177:15
cat: can't open '/var/log/messages.0': No such file or directory

**Comment by hobbyquaker** [comment]
Oha, immer wieder was Neues ;-) Da scheint das Context-File kaputt zu sein. Lösch es einfach mal, dann sollte Node-RED wieder starten. Wo Du es findest ist im RedMatic UI ersichtlich, siehe https://github.com/rdmtc/RedMatic/wiki/Context-Storage

Ich nehm mal auf die Todo: Context-Storage Datei auf valides JSON validieren im Startscript um das in Zukunft zu verhindern. Warum das File kaputt ist ist natürlich auch noch ne gute Frage, werde mal nachforschen.
