### ISSUE TITLE
RedMatic 3.3.1 / node-red-contrib-ccu@2.0.4 - Homekit Nodes zeigen Status "partly connected"

### ISSUE THREAD

**Issue by Jemeins** [rdmtc/RedMatic#172]
Nach Update auf 3.3.1 ist Homekit nur "partly connected".
Downgrade auf 3.3.0 i.o.

**Comment by udochrist** [comment]
same here..

**Comment by str3000** [comment]
me too

**Comment by hobbyquaker** [comment]
ist die Funktion aller Schnittstellen die ihr in HomeKit nutzt noch gegeben oder tut irgendwas nicht mehr?

**Comment by hobbyquaker** [comment]
Hab's (glaube/hoffe ich) gefunden und gefixt. War wirklich nur die Anzeige, sollte in node-red-contrib-ccu Version 2.0.5 wieder richtig angezeigt werden. Bis es ein neues RedMatic Release gibt wo das drinsteckt könnt ihr auch vorab node-red-contrib-ccu über den Palette Manager von Node-RED aktualisieren.

**Comment by udochrist** [comment]
Bei mir konnten die Geräte nicht mehr über HomeKit gesteuert werden. Der HomeKit Node war „partially connected“, Schaltbare Variablen waren rot. Downgrade auf 3.3.0 und es läuft alles wieder perfekt

**Comment by hobbyquaker** [comment]
wär cool wenn du mal das node-red-contrib-ccu auf 2.0.4 hochziehen könntest und mit Bescheid gibst ob es damit passt. Falls ja bau ich dann heut oder morgen Abend ein neues RedMatic Release wo das drinsteckt :)

**Comment by hobbyquaker** [comment]
Eben RedMatic v3.3.2 veröffentlicht, damit sollte das nun passen.

**Comment by udochrist** [comment]
3.3.2 funktioniert bei mir. connected und steuerbar über die Home.app

**Comment by hannoverRed** [comment]
Hi,

Seit dem update auf 5.3.10 habe ich bei den HomeKit Geräten partly connected

Die HomeKit Cams gehen aber noch
