### ISSUE TITLE
Versionierungen RedMatic allgemein

### ISSUE THREAD

**Issue by spiu16** [rdmtc/RedMatic#174]
@hobbyquaker: Ich hätte mal eine ganz allgemeine Frage: Wie gehst du grundsätzlich bei der Versionierung vor? Nach welchen Kriterien erhöhen sich die Ziffern? Was ist der Unterschied ob z.B. 3.0.1 oder 3.1.0? 
Danke und Gruß

**Comment by hobbyquaker** [comment]
ich versuche mich sogut es geht an semver 2.0 zu halten: https://semver.org/lang/de/
major erhöhe ich zudem wenn ich weitreichende änderungen am build-, installations- oder updateprozess durchführe oder Node-RED ein milestone release hatte.

**Comment by spiu16** [comment]
ok, danke.
