### ISSUE TITLE
HmIP-SPI => CURRENT_ILLUMINATION => Invalid parameter or value

### ISSUE THREAD

**Issue by Tscherno** [rdmtc/RedMatic#175]
Ich habe eben versucht mit einem Value-Node den Wert von CURRENT_ILLUMINATION ausgeben zu lassen. Dabei wirft er eine Expection:

```
msg : string[143]
"rpc > HmIP-RF setValue ["000C170999F1C4:1","CURRENT_ILLUMINATION",{"explicitDouble":163830}] < Error: XML-RPC fault: Invalid parameter or value"
```

Ich bin der Meinung, dass das schon funktioniert hat. Seit ein paar Tagen geht auch meine Präsenzmelder Logik nicht mehr. Das könnte mit einem der letzten Updates zusammen passen.

**Comment by hobbyquaker** [comment]
der Fehler sagt dass versucht wurde etwas auf dem Datenpunkt zu setzen, das kann nicht funktionieren da er ReadOnly ist. Ist am Eingang des Value Nodes was angeschlossen?
