### ISSUE TITLE
Redmatic - CCU3 - Taster HmIP-WRC6

### ISSUE THREAD

**Issue by RedBaron2020** [rdmtc/RedMatic#176]
Hallo,

Meine Frage an eq-3:
 
Text: Guten Tag, ich nutze die CCU3 und parallel auf der CCU3 Node-Red. Nun habe ich mir den HmIP-WRC6 eingebunden. Ich nutze die Taster direkt mit HmIP Geräten (Ventil ECO-Mode). Die Taster die in der CCU3 nicht verknüpft sind kann ich nicht in der Node-Red nutzen. Die Singale vom Sender/Taster kommen in Node-Red erst an wenn ich disen in der WebUI mit einer Funktion belegt habe! Ist dieses Verhalten normal oder habe ich was falsch gemacht. Ich hoffe Sie können mir weiterhelfen oder muss ich mich an Node-Red wenden?

Die Antwort: 

Allerdings haben wir keine Erfahrungswerte mit dem Einsatz von Node-RED vorliegen. Bitte wenden Sie sich in Ihrem Fall an den Support von Node-RED.

Nun bin ich hier, gibt es eine Erklärung dafür  das ich die Taster erst in der CCU3 benutzen muss damit die Signale in Node-Red auch ankommen?
Oder mache ich was falsch?

Gruß Carsten Krug 

PS: Ich habe die Version 3.3.0 installiert.

**Comment by hobbyquaker** [comment]
Das ist "normal". Auf den Tasterkanälen muss eine Verknüpfung mit den "Central Device" bestehen sonst empfängt die CCU keine Events (und somit Node-RED auch nicht). Entweder mit dem Homematic Manager auf den Kanal rechtsklicken und "ReportValueUsage" auswählen oder auf der CCU ein "Dummy-Programm" anlegen dass auf Tastendruck reagiert und nichts macht (kann danach auch wieder gelöscht werden).

**Comment by fabsewup** [comment]
Leider empfange ich keine Events in Redmatic. Weder als Value mit Dummyprogramm, richtigen Programm, oder auch Homematic Manager "reportValueUsage".

Mittels Programm auf der CCU funktioniert der WRC6 einwandfrei.

Ich habe es auch über das rpc Event probiert. Auch hier bekomme ich über keinen der 6 Kanäle ein Event.

Im Debug wird keinerlei Reaktion angezeit.

Hat hier jemand noch eine Idee woran dies liegen könnte?

**Comment by fabsewup** [comment]
Leider empfange ich keine Events in Redmatic. Weder als Value mit Dummyprogramm, richtigen Programm, oder auch Homematic Manager "reportValueUsage".

Mittels Programm auf der CCU funktioniert der WRC6 einwandfrei.

Ich habe es auch über das rpc Event probiert. Auch hier bekomme ich über keinen der 6 Kanäle ein Event.

Im Debug wird keinerlei Reaktion angezeit.

Hat hier jemand noch eine Idee woran dies liegen könnte?

**Comment by DamianosS** [comment]
Folgender Weg hat bei mir funktioniert:
 - für jede Taste des HmIP-WRC6 anlegen eines Programms in der ReGa
 - Ausführen des Programms
 - Löschen des Programms

Danach sind die Events für den HmIP-WRC6 in der Redmatic angekommen.
