### ISSUE TITLE
Package Installation schlägt fehl - An error occured

### ISSUE THREAD

**Issue by TRehfeldt** [rdmtc/RedMatic#178]
Hallo Sebastian, 
vielen Dank für das innovative Plug-In. Deine Lösung gefällt mir sehr gut.  
Ich möchte meine piVCCU mit homebridge durch das AddOn ersetzen. Dafür habe ich RaspberryMatic (3.45.5.20190330) frisch installiert. Solange ich meine alte Config nicht übernehme, kann ich RedMatic mit redmatic-homekit erfolgreich installieren. Sobald ich aber meine alte Config von der piVCCU und RedMatic (Version: 4.0.3) installiere schlägt die Installation von allen Package fehl (u.A. redmatic-homekit). 

Ich habe nun schon viel versucht und den Raspberry mehrmals neu aufgesetzt. Da meine CCU Config recht umfangreich ist, scheidet eine Neukonfiguration aus. 

Hier das Log:
```
{
   "ccu": {
      "VERSION": "3.45.5.20190330",
      "PRODUCT": "raspmatic_rpi3",
      "PLATFORM": "rpi3"
   },
   "redmatic": "4.0.3",
   "nodejs": "10.15.3",
   "ain2": "3.0.0",
   "node-red": "0.20.3",
   "npm": "6.9.0",
   "node-red-contrib-ccu": "2.0.6",
   "node-red-contrib-combine": "1.7.1",
   "node-red-contrib-sun-position": "0.2.9",
   "node-red-dashboard": "2.14.0",
   "node-red-node-email": "1.3.0",
   "node-red-node-rbe": "0.2.4",
   "redmatic-led": "1.0.0",
   "redmatic-webapp": "0.2.2"
}

Apr 02 20:05:25

Apr  2 20:05:27 homematic daemon.info redmatic: RedMatic v4.0.3 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Apr  2 20:05:27 homematic daemon.info redmatic: Starting Node-RED
Apr  2 20:05:32 homematic daemon.info node-red[1011]: Welcome to Node-RED
Apr  2 20:05:32 homematic daemon.info node-red[1011]: ===================
Apr  2 20:05:32 homematic daemon.info node-red[1011]: Node-RED version: v0.20.3
Apr  2 20:05:32 homematic daemon.info node-red[1011]: Node.js  version: v10.15.3
Apr  2 20:05:32 homematic daemon.info node-red[1011]: Linux 4.19.30 arm LE
Apr  2 20:05:32 homematic daemon.err node-red: (node:1011) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Apr  2 20:05:34 homematic daemon.info node-red[1011]: Loading palette nodes
Apr  2 20:05:38 homematic daemon.info node-red[1011]: Dashboard version 2.14.0 started at /addons/red/ui
Apr  2 20:05:39 homematic daemon.info node-red[1011]: node-red-contrib-ccu version: 2.0.6
Apr  2 20:05:40 homematic daemon.info node-red[1011]: Settings file  : /usr/local/addons/redmatic/lib/settings.js
Apr  2 20:05:40 homematic daemon.info node-red[1011]: Context store  : 'default' [module=memory]
Apr  2 20:05:40 homematic daemon.info node-red[1011]: Context store  : 'file' [module=localfilesystem]
Apr  2 20:05:40 homematic daemon.info node-red[1011]: User directory : /usr/local/addons/redmatic/var
Apr  2 20:05:40 homematic daemon.warn node-red[1011]: Projects disabled : editorTheme.projects.enabled=false
Apr  2 20:05:40 homematic daemon.info node-red[1011]: Flows file     : /usr/local/addons/redmatic/var/flows.json
Apr  2 20:05:40 homematic daemon.info node-red[1011]: Starting flows
Apr  2 20:05:40 homematic daemon.info node-red[1011]: [ccu-connection:localhost] local connection on ccu >= v3.41 detected
Apr  2 20:05:41 homematic daemon.info node-red[1011]: [ccu-connection:localhost] paramsets loaded from /usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/paramsets.json
Apr  2 20:05:42 homematic daemon.info node-red[1011]: [ccu-connection:localhost] paramsets saved to /usr/local/addons/redmatic/var/paramsets.json 1855
Apr  2 20:05:42 homematic daemon.info node-red[1011]: [ccu-connection:localhost] metadata new empty
Apr  2 20:05:42 homematic daemon.info node-red[1011]: Started flows
Apr  2 20:05:42 homematic daemon.info node-red[1011]: Server now running at http://127.0.0.1:1880/addons/red/
Apr  2 20:05:46 homematic daemon.info node-red[1011]: [ccu-connection:localhost] Interfaces: ReGaHSS, BidCos-RF, HmIP-RF, VirtualDevices
Apr  2 20:05:46 homematic daemon.info node-red[1011]: [ccu-connection:localhost] ReGaHSS binrpc port 31999 connected
Apr  2 20:05:46 homematic daemon.info node-red[1011]: [ccu-connection:localhost] init BidCos-RF binrpc://127.0.0.1:2047 nr_AKHydZ_BidCos-RF
Apr  2 20:05:46 homematic daemon.info node-red[1011]: [ccu-connection:localhost] init HmIP-RF http://127.0.0.1:2048 nr_D24DjW_HmIP-RF
Apr  2 20:05:47 homematic daemon.info node-red[1011]: [ccu-connection:localhost] init VirtualDevices http://127.0.0.1:2048 nr_D24DjW_VirtualDevices
Apr  2 20:05:47 homematic daemon.info node-red[1011]: [ccu-connection:localhost] binrpc server listening on binrpc://127.0.0.1:2047
Apr  2 20:05:47 homematic daemon.info node-red[1011]: [ccu-connection:localhost] xmlrpc server listening on http://127.0.0.1:2048
Apr  2 20:05:47 homematic daemon.info node-red[1011]: [ccu-connection:localhost] HmIP-RF http port 32010 connected
Apr  2 20:05:47 homematic daemon.info node-red[1011]: [ccu-connection:localhost] metadata saved to /usr/local/addons/redmatic/var/ccu_localhost.json
Apr  2 20:05:48 homematic daemon.info node-red[1011]: [ccu-connection:localhost] metadata saved to /usr/local/addons/redmatic/var/ccu_localhost.json
Apr  2 20:05:49 homematic daemon.info node-red[1011]: [ccu-connection:localhost] metadata saved to /usr/local/addons/redmatic/var/ccu_localhost.json
Apr  2 20:05:49 homematic daemon.info node-red[1011]: [ccu-connection:localhost] BidCos-RF binrpc port 32001 connected
Apr  2 20:05:57 homematic daemon.info node-red[1011]: [ccu-connection:localhost] VirtualDevices http port 39292 connected
Apr  2 20:06:04 homematic daemon.info node-red[1011]: [ccu-connection:localhost] paramsets saved to /usr/local/addons/redmatic/var/paramsets.json 1885
Apr  2 20:06:15 homematic daemon.info node-red[1011]: [ccu-connection:localhost] paramsets saved to /usr/local/addons/redmatic/var/paramsets.json 1915
Apr  2 20:06:25 homematic daemon.info node-red[1011]: [ccu-connection:localhost] paramsets saved to /usr/local/addons/redmatic/var/paramsets.json 1945
Apr  2 20:06:33 homematic daemon.info node-red[1011]: [ccu-connection:localhost] paramsets saved to /usr/local/addons/redmatic/var/paramsets.json 1974
```

Was kann ich tun um das Problem zu lösen?

Viele Grüße nach Stuttgart, 
Tilmann

**Comment by hobbyquaker** [comment]
Das Log hilft in dem Fall leider nicht weiter. Melde Dich mal per SSH an und zeig mal was folgende Kommandos zurückgeben:
```
source /usr/local/addons/redmatic/home/.profile
redmatic-pkg install redmatic-homekit
```

**Comment by TRehfeldt** [comment]
Hi, 
hier der Output:

# source /usr/local/addons/redmatic/home/.profile
# redmatic-pkg install redmatic-homekit
Get https://github.com/rdmtc/RedMatic/releases/download/v4.0.3/redmatic-pkg-redm                                                      atic-homekit-2.1.2.tar.gz
curl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared                                                       object file: No such file or directory
#
Da scheint es Probleme mit curl zu geben. Hast du eine Idee was das seien kann?

**Comment by hobbyquaker** [comment]
Hmm... Führ mal bitte das aus:

```
echo $LD_LIBRARY_PATH
ls -l /usr/lib/libssl*
ls -l /usr/local/lib
```

**Comment by TRehfeldt** [comment]
# source /usr/local/addons/redmatic/home/.profile
# echo $LD_LIBRARY_PATH
/usr/local/addons/redmatic/lib:/usr/lib:/usr/local/lib
# ls -l /usr/lib/libssl*
lrwxrwxrwx    1 root     root            13 Mar 29 14:11 /usr/lib/libssl.so -> libssl.so.1.1
-rwxr-xr-x    1 root     root        432256 Mar 29 15:11 /usr/lib/libssl.so.1.1
# ls -l /usr/local/lib
ls: /usr/local/lib: No such file or directory

Ich besorge mir mal die Datei libssl.so.1.0.0 und leg sie dort ab.

**Comment by hobbyquaker** [comment]
hmm... das ist seltsam. @jens-maus @akexreinert habt ihr vll ne idee wie das zustande kommt?

**Comment by hobbyquaker** [comment]
hmm... das ist seltsam. @jens-maus @alexreinert habt ihr vll ne idee wie das zustande kommt?

**Comment by jens-maus** [comment]
@hobbyquaker Meine Vermutung ist das @TRehfeldt hier irgendwo ein altes/kaputtes `curl` binary rumliegen hat. Er sollte mal ein `which curl` ausführen.

**Comment by TRehfeldt** [comment]
Mit curl hatte ich unter cuxd schonmal vor einem Jahr Probleme. Vermutlich hängt das immer noch in der Config drin. "which curl" gibt "/usr/bin/curl" aus. Ist das korrekt?

**Comment by jens-maus** [comment]
@hobbyquaker In https://github.com/rdmtc/RedMatic/blob/master/addon_files/redmatic/bin/redmatic-pkg#L44 würde ich daher auch explizit `/usr/bin/curl` Mit ganzen Pfad aufrufen damit er nicht versehentlich ein anderes curl binary aufruft.

@TRehfeldt Mal bitte den Folgenden Befehl aufrufen:

`find /usr/local -name curl`

Und die Ausgaben zeigen.

**Comment by TRehfeldt** [comment]
# find /usr/local -name curl
/usr/local/addons/cuxd/curl
/usr/local/addons/cuxd/extra/curl

**Comment by jens-maus** [comment]
@TRehfeldt und was gibt dann folgendes aus:

```
ls -la /usr/local/addons/cuxd/curl
ls -la /usr/local/addons/cuxd/extra/curl
```

und folgender Befehl:

```
/usr/bin/curl —version
```

**Comment by TRehfeldt** [comment]
ls -la /usr/local/addons/cuxd/curl
lrwxrwxrwx    1 root     root            10 Apr  2 21:44 /usr/local/addons/cuxd/curl -> extra/curl

ls -la /usr/local/addons/cuxd/extra/curl
lrwxrwxrwx    1 root     root            13 Apr  2 21:44 /usr/local/addons/cuxd/extra/curl -> /usr/bin/curl

/usr/bin/curl --version
/usr/bin/curl: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by jens-maus** [comment]
@TRehfeldt This is indeed very strange. Which RaspberryMagic image did you use? pi3 or pi0?

**Comment by TRehfeldt** [comment]
Hi Jens, 
i use the pi3 Image. Is it possible to reinstall curl?

**Comment by jens-maus** [comment]
@TRehfeldt More ideas. Please execute:

```
ls -la /usr/bin/curl
```

```
ls -la /usr/lib/*curl*
```

```
find /usr/local -name "*curl*"
```

**Comment by TRehfeldt** [comment]
okay, here are the Output:

```
ls -la /usr/bin/curl
-rwxr-xr-x    1 root     root        120556 Mar 29 15:11 /usr/bin/curl
```

```
ls -la /usr/lib/*curl*
lrwxrwxrwx    1 root     root            16 Mar 29 14:17 /usr/lib/libcurl.so -> libcurl.so.4.5.0
lrwxrwxrwx    1 root     root            16 Mar 29 14:17 /usr/lib/libcurl.so.4 -> libcurl.so.4.5.0
-rwxr-xr-x    1 root     root        363316 Mar 29 15:11 /usr/lib/libcurl.so.4.5.0
```

```
find /usr/local -name "*curl*"
/usr/local/addons/cuxd/curl
/usr/local/addons/cuxd/extra/curl
/usr/local/addons/redmatic/lib/libcurl.so.4.5.0
/usr/local/addons/redmatic/lib/libcurl.so
/usr/local/addons/redmatic/lib/libcurl.la
/usr/local/addons/redmatic/lib/libcurl.so.4
```

**Comment by hobbyquaker** [comment]
ouch. no clue why i have libcurl in the redmatic lib folder. shame on me, guess that's the root cause. and thanks @jens-maus !
@TRehfeldt give me a moment, will check this asap

**Comment by jens-maus** [comment]
@hobbyquaker perfect. we got it :) So get rid of libcurl and everything should work fine again.

**Comment by hobbyquaker** [comment]
@TRehfeldt could you try just to remove these files:
`rm /usr/local/addons/redmatic/lib/libcurl*`

and afterwards try again
```
source /usr/local/addons/redmatic/home/.profile
redmatic-pkg install redmatic-homekit
```

**Comment by TRehfeldt** [comment]
That's it! Very good job. Many thanks for your help.

**Comment by hobbyquaker** [comment]
Fixed with https://github.com/rdmtc/RedMatic/releases/tag/v4.0.4
