### ISSUE TITLE
LED node geht nicht mehr

### ISSUE THREAD

**Issue by Maladus** [rdmtc/RedMatic#179]
Durch den Watchdog Timer in der neuen RaspberryMatic Version wird die Led wieder gestartet mit einer Alarmmeldung.

**Comment by hobbyquaker** [comment]
Sollte mit RedMatic 4.1.0 gefixt sein. Bitte gib Bescheid ob es funktioniert.

**Comment by Maladus** [comment]
Kann ich bestätigen mit 4.1.0 funktioniert es wieder.
Danke
