### ISSUE TITLE
HomeKit HM-Sec-SCo Doppelte Darstellung

### ISSUE THREAD

**Issue by VisitorSam** [rdmtc/RedMatic#182]
Die Optischen HM Fensterkontakte (HM-Sec-SCo) werden im Homekit doppelt erzeugt.
Es sollte daher die Auswahl des Hauptgerätes oder vom Kanal 1 Deaktivierbar gemacht werden.

**Comment by hobbyquaker** [comment]
Kann ich nicht reproduzieren? Kann es sein dass Du die Fensterkontakte umkonfiguriert hast im HomeKit-Homematic Node und danach Node-RED nicht neugestartet hast? (https://github.com/rdmtc/RedMatic/wiki/Homekit#nutzungshinweise)

**Comment by VisitorSam** [comment]
Ich hatte die Kontakte Neu Konfiguriert als "Fenster" Hab jetzt nochmal Node-RED gestoppt und gestartet danach dauerte es etwas und sind verschwunden.
