### ISSUE TITLE
HELP - Openweathermap für Virtuelle CUxD Wetterstation

### ISSUE THREAD

**Issue by VisitorSam** [rdmtc/RedMatic#186]
Ich Versuche mit Node-RED die Daten von Openwathermap in die Virtuelle CUxD Wetterstation zu bekommen um die Wetterdaten in der HomeMatic zu verwenden und anzuzeigen.

**Comment by Sineos** [comment]
Hilft das: http://noderedguide.com/node-red-lecture-2-building-your-first-flows-15/

Etwa ab Mitte der Seite

**Comment by Hypnos3** [comment]
Bitte, hier eine Anleitung:
https://github.com/rdmtc/RedMatic/wiki/Openweathermap

Wenn jemand noch ein anderes CUxD Device kennt, immer her damit.

**Comment by litti** [comment]
Super! 

 

Müsste es nicht statt

 

aus der Palette die OpenWeathermap Node ohne Ausgang in den Flow ziehen

 

aus der Palette die OpenWeathermap Node ohne Eingang in den Flow ziehen

 

heißen? 

 

Von: Hypnos <notifications@github.com> 
Gesendet: Donnerstag, 11. April 2019 12:08
An: rdmtc/RedMatic <RedMatic@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [rdmtc/RedMatic] HELP - Openweathermap für Virtuelle CUxD Wetterstation (#186)

 

Bitte, hier eine Anleitung:
https://github.com/rdmtc/RedMatic/wiki/Openweathermap

Wenn jemand noch ein anderes CUxD Device kennt, immer her damit.

**Comment by Hypnos3** [comment]
Das war ein Test ob es überhaupt jemand ließt ;)
--> ist korrigiert...

**Comment by VisitorSam** [comment]
Top, geht das nur mit dem "90 Universal Wrapper Device" oder kann ich auch ein Virtuellen CuXD"HM-WDS100-C6-O" damit füttern?

Hab ich irgendwelche Nachteile oder Vorteile durch das Wrapper Device?

**Comment by hobbyquaker** [comment]
Ich denk das ist eine recht CUxD spezifische Frage die eher wenig mit RedMatic/Node-RED zu tun hat. Würde eher empfehlen das im CUxD-Forum zu fragen: https://homematic-forum.de/forum/viewforum.php?f=37

**Comment by Hypnos3** [comment]
Laut CUxD Handbuch gibt es kein `HM-WDS100-C6-O` als CUxD device. Es gibt da ein `(31) Kombisensor KS200/KS300`, der einer Wetterstation am nächsten kommt. Der hat aber laut Handbuch keinen Datenpunkt den man per Script/Node-Red beschreiben könnte.
Hier ist wirklich die Frage, im Homematic Forum, wie man das bewerkstelligen kann.
