### ISSUE TITLE
node-ical

### ISSUE THREAD

**Issue by Christoph22** [rdmtc/RedMatic#188]
Hab in ner Facebook Gruppe node-ical gesehen, und versucht es unter Redmatic zu installieren.

npm install node-ical
node: /usr/local/lib/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by node)

https://github.com/jens-maus/node-ical
https://nodered.org/docs/writing-functions.html?#loading-additional-modules

**Comment by hobbyquaker** [comment]
Hast Du das ccu-addon-mosquitto installiert? Ich befürchte ich hab da ein bösen Fehler gemacht.

**Comment by Christoph22** [comment]
Ja

**Comment by hobbyquaker** [comment]
fix kommt asap. 
referenz: https://github.com/hobbyquaker/ccu-addon-mosquitto/issues/8
