### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by ma-gu-16** [rdmtc/RedMatic#192]
Hi, 

Ich versuche diverse HTTP request zu empfangen oder zu senden. 
Jedoch blockiert mich der Browser/Dashboard UI.

Ist es möglich bzw es sollte möglich sein die ORIGIN irgendwo zu setzen. Ebenso die Methoden, PUT/GET/PUSH, usw.

**Comment by hobbyquaker** [comment]
Was genau versuchst Du zu tun? XHR Requests aus einer Webseite heraus die vom Node-RED Webserver geliefert wurde? Dann muss der Server den Du anfragst eben `Access-Control-Allow-Origin: *` Header liefern. Oder versteh ich Dich falsch?

**Comment by ma-gu-16** [comment]
z.b. den stream einer ipcam im selben netzwerk. schon alleine wenn diese kein ssl / https  hat, wird der stream geblockt. 

da das webui unter https läuft.

**Comment by hobbyquaker** [comment]
Beim Thema tls (https vs http) lässt sich nichts machen. Entweder dann das webui selbst auch ohne tls nutzen oder als Workaround einen Reverse Proxy vor die Kamera setzen der tls davorsetzt und header manipulieren kann. Oder irgendeine Surveillance-Software die die Streams selbst nochmal auf ihrem eigenen Webserver bereitstellt dazwischen hängen, wie z.B. Motioneye. 
Zum Thema CORS: der springende Punkt bei den `allow-origin-*` Headern ist: die müssen von dem Webserver der Ressource die angefragt wird gesetzt werden, nicht von dem Webserver der die Webseite geliefert hat. Da kann ich also auch nichts machen.

**Comment by ma-gu-16** [comment]
alles klar, kauf ich mir eine neue cam :-) die ist eh schon etwas älter.
