### ISSUE TITLE
Feature Request: Kleine Info Texte und Links auf der Settings Seite

### ISSUE THREAD

**Issue by helje5** [rdmtc/RedMatic#194]
Hier stellen sich die üblichen Fragen:
- was ist ein Kontext?
- was sind "Projects"?
- was sind die Werte für Auth (RegaHSS? Creds? None? Wozu?)

Für 2-3 Zeilen Text dazu plus Link zum Thema im Wiki ist da locker Platz ;-)

Weiterhin:
- [x] 86800? Frau kann ahnen dass das der Session Timeout in Sekunden ist, hübscher wäre es, wenn es auch dasteht und weswegen man das ändern will/sollte
- [x] statt "None" in den Auth Popups wäre "Keine Authentifizierung" oder so hübscher
- [ ] statt Auth Popups wären Auth Radiogroups hübscher
- [ ] Enabled Popup? Warum keine Checkbox: `[ ] Enable Projects`

<img width="961" alt="Bildschirmfoto 2019-04-19 um 13 12 39" src="https://user-images.githubusercontent.com/7712892/56421870-df2df380-62a4-11e9-9ce3-c0cf08b30003.png">

**Comment by hobbyquaker** [comment]
Zu 
> statt Auth Popups wären Auth Radiogroups hübscher
> Enabled Popup? Warum keine Checkbox: [ ] Enable Projects
nehme ich gerne Pull Requests an, aber ich hab jetzt bei der Abwägung Faulheit vs. Dringlichkeit für Faulheit entschieden ;-)
