### ISSUE TITLE
Feature Request: Aktor-Auslösung manuell ?

### ISSUE THREAD

**Issue by garosp** [rdmtc/RedMatic#195]
Gibt es eine Möglichkeit der Status-Meldung ein Kennzeichen mit zu geben wodurch der Aktor ausgelöst wurde. Ich nutze zur Kommunikation mit der CCU ausschließlich MQTT und suche nach einer Möglichkeit einen im msg-Object z.B. einen msg.submitter "set" zu übergeben und dann nach Auslösung mittels "state" zurück zu bekommen. Einsatzzweck wäre z.B. eine automatische Jalousie-Steuerung mittels manueller Taster-Eingabe zu übersteuern - dann muss ich wissen wer der Auslöser war. Vielleicht hat aber auch jemand eine andere Idee.

**Comment by hobbyquaker** [comment]
Homematic Geräte stellen die Info ob ein Befehl über einen Druck auf Ihre Taste oder über Funk ausgelöst wurde leider nicht zur Verfügung.

**Comment by garosp** [comment]
thx
