### ISSUE TITLE
Config option to choose if Backup size should be reduced or if everything should be included

### ISSUE THREAD

**Issue by hobbyquaker** [rdmtc/RedMatic#198]

**Comment by hobbyquaker** [comment]
@jp112sdl - könnte iirc für Dich interessant sein: das Aussparen bestimmter RedMatic Verzeichnisse aus dem Backup ist ab 4.4.0 abschaltbar

**Comment by jp112sdl** [comment]
Schau ich mir mal an!
Wobei ich nach wie vor der Meinung bin, dass ich lieber alles komplett im Backup haben möchte, um mich nach einem Restore (bei jeder neuen RaspberryMatic Version) nicht weiter kümmern zu müssen.
