### ISSUE TITLE
Delay Node mittels msg.delay einstellen

### ISSUE THREAD

**Issue by SkylightXD** [rdmtc/RedMatic#199]
Hallo zusammen,

ich möchte einen Delay über das Dashboard variabel einstellen.
Mit einem festen Wert nutze ich aktuell den Delay Node, das funktioniert auch super, aber die Option "Verzögerung mit msg.dekay bestimmen" bringt mich zum verzweifeln bzw. ich bekomme es nicht umgesetzt.
Könnt ihr mir sagen, wie ich diesen Node bedienen muss?

Danke und Grüße
Christoph

**Comment by Hypnos3** [comment]
so geht es
![image](https://user-images.githubusercontent.com/12692680/57176907-598e7400-6e5e-11e9-8a56-565a9ce8cbdb.png)

Zu beachten ist, das die zeit in Millisekunden ist.
`[{"id":"8f829fbb.15688","type":"delay","z":"41c55cf0.be39c4","name":"","pauseType":"delayv","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":555,"y":2325,"wires":[["5060dd6d.61efc4"]]},{"id":"1f1d738c.fee4bc","type":"inject","z":"41c55cf0.be39c4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":180,"y":2325,"wires":[["d551825d.5b5ff"]]},{"id":"d551825d.5b5ff","type":"change","z":"41c55cf0.be39c4","name":"","rules":[{"t":"set","p":"delay","pt":"msg","to":"delayTime","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":365,"y":2325,"wires":[["8f829fbb.15688"]]},{"id":"5060dd6d.61efc4","type":"debug","z":"41c55cf0.be39c4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":750,"y":2325,"wires":[]},{"id":"795a4917.71d6a8","type":"inject","z":"41c55cf0.be39c4","name":"","topic":"","payload":"1000","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":2385,"wires":[["3af16d1a.206a72"]]},{"id":"b8dbd609.d7ab68","type":"inject","z":"41c55cf0.be39c4","name":"","topic":"","payload":"2000","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":200,"y":2430,"wires":[["3af16d1a.206a72"]]},{"id":"3af16d1a.206a72","type":"change","z":"41c55cf0.be39c4","name":"","rules":[{"t":"set","p":"delayTime","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":400,"y":2400,"wires":[[]]}]`
