### ISSUE TITLE
RedMatic inkompatibel mit RaspberryMatic 3.45.7.20190504

### ISSUE THREAD

**Issue by Matten-Matten** [rdmtc/RedMatic#202]
Kann keine Knoten laden.
![Node-RED _ 192 168 27 42-05 05 2019_16_46_58](https://user-images.githubusercontent.com/32074970/57195661-79ed2a00-6f55-11e9-97be-88d4c5a0eb2c.jpg)

**Comment by hobbyquaker** [comment]
Das liegt an neuen "Sicherheitsmaßnahmen" in RaspberryMatic 3.45.7.20190504. Bin dabei mögliche Lösungen zu evaluieren, bitte um Geduld.

**Comment by Matten-Matten** [comment]
Klar kein Problem. Ich schaue mal ob ich die RPIMatic Vorgänger Version wieder drauf bekomme

**Comment by hobbyquaker** [comment]
https://homematic-forum.de/forum/viewtopic.php?f=65&t=50589

**Comment by hobbyquaker** [comment]
Möglicher Workaround mit RaspberryMatic 3.45.7.20190504
`mount -o remount,rw /`
Datei `/etc/lighttpd/conf.d/setenv.conf` durch diese ersetzen: https://github.com/jens-maus/RaspberryMatic/blob/5cd985194b7d4113f2b5943618fbfb5da5bc54b9/buildroot-external/overlay/base/etc/lighttpd/conf.d/setenv.conf

```
mount -o remount,ro /
/etc/init.d/S50lighttpd restart
```
Node-RED Neustarten, Browsercache leeren - schadet nicht ;-)

**Comment by hobbyquaker** [comment]
Workaround wird mit dem nächsten RaspberryMatic Release nicht mehr nötig sein (siehe https://github.com/jens-maus/RaspberryMatic/pull/619#issuecomment-490051057)

**Comment by Matten-Matten** [comment]
Super danke für die Info.👍

**Comment by spiu16** [comment]
Top!
