### ISSUE TITLE
Verschwinden der Homekit-Einstellungen nach Update

### ISSUE THREAD

**Issue by drMaxxi** [rdmtc/RedMatic#203]
Jedes mal wenn ich ein Update von RedMatic durchführe verschwinden alle Raumzuordnungen, Namensänderungen, etc. Im HomeKit. Dieses Problem habe nicht erst seit dem letzten Update, sondern bereits von Anfang an. Ist dies ein Bug, oder muss ich eine besondere Einstellung tätigen?

**Comment by hobbyquaker** [comment]
Definitiv ein Bug, das darf nicht sein. Ist bei mir auch bisher nie vorgekommen, daher bin ich da auch erstmal ratlos. Passiert das bei Dir _immer_ bei _jedem_ Update? Kam es auch schonmal bei einem Neustart vor oder wirklich _nur_ bei Updates? Eigentlich ist so ein Update sozusagen auch nicht viel mehr als ein Neustart.
Stell auf jeden Fall mal vor dem nächsten Update den Loglevel auf Debug, lade das Log einmal vor und einmal nach dem Update runter und lass es mir zukommen, dann schau ich das an.

**Comment by hobbyquaker** [comment]
Ah und noch ein Tipp dazu: Um nicht alles von Hand neumachen zu müssen falls dieser Bug bei Dir nochmal zuschlägt: es gibt eine HomeKit App die die Einstellungen die in iOS gespeichert sind zu Backuppen: https://itunes.apple.com/de/app/controller-f%C3%BCr-homekit/id1198176727?mt=8
