### ISSUE TITLE
HM-Dis-WM55 Farbdisplay und Redmatic

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/RedMatic#204]
Hallo Hobbyquacker,

nach dem update von 2.0.13 auf 2.0.14 (node-ccu) funktioniert das Display HM-DIS-WM55 (farbe + ePaper) nicht mehr. Habe dieses im Forum auch mit Bilder beschrieben. Egal welche Parameter ich einstelle gibt das Display: "Keine Daten empfangen" aus. Über die Raspberrymatic geht es.

Gruß Thomas

**Comment by ThomasLoeffel** [comment]
Hallo Hobbyquaker,
habe ich im falschen Bereich ein Ticket geschrieben? Oder war das so ok?

Lieben Gruß Thomas

**Comment by hobbyquaker** [comment]
@ThomasLoeffel gib bitte Bescheid ob es mir RedMatic 4.4.2 (bzw. node-red-contrib-ccu 2.0.15) wieder passt.

**Comment by ThomasLoeffel** [comment]
Hallo Hobbyquaker,

mit 4.4.2 und CCU-Node 2.0.15 läuft es wieder geau wie es soll.

Danke Dir !!!!!!!!
