### ISSUE TITLE
node-red-contrib-avr-yamaha funktioniert nicht (UPNP Problem?)

### ISSUE THREAD

**Issue by ma-gu-16** [rdmtc/RedMatic#205]
Hallo,

Frage ist UPnP aktiv bzw der Port 1900 offen und weitergeleitet?

Ich habe ein Problem mit der Node https://github.com/krauskopf/node-red-contrib-avr-yamaha, der empfängt nichts via UpnP.

Gibts da evtl bereits ein bekanntes Problem RasbMatic/RedMatic?

Danke :-)

**Comment by hobbyquaker** [comment]
Hast den Port in der CCU/RaspberryMatic Firewall aufgemacht oder die Firewall ausgeschaltet?

**Comment by hobbyquaker** [comment]
Eben nachgeschaut: daran liegt es nicht (`reuseAddr` ist gesetzt, somit sollte es kein Problem sein wenn andere Dienste auch auf 1900/UDP lauschen) https://github.com/krauskopf/node-red-contrib-avr-yamaha/blob/master/avr-yamaha.js#L325

Jetzt bin ich erstmal Ratlos, mangels Yamaha AVR kann ich das auch nicht testen. Was jetzt interessant wäre: funktionieren die Nodes außerhalb von RedMatic (sprich: kannst Du mal irgendwo ein Node-RED aufsetzen und das testen?). Wenn es dann auch nicht geht müsstest Dich an den Macher dieser Nodes wenden, wenn es außerhalb von RedMatic funktioniert müssten wir hier weiterforschen ;-)

**Comment by ma-gu-16** [comment]
Hi, 

soeben mal nodered neu installiert und nur das module drin, hab auch ein issue dort angelegt. 
bin mir nicht sicher wo das problem ist. 

https://github.com/krauskopf/node-red-contrib-avr-yamaha/issues/13

**Comment by hobbyquaker** [comment]
Hmm, dann würd ich mal so verbleiben: Wir lassen den Issue offen und Du gibst Bescheid wenn Du die Nodes anderswo laufen hast und sie funktionieren - sie aber in RedMatic weiterhin nicht funktionieren (also davon auszugehen ist dass das Problem RedMatic-spezifisch ist) - dann versuch ich Dich zu unterstützen.
