### ISSUE TITLE
Update not possible on Redmatic 3.45.7.20190511

### ISSUE THREAD

**Issue by r100gs** [rdmtc/RedMatic#211]
Hello,

I tried to update from 4.4.1 to 4.6.1 via System-Update, but I always get the error not possible.

Should I try to download it manually and try to update?

Best regards,
Stefan

**Comment by Hypnos3** [comment]
System-Update?

To update the RedMatic AddOn you have to simply install the new Version under "Settings > Systemsteuerung > AnnOn" (German: "Startseite > Einstellungen > Systemsteuerung > Zusatzsoftware"), whicle the old version is still installed.

**Comment by hobbyquaker** [comment]
> via System-Update

you tried to use the [rmupdate](https://github.com/j-a-n/raspberrymatic-addon-rmupdate) addon for the RedMatic installation? That _should_ work, if it fails it might help to take a look at `/tmp/rmupdate-addon-log.txt` (mind that `/tmp` does not survive a reboot).
Of course it's also worth a try if it will work via the "normal" way Hypnos described.
