### ISSUE TITLE
Get Value Node ändert Variablenwert seit V.4.4.3

### ISSUE THREAD

**Issue by CNpunkt** [rdmtc/RedMatic#212]
Seit der Version 4.4.3 ermittelt der Get Value Node nicht mehr nur einen Wert sondern setzt auch den Wert aus dem eingehenden Payload. Wenn ich beispielsweise mit dem Get Value Node eine Systemvariable aus der CCU abfrage und der Payload zuvor "True" ist, so setzt der Get Value Node die Systemvariable auf "True".
Aus meiner Sicht sollte der Get Value Node nur den Wert einer Systemvariablen ermitteln aber nicht abändern.

**Comment by hobbyquaker** [comment]
siehe https://github.com/rdmtc/node-red-contrib-ccu/issues/84

**Comment by hobbyquaker** [comment]
@CNpunkt sollte mit RedMatic 4.7.1 gefixt sein. Bitte gib Bescheid ob es funktioniert.

**Comment by CNpunkt** [comment]
@hobbyquaker mache ich sobald ich wieder updaten kann --> #213

**Comment by CNpunkt** [comment]
@hobbyquaker funktioniert wieder. Vielen Dank!
