### ISSUE TITLE
Aktualisierung nicht mehr möglich

### ISSUE THREAD

**Issue by CNpunkt** [rdmtc/RedMatic#213]
Die Aktualisierung von Version 4.4.2 auf Version 4.7.1 schlägt fehl. Ich versuche, wie mit älteren Versionen auch, über die CCU Zusatzsoftware das Update durchzuführen:
![image](https://user-images.githubusercontent.com/16060613/58165080-4fa2a880-7c87-11e9-8328-a276999fa886.png)

Nach dem automatischen Reboot der CCU wird weiterhin die Version 4.4.2 aufgeführt. Eine Fehlermeldung wird nicht angezeigt. Gibt es eine Möglichkeit über irgendein Logfile herauszufinden warum das Update scheitert?

**Comment by hobbyquaker** [comment]
Hmmm... Nutzt Du die eQ-3 Firmware oder RaspberryMatic? Läuft der Neo Server bei Dir?

Ich vermute die Installation scheitert wegen zu wenig verfügbarem RAM. Eventuell reicht es schon vor dem Update mal Node-RED zu beenden. Falls Du den Neo Server nutzt: Ich rate davon ab RedMatic und Neo gleichzeitig zu nutzen, beide haben hohe Speicheranforderungen, da ist 1GB zu knapp.

Ansonsten würde ich empfehlen es mal mit dem rmupdate Addon https://github.com/j-a-n/raspberrymatic-addon-rmupdate zu versuchen (geht auch wenn es der Name anders suggeriert nicht nur mit RaspberryMatic sondern auch mit der eQ-3 Firmware und geht bei der Addon-Installation sparsamer mit dem RAM um).

**Comment by CNpunkt** [comment]
Ich nutze die eQ-3 Firmware.
Die Deinstallation des Neo Servers und das Beenden von Node-RED vor dem Update haben geholfen.
