### ISSUE TITLE
HomeKit: Sirene HM-Sec-Sir-WM nicht unterstützt?

### ISSUE THREAD

**Issue by CharlyFive** [rdmtc/RedMatic#215]
Hallo, ich habe gerade die Sirene HM-Sec-Sir-WM hinzugefügt. In der HomeApp wird mir angezeigt das dieses Gerät nicht unterstütz wird.

Kann das sein? Deploy und Neustart habe ich gemacht.

![IMG_2672](https://user-images.githubusercontent.com/23129385/58361438-19d01080-7e8f-11e9-8015-bcadf3157e27.png)

**Comment by hobbyquaker** [comment]
Duplicate: https://github.com/rdmtc/RedMatic-HomeKit/issues/118
