### ISSUE TITLE
Problem mit MQTT-Knoten: Ereignisse werden nicht an MQTT-Broker gemeldet

### ISSUE THREAD

**Issue by chrispi68** [rdmtc/RedMatic#217]
Seit Installation der Version 4.7.0 und 4.7.1 werden Ereignisse von meinem HMIP-Präsenzmeldern (HmIP-SPI) und HMIP-Kontakten (HMIP-SWDO) nicht mehr an den MQTT-Broker gemeldet. Ich hatte vorher eine ca. 3 Monate alte Version installiert und damit keinerlei Probleme.

Ist das Problem bekannt?

Viele Grüße
Christoph

**Comment by chrispi68** [comment]
Ich habe jetzt wieder einen Downgrade auf die Version 4.0.5 gemacht und das Problem existiert weiterhin.  Nach einiger Zeit (teilweise mehreren Stunden) kommen im MQTT Broker keine Ereignisse von der CCU mehr an.

Ich habe insgesamt drei CCUs (Version 3). Seltsamerweise tritt das Problem nur bei der dritten CCU auf. Die betreffende CCU ist bei mir ausschließlich mit HMIP-Geräten verknüpft. Ansonsten sind die Flows identisch.

Ich werde weiter analysieren und hier berichten, wenn ich die Ursache gefunden habe.

**Comment by hobbyquaker** [comment]
Ich denk da würd es Sinn machen mal das Loglevel von RedMatic und dem MQTT Broker auf Debug zu stellen und nachzuschauen was die so melden wenn die Verbindung abbricht.

**Comment by chrispi68** [comment]
Danke für den Tipp, werde ich probieren und hier berichten. Momentan habe ich Mosquitto unter Linux 19.1 in Verdacht. Ich habe testweise auf eine ältere Version von Mosquitto unter Windows gewechselt und seit 24 Stunden keinen Abbruch.

**Comment by chrispi68** [comment]
Es läuft inzwischen seit 2 Tagen problemlos mit dem älteren Mosquitto unter Windows. Weil das Problem anscheinend nicht an RedMatic liegt, schließe ich hier.
