### ISSUE TITLE
Wettericons für RedMatic Dashboard hinzufügen

### ISSUE THREAD

**Issue by djiwondee** [rdmtc/RedMatic#220]
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/37173958/58908532-1e0ef000-8711-11e9-8e30-63e8ed86b718.png">

Es gibt ein in Node-red nutzbares sehr [umfangreiches Set von über 200 Wettersymbolen](https://erikflowers.github.io/weather-icons/), die insbesondere im Zusammenhang mit dem OpenWeather Nodes genutzt werden können. Ein Beispiel, wie es aktuell auf Basis Node-Red auf einem Raspi implementiert ist, ist [hier dargestellt](https://gist.github.com/djiwondee/b5b7d5da14d24e71de447e6aa290937e).

<img width="562" alt="image" src="https://user-images.githubusercontent.com/37173958/58908934-1c91f780-8712-11e9-84ab-9a5cab1816aa.png">

Die Ressourcen für die Wettersymbole sind verfügbar einschl. einer entsprechenden [Anleitung zur Implementierung](https://github.com/Paul-Reed/weather-icons) in Node-Red. Da ja RedMatic als add-on für Homatic implementiert ist, ist es sicher nicht der richtige Weg ist, (wo auch immer) Modifikationen auf File-Ebene manuell durchzuführen. Gibt es daher einen _supporteten_ Weg für die manuelle Einbindung oder ist es ggf. sinnvoll, das Set in eines der nächsten Releases zu inkludieren.

**Comment by Hypnos3** [comment]
auf der Seite steht: "DO NOT USE - SEE [WEATHER-ICONS-LITE](https://github.com/Paul-Reed/weather-icons-lite) WHICH IS MERGED INTO NODE-RED CORE"

**Comment by djiwondee** [comment]
@Hypnos3: Nach meinem Verständnis ist das Package was ich meine nicht das **WEATHER-ICONS-LITE**. Es handelt sich bei dem **LITE** um [ein anderes Repository](https://github.com/Paul-Reed/weather-icons-lite).

**Comment by Hypnos3** [comment]
@djiwondee: Ich habe lediglich darauf hingewiesen, das in der von dir genannte "[Anleitung zur Implementierung](https://github.com/Paul-Reed/weather-icons)" der Autor [Paul-Reed](https://github.com/Paul-Reed) selbst geschrieben hat, das dieses nicht mehr verwendet werden sollte und stattdessen ein anderes Paket von ihm genommen werden soll. Bei diesem Paket wiederum steht, dass es bereits in node-red integriert ist.

Der Raspi hat nur begrenzte Ressourcen und es hat es bei Nutzern bereits Probleme gegeben, weil das RedMatic Paket zusammen mit anderen AddOns zu groß gewesen ist. Aus diesem Grunde wurden bereits Zusatzpakete in RedMatic ausgelagert.

Da die lite Version der Wetter Icons bereits in Node-Red integriert sind, was ist denn der konkrete Benefit davon das volle Paket noch zu integrieren?

Wäre es nicht einfacher diese Icons zu nehmen und das [Beispiel](https://gist.github.com/djiwondee/b5b7d5da14d24e71de447e6aa290937e) entsprechend anzupassen?

**Comment by djiwondee** [comment]
Hallo @hobbyquaker,

Danke für die Bearbeitung und die hilfreichen Tipps wie unter [node-red-contrib-weatherman](https://github.com/Sineos/node-red-contrib-weatherman/blob/master/README_DE.md). 

Damit das von mir gewünschte Feature läuft habe ich folgende Umsetzung gewählt:

**1) Einrichten des Verzeichnis und Kopieren der CSS-Resourcen**

```
/usr/local/sdcard/www/addons/red/static/
```

<img width="502" alt="image" src="https://user-images.githubusercontent.com/37173958/60265531-3d4f0680-98e6-11e9-89e5-bf2d9c825d50.png">

**2) Anpassen der der RedMatic Node-Red settings.json**

```
/usr/local/addons/redmatic/etc/settings.json
```
<img width="352" alt="image" src="https://user-images.githubusercontent.com/37173958/60265630-8010de80-98e6-11e9-8147-c6e3d6a22328.png">

**3) Neustart von RedMatic**

_(selbsterklärend)_

**4) In meinen Flow die Einstellungen für das UI-Template Widget anpassen**

<img width="873" alt="image" src="https://user-images.githubusercontent.com/37173958/60265799-e138b200-98e6-11e9-9c71-3cbfe171e538.png">

**5) Am Ergebnis freuen**

<img width="499" alt="image" src="https://user-images.githubusercontent.com/37173958/60265889-1fce6c80-98e7-11e9-9b90-01977a786f6e.png">

Auch die Sonnenauf- und -untergangssymbole sind nun verfügbar

<img width="303" alt="image" src="https://user-images.githubusercontent.com/37173958/60265975-560bec00-98e7-11e9-97b7-e089cff797d8.png">

________________

Aus meiner Sicht kann das Issue geschlossen werden, da "Problem" gelöst! Übernehme auch gerne einen Eintrags in Wiki, für den Fall, dass das gewünscht ist.

Mit Verweis auf die hilfreiche [Anmerkung](https://github.com/rdmtc/RedMatic/issues/220#issuecomment-498960563) von @Hypnos3: der node_red Flow-Editor verweist in seiner Infobox 

<img width="707" alt="image" src="https://user-images.githubusercontent.com/37173958/60266438-55c02080-98e8-11e9-91c7-2b224a41c513.png">

selbst auf die [in Node-Red out of-the-box verfügbaren](https://github.com/Paul-Reed/weather-icons-lite/blob/master/css_mappings.md) Wetter-Icons. Wie im Ursprung des Issues erwähnt, bringt diese Variante hier mehr mit. Wenn noch Sorge besteht, dass der Storage auf der CCU knapp wird: anders als [hier](https://github.com/Paul-Reed/weather-icons) beschrieben, kann man auf das _vollständige_ Clonen des git-Repositories verzichten und nur die hier dargestellten Files kopieren. Spart aber auch nur 380 KB.

**Comment by hobbyquaker** [comment]
@djiwondee Wiki: gerne!

**Comment by djiwondee** [comment]
@hobbyquaker Eintrag im [Wiki](https://github.com/rdmtc/RedMatic/wiki/Zusätzliche-Wettericons-für-UI-Dashboard-in-Redmatic-verfügbar-machen) erstellt.

**Comment by hobbyquaker** [comment]
Top, vielen Dank!
