### ISSUE TITLE
KeyMatic mit Homekit entriegeln öffnet Haustüre FEHLER!

### ISSUE THREAD

**Issue by Macem79** [rdmtc/RedMatic#221]
Hallo, wie bereits in einem anderen Issue erwähnt, komme ich von der Homebridge von @thkl.

Nun benutze ich Redmatic für Homekit. Es ist einfach super.

Soeben habe ich meine Keymatic hinzugefügt, und habe Siri gesagt "Entriegle meine Haustüre" Das hat sie auch getan, aber sie hat sie nicht nur entriegelt, sondern auch gleich geöffnet. Das ist ein Fehler. Eigentlich hätte die Keymatic nur (wie ich es auch Siri gesagt habe) entriegelt werden sollen, und nicht komplett geöffnet.

Als ich noch die Homebridge verwendet habe, gab es 3 möglichkeiten:

Entriegle die Haustüre = Die Keymatic wurde entriegelt
Verriegle die Haustüre = Die Keymatic wird verriegelt (ist bei Redmatic auch so)
Öffne die Haustüre = Die Keymatic hat entriegelt und dann die Türe geöffnet bzw. nur die Türe geöffnet wenn schon entriegelt war (gibt es bei Redmatic nicht)

In der WebUI gibt es ja für die Keymatic auch 3 Optionen:

Zu (verriegeln)
Auf (entriegeln)
Tür öffnen (entriegeln und öffnen bzw. nur öffnen wenn schon entriegelt war)

Und diese 3 Optionen gab bzw. gibt es auch bei der Homebridge von @thkl 

@hobbyquaker kannst du dies bitte anpassen bzw. erweitern, denn es ist echt blöd wenn man zuhause ist und man die Haustüre entriegeln will, sie aber gleichzeitig auch geöffnet wird und man hier mit geöffneter Wohnungstüre sitzt ^^ Vielen Dank!

**Comment by LevelOne2k** [comment]
Moin! Das ist mir auch schon aufgefallen und bitte hier um Anpassung @hobbyquaker . Danke sehr 👍 

PS: Auch ich komme von der "alten" Homebridge.

**Comment by hobbyquaker** [comment]
@Macem79 kannst Du mit dem von @LevelOne2k genannten Weg leben - können wir diesen Issue schließen?

**Comment by Macem79** [comment]
@hobbyquaker Ja, auf jeden Fall, danke.

Das einzige was mit bei der Steuerung von HomeKit und KeyMatic aufgefallen ist, ist, dass es sehr oft "Kommunikationsstörungen" auf der CCU gibt wenn ich die KeyMatic über HomeKit steuere. 

in 10/10 Fällen kommt es mindestens 8 mal vor, dass es Kommunikationsstörungen gibt wenn ich die KeyMatic über Siri steuere, insbesondere dann, wenn die KeyMatic mit in einer Szene drin steckt. Das hatte ich damals bei der Homebridge nicht.

**Comment by hobbyquaker** [comment]
Das Problem mit den Szenen ist auch schon an anderen Stellen aufgetreten, da bin ich noch etwas ratlos. Würde Dich bitten dazu einen neuen Issue im [RedMatic-HomeKit Issue Tracker](https://github.com/rdmtc/RedMatic-Homekit/issues) aufzumachen und da ein Log auf Debug Level anzuhängen in dem so eine fehlgeschlagene Szenensteuerung enthalten ist.

**Comment by thoduh** [comment]
Bei meiner KeyMatic (HM-Sec-Key-O) gibt es die Auswahl von "OpenUnLock" gar nicht?
Gibt es da einen Trick das sichtbar zu machen?

Jetzt wird meine Türe nämlich immer komplett geöffnet statt nur entriegelt :-(
