### ISSUE TITLE
Alexa-Remote-2 issue with new Proxy setup

### ISSUE THREAD

**Issue by ThomasPoett** [rdmtc/RedMatic#227]
https://github.com/586837r/node-red-contrib-alexa-remote2/issues/20
I have created this issue with the new proxy possibility storing the Alexa cookie.
Nevertheless, we found issue, which are mostly related to RapsMatic act differently then other PI distribution. If you could get in touch with : https://github.com/586837r and figure out what this issue is it would be great. Sure I help testing…

**Comment by hobbyquaker** [comment]
I had a quick flip throught that issue 
The thing about trying to write on readonly paths: this is something the author of these nodes should change, writeable is: `/tmp` (non persistent tmpfs/ramdisk), the user home dir `~` (resolves to `/usr/local/addons/redmatic/home` in RedMatics Env) and the path returned by `RED.settings.userDir` - in case of RedMatic this resolves to `/usr/local/addons/redmatic/var`. Common in the Node-RED world is the usage of RED.settings.userDir with a subfolder named similar to the Nodes. Or he could just make the path configurable with a reasonable default.

I have to admit I was to lazy to read all of the issue comments - but it seems there are also more/other issues? If yes: do they create any error message or other useful log output (perhaps it also makes sense to raise log level to "debug")? Did you make sure that the firewall of RaspberryMatic isn't the cause of the problem?

**Comment by ThomasPoett** [comment]
Update, with the actual release now, it is stable and works fine
