### ISSUE TITLE
Probleme mit RPC Event bei HMIP-BSM, HMIP-BROLL mit press short/press long

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/RedMatic#230]
Hallo hobbyquaker,

folgender Fall:

Ich möchte ein RPC-Event nutzen um das Drücken der Schalter vom z.B. HMIP-Broll, oder HMIP-BSM abzufangen. Aber das RPC-Event bleibt leer. Nun lege ich ein Programm auf der CCU an die dieses ebenfalls macht. Ich sage, Wenn Channel 1: oder Channel 2: dieser Aktoren bedient wird dann schreibe in eine Variable. Dann bediene ich den Schalter rauf und runter. Siehe da das Event auf der redmatic geht auf einmal auch. Dann lösche ich das Programm auf der CCU und boote neu. Es geht immer noch...... Aber alle anderen HMIP-Broll, oder HMIP-BSM gehen immer noch nicht. 

Was mache ich denn falsch, oder ist das ein Bug?
Gruß Thomas

![grafik](https://user-images.githubusercontent.com/44590735/60398056-3e856b00-9b54-11e9-926f-98173deaeba1.png)

**Comment by hobbyquaker** [comment]
Das ist höchstwahrscheinlich die "reportValueUsage Thematik".

Siehe https://github.com/rdmtc/RedMatic/wiki/Faq#Tastendruck-erzeugt-keine-Events

**Comment by ThomasLoeffel** [comment]
Hallo hobbyquaker,

jop denke genau das ist das Problem. Hätte auch nachlesen können, sorry :-).
Danke für die schnelle Antwort!

Gruß Thomas
