### ISSUE TITLE
Ein Problem mit dem DutyCycle

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/RedMatic#231]
Hallo hobbyquaker,

ich habe mich mal dran gemacht Teile der CCU Programme auf die redmatic zu bringen.
Nun ist mir aufgefallen das nur durch das deploy mein DC kontinuierlich steigt.

Meine Flows habe ich mal abgebildet. Warum steigt der DC kontinuierlich an?
Lieben Gruß Thomas

Ich habe derzeit nur dieses realisiert:
![grafik](https://user-images.githubusercontent.com/44590735/60402787-701e2680-9b94-11e9-972a-54925a9e4d0d.png)

Beispiel eines HMIP--Broll:
![grafik](https://user-images.githubusercontent.com/44590735/60402801-9d6ad480-9b94-11e9-9ef6-00b942d12bce.png)

Zweiter Flow:
![grafik](https://user-images.githubusercontent.com/44590735/60402813-cb501900-9b94-11e9-9105-165f2e360163.png)

Dritter Flow:
![grafik](https://user-images.githubusercontent.com/44590735/60402818-da36cb80-9b94-11e9-82f7-8705ac193a5a.png)

**Comment by hobbyquaker** [comment]
Am besten mal Log Level auf Debug stellen und auf der Console mit `tail -F /var/log/messages | grep "rpc >"` verfolgen was für RPC Calls da beim Deploy gemacht werden. Häufige Ursache ist dass man Nodes einsetzt die beim Deploy eine oder mehrere Nachrichten erzeugen (z.B. Value oder RPC Event mit Checkbox "Emit Cached Values on Start" gesetzt) und diese dann im weiteren Verlauf der Flows das Senden eines Befehls an einen Aktor verursachen.

**Comment by ThomasLoeffel** [comment]
Hallo hobbyquaker,

danke für den Tipp. Meinst Du mit ssh auf das Tinkerboard gehen? LOG zum herunterladen finde ich nur dieses. Danke Thomas
........................................................
Jul  1 20:59:58 homematic-tinker daemon.info node-red[13908]: Flows starten
Jul  1 20:59:58 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] local connection on ccu >= v3.41 detected
Jul  1 20:59:59 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] paramsets loaded from /usr/local/addons/redmatic/var/paramsets.json
Jul  1 20:59:59 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] metadata loaded from /usr/local/addons/redmatic/var/ccu_localhost.json
Jul  1 20:59:59 homematic-tinker daemon.info node-red[13908]: SonosPollyTTS: ConfigNode:[object Object]
Jul  1 20:59:59 homematic-tinker daemon.info node-red[13908]: Flows gestartet
Jul  1 20:59:59 homematic-tinker daemon.info node-red[13908]: [mqtt-broker:Synology Mosquito] Verbindung zum Broker Tinker_Master@mqtt://192.168.180.43:1883 hergestellt.
Jul  1 21:00:01 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] Interfaces: ReGaHSS, BidCos-RF, HmIP-RF, VirtualDevices
Jul  1 21:00:01 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] ReGaHSS binrpc port 31999 connected
Jul  1 21:00:01 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] init BidCos-RF binrpc://127.0.0.1:2047 nr_AKHydZ_BidCos-RF
Jul  1 21:00:01 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] init HmIP-RF http://127.0.0.1:2048 nr_D24DjW_HmIP-RF
Jul  1 21:00:01 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] init VirtualDevices http://127.0.0.1:2048 nr_D24DjW_VirtualDevices
Jul  1 21:00:01 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] binrpc server listening on binrpc://127.0.0.1:2047
Jul  1 21:00:01 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] xmlrpc server listening on http://127.0.0.1:2048
Jul  1 21:00:01 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] BidCos-RF binrpc port 32001 connected
Jul  1 21:00:01 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] VirtualDevices http port 39292 connected
Jul  1 21:00:01 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] metadata saved to /usr/local/addons/redmatic/var/ccu_localhost.json
Jul  1 21:00:01 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] HmIP-RF http port 32010 connected
Jul  1 21:00:03 homematic-tinker daemon.info node-red[13908]: [ccu-connection:localhost] metadata saved to /usr/local/addons/redmatic/var/ccu_localhost.json
..................................................................

**Comment by Hypnos3** [comment]
Ich würde für die Rollladen-Nodes einen Trigger von 10 Minuten empfehlen.

**Comment by ThomasLoeffel** [comment]
Hallo hypnos,

habe ich umgesetzt. Danke Dir.
Gruß Thomas

**Comment by hobbyquaker** [comment]
@ThomasLoeffel besteht das DutyCycle Problem bei Dir noch oder können wir hier schließen?

**Comment by ThomasLoeffel** [comment]
Hallo hobbyquaker,

es ist besser geworden. Es liegt aber an meinen Flows wie es scheint. 
Gruß und Danke Thomas
