### ISSUE TITLE
CuxD Geräte

### ISSUE THREAD

**Issue by DennisXK** [rdmtc/RedMatic#232]
Hey, habe die Redmatic und HomeKit addon erfolgreich installiert bekommen. Super Sache!!!

Ich vermisse nur meine Cuxd Geräte....ist es möglich diese aus in homekit zu integrieren?

**Comment by Sineos** [comment]
Findest du unter den "Configuration Nodes":

![image](https://user-images.githubusercontent.com/4459312/60687330-360f9600-9eae-11e9-8d14-406fc66970f8.png)

**Comment by DennisXK** [comment]
Danke, hat geklappt! aber irgendwie nicht so wie ich mir das vorgestellt habe. Ich habe eine 3 Kanal Cuxd Wandtaster angelegt. Jedoch bekomme ich die 3 Taster nicht in der Homekit APP angezeigt sonder nur einen Schalter !

Des weitern habe ich testweise den Hacken bei CUxD wider entfernet, aktualisiert, Fertig und implementiert. Die Homekit App aus dem Arbeitsspeicher im iPhone gelöscht und neu gestartet, jedoch werden die CUxD Geräte noch angezeigt.

**Comment by sslneve** [comment]
Hi,

ich habe in etwa das selbe Problem. Es werden bei mir zwar 2 CuxD Geräte angezeigt, dies ist jedoch ein Sensor (Wetter) und das Timer Gerät. Ich habe allerdings eine Menge 433MHz Funksteckdosen und Schalter/Taster (über einen CUL433) per CuxD 16-Kanal Universalsteuerung. Diese werden alle nicht angezeigt. Liegt es vielleicht daran, dass nur Sensoren und Aktoren angezeigt werden, nicht aber CuxD Schalter/Taster? Die Funksteckdosen können nur über die Universalsteuerung eingebunden werden, die formell weder Aktor noch Sensor ist...

**Comment by DennisXK** [comment]
Bei mir hat es funktioniert nachdem ich die redmatic neu gestartet habe !

**Comment by sslneve** [comment]
Ich sehe gerade, dass mein Komentar eher zum Homekit Addon gehört, da ich mich auf die homematic Node von Homekit beziehe...

**Comment by hobbyquaker** [comment]
D.h. wir können diesen Issue schließen?
