### ISSUE TITLE
Probleme mit RPC Event nach CCU Neustart

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/RedMatic#233]
Hallo hobbyquaker,

folgendes ist mir aufgefallen. Ich schreibe aus einem RPC Event die Infos in globale Variablen.
Nach einem CCU Neustart führt er aber diese RPC Events nicht aus. Ich warte nun schon 40min. Wenn ich allerdings Redmatic "neustart" machen würde wäre alles wieder ok. Oder muss ich diese Events irgendwie an triggern?

Gruß Thomas

![grafik](https://user-images.githubusercontent.com/44590735/60688307-aae5ce80-9eb4-11e9-8b8d-03067824bd25.png)

![grafik](https://user-images.githubusercontent.com/44590735/60688374-f7310e80-9eb4-11e9-97f1-70f9bce870c2.png)

**Comment by ThomasLoeffel** [comment]
Hallo hobbyquaker,

ich habe es heute noch einmal getestet. Wenn ich einen CCU / Raspberrymatic Neustart mache, wird irgendwie das RPC Event nicht ausgeführt. Ich habe 5 Stunden gewartet. Erst nach einem Deploy oder Redmatic Neustart startet das RPC Event und somit werden meine "global-Wert" befüllt. Kannst Du das nachstellen, oder liegt das an mir?

Gruß Thomas

**Comment by Maxvil30** [comment]
Hallo Thomas,
ich habe sowas ähnliches auch mal gehabt. Ich glaube ich habe in meinem Fall den Haken bei "Emit only changed values" raus genommen. Dann hat es bei mir funktioniert.

Gruß
Marcus
