### ISSUE TITLE
Dokumentation - Backup - Library

### ISSUE THREAD

**Issue by hklages** [rdmtc/RedMatic#234]
Auf der Seite für den manuellen Backup  ( ... wiki/Backup) fehlt meiner Ansicht nach das Verzeichnis lib (inklusive aller Unterverzeichniss), in dem alle nodes, functions, templates gespeichert werden können.

**Comment by hobbyquaker** [comment]
Manuell nachinstallierte Nodes und sonstige "Nutzdaten" sind alle in /var, in /lib ist nichts veränderliches gespeichert.

**Comment by hklages** [comment]
Ich meine "/usr/local/addons/redmatic/var/lib" - dort sind alle Elemente, die man mit Export Library speichert.

**Comment by hklages** [comment]
Meine *Vorschlag* für die Dokumentation des manuellen Backup ist: 

_Es sollten die folgenden Dateien und Verzeichnisse inklusive aller Unterverzeichnisse gesichert werden: 

- /usr/local/addons/redmatic/etc/credentials.key
- /usr/local/addons/redmatic/etc/settings.json
- /usr/local/addons/redmatic/var aber ohne Verzeichniss node_modules_

Das entspricht der Empfehlung von 
[https://github.com/node-red/cookbook.nodered.org/wiki/How-to-backup-flows-and-related-configuration](url)
und damit sind auch die HomeKit, Alexa, Projekt (Github), ... Daten enthalten und natürlich auch meine Library Code Snippets, Notes aus  "/usr/local/addons/redmatic/var/lib".

Wenn du Deine Anleitung für context storage [https://github.com/rdmtc/RedMatic/wiki/Context-Storage](url) dahingehend änderst, dass nur von memory auf file umgestellt wird und nicht zusätzlich der Name geändert wird, werden die global Variablen auch mit gesichert. Ansonsten bei USB müsste man diese extra sicher.

**Comment by hobbyquaker** [comment]
Klingt gut. Du kannst das gerne im Wiki anpassen :)

**Comment by hklages** [comment]
Done.
