### ISSUE TITLE
RedMatic remote über reverse proxy nicht erreichbar

### ISSUE THREAD

**Issue by paranerd** [rdmtc/RedMatic#237]
Moin zusammen!

Ich versuche, remote auf RedMatic zuzugreifen. Dazu habe ich auf einem separaten Pi Nginx als Reverse Proxy mit folgender Konfiguration eingerichtet:

```
    server {
        listen 443 ssl;
        server_name nodered.<mydomain>;
        ssl_certificate      /etc/letsencrypt/live/<mydomain>/fullchain.pem;
        ssl_certificate_key  /etc/letsencrypt/live/<mydomain>/privkey.pem;

        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
                auth_basic "NodeRED";
                auth_basic_user_file /etc/nginx/.htpasswd;
                proxy_pass http://<RaspberryMatic-IP>:1880/addons/red/;
        }
    }
```

Mit einer ähnlichen Konfiguration (bis auf: proxy_pass http://<RaspberryMatic-IP>/addons/red/ui/;) komme ich problemlos auf das Dashboard, nur die Flows wollen mir nicht angezeigt werden.

Da es ebenfalls eine Freigabe für die RaspberryMatic gibt, habe ich den Zugriff auch über deren UI versucht. Hier wird mir zumindest noch der Login-Screen von RedMatic präsentiert, dann bleibe ich aber auf bis auf die NodeRED-Titlebar leeren Seite hängen und nichts passiert mehr.

Hat jemand eine Idee, was hier falsch läuft?

Viele Grüße.

**Comment by hobbyquaker** [comment]
> proxy_pass http://<RaspberryMatic-IP>:1880/addons/red/;

Du musst Port 80 anstatt 1880 nutzen. Außerdem wirst Du dem Nginx auch beibringen müssen dass er Websocket Verbindungen durchlässt, siehe https://gist.github.com/boneskull/d418b7c871d2248cfeba#file-proxy-L10 Zeile 10 und 11

**Comment by paranerd** [comment]
Wow, das war einfach^^
Danke für die schnelle Antwort :-).

Keep up the great work B-)!
