### ISSUE TITLE
Probleme mit der ccu-node signal für HM-OU-CFM-TW

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/RedMatic#238]
Hallo hobbyquaker,

ich habe einmal auf einen Eintrag im Forum reagiert.
Es geht um die ccu-signal node. Im besonderen die Volumeneinstellung über den Input.

Wenn man in den Einstellungen Volumen auf "msg.payload" stellt, geht es bei einem HMIP-MP3p aber nicht bei einem HM-OU-CFM-TW. Ich habe hierfür unten gezeigten "flow" verwendet. Beim HM-OU-CFM-TW habe ich auch festgestellt das hin und wieder sich der "msg.payload" verstellt (ohne mein Zutun).

Gruß Thomas

![grafik](https://user-images.githubusercontent.com/44590735/61412419-184c2300-a8e9-11e9-9787-a83bcf4aff19.png)

![grafik](https://user-images.githubusercontent.com/44590735/61412473-416cb380-a8e9-11e9-80f5-045733db0151.png)

**Comment by hobbyquaker** [comment]
Duplicate: https://github.com/rdmtc/node-red-contrib-ccu/issues/90
