### ISSUE TITLE
Export Env für Git

### ISSUE THREAD

**Issue by Sineos** [rdmtc/RedMatic#240]
Um auch mal flexibel ein addon via `npm -i git://...` installieren zu können, wären die Umgebungsvariablen für Git praktisch:

```
export PATH=/usr/local/addons/redmatic/bin:$PATH
export GIT_EXEC_PATH=/usr/local/addons/redmatic/libexec/git-core
```

**Comment by hobbyquaker** [comment]
Hmm, das ist im `.profile` schon drin: https://github.com/rdmtc/RedMatic/blob/master/addon_files/redmatic/home/.profile

Die .profile sollte sowieso gesourced werden bevor man das RedMatic npm nutzt, auch weil es sonst zu problemen mit dem `HOME` auf der ro-partition kommt. Siehe auch: https://github.com/rdmtc/RedMatic/wiki/Node-Installation#installation-via-npm-auf-der-kommandozeile

**Comment by Sineos** [comment]
Alles gut, aus alter Gewohnheit an der Shell angemeldet und dann halt "zu Fuß" gemacht. RTFM hätte geholfen.
