### ISSUE TITLE
/usr/local/etc/monit-redmatic.cfg link wird nicht entfernt beim Deinstallieren

### ISSUE THREAD

**Issue by jens-maus** [rdmtc/RedMatic#241]
Beim Deinstallieren des Addons wird anscheinend der Link `/usr/local/etc/monit-redmatic.cfg` nicht entfernt. Es kommt daher nach dem deinstallieren beim ausführen von `monit` zu folgender Fehlermeldung:

```
# monit status
/etc/monitrc:399: Cannot include file '/usr/local/etc/monit-redmatic.cfg' -- No such file or directory '/usr/local/etc/monit*.cfg'
```

**Comment by hobbyquaker** [comment]
thx!

**Comment by mbhomie007** [comment]
@hobbyquaker @jens-maus 
Das Problem entsteht auch noch mit der aktuellen Version 7.1.3.

Siehe auch: https://homematic-forum.de/forum/viewtopic.php?f=77&t=65006

`Jan 27 18:27:37 Homematic-CCU daemon.info : starting pid 3258, tty '/dev/null': '/usr/bin/monit -Ic /etc/monitrc'
Jan 27 19:27:37 Homematic-CCU user.err monit: /etc/monitrc:435: Cannot include file '/usr/local/etc/monit-redmatic.cfg' -- No such file or directory '/usr/local/etc/monit*.cfg'
Jan 27 18:27:37 Homematic-CCU daemon.info : process '/usr/bin/monit -Ic /etc/monitrc' (pid 3258) exited. Scheduling for restart.
Jan 27 18:27:38 Homematic-CCU daemon.info : starting pid 3280, tty '/dev/null': '/usr/bin/monit -Ic /etc/monitrc'
Jan 27 19:27:38 Homematic-CCU user.err monit: /etc/monitrc:435: Cannot include file '/usr/local/etc/monit-redmatic.cfg' -- No such file or directory '/usr/local/etc/monit*.cfg'
Jan 27 18:27:38 Homematic-CCU daemon.info : process '/usr/bin/monit -Ic /etc/monitrc' (pid 3280) exited. Scheduling for restart.
Jan 27 18:27:39 Homematic-CCU daemon.info : starting pid 3290, tty '/dev/null': '/usr/bin/monit -Ic /etc/monitrc'
Jan 27 19:27:39 Homematic-CCU user.err monit: /etc/monitrc:435: Cannot include file '/usr/local/etc/monit-redmatic.cfg' -- No such file or directory '/usr/local/etc/monit*.cfg'
Jan 27 18:27:39 Homematic-CCU daemon.info : process '/usr/bin/monit -Ic /etc/monitrc' (pid 3290) exited. Scheduling for restart.
Jan 27 18:27:40 Homematic-CCU daemon.info : starting pid 3291, tty '/dev/null': '/usr/bin/monit -Ic /etc/monitrc'
Jan 27 19:27:40 Homematic-CCU user.err monit: /etc/monitrc:435: Cannot include file '/usr/local/etc/monit-redmatic.cfg' -- No such file or directory '/usr/local/etc/monit*.cfg'
Jan 27 18:27:40 Homematic-CCU daemon.info : process '/usr/bin/monit -Ic /etc/monitrc' (pid 3291) exited. Scheduling for restart.
Jan 27 18:27:41 Homematic-CCU daemon.info : starting pid 3293, tty '/dev/null': '/usr/bin/monit -Ic /etc/monitrc'
Jan 27 19:27:41 Homematic-CCU user.err monit: /etc/monitrc:435: Cannot include file '/usr/local/etc/monit-redmatic.cfg' -- No such file or directory '/usr/local/etc/monit*.cfg'
Jan 27 18:27:41 Homematic-CCU daemon.info : process '/usr/bin/monit -Ic /etc/monitrc' (pid 3293) exited. Scheduling for restart.`
