### ISSUE TITLE
node-red-contrib-zigbee Exception führt zu Node-RED Crash

### ISSUE THREAD

**Issue by Matten-Matten** [rdmtc/RedMatic#254]
Redmatic V5.0.0 stoppt immer wieder

{
   "ccu": {
      "VERSION": "3.47.18.20190918",
      "PRODUCT": "raspmatic_rpi4",
      "PLATFORM": "rpi4"
   },
   "redmatic": "5.0.0",
   "nodejs": "10.16.3",
   "ain2": "3.0.0",
   "node-red": "1.0.1",
   "node-red-contrib-theme-midnight-red": "1.0.2",
   "node-red-contrib-zigbee": "0.9.8",
   "npm": "6.11.3",
   "node-red-contrib-alexa-remote2": "2.3.5",
   "node-red-contrib-ccu": "3.0.0",
   "node-red-contrib-combine": "1.8.1",
   "node-red-contrib-counter": "0.1.5",
   "node-red-contrib-hyperion": "0.1.3",
   "node-red-contrib-milight-2": "1.0.8",
   "node-red-contrib-pushover": "0.1.10",
   "node-red-contrib-samsung-tv": "0.2.0",
   "node-red-contrib-samsungTV": "0.1.1",
   "node-red-contrib-sun-position": "0.4.10",
   "node-red-dashboard": "2.17.0",
   "node-red-node-email": "1.7.1",
   "node-red-node-openweathermap": "0.2.1",
   "node-red-node-rbe": "0.2.5",
   "node-red-node-sentiment": "0.1.4",
   "node-red-node-tail": "0.0.3",
   "redmatic-led": "1.1.0",
   "redmatic-webapp": "0.3.1"
}

Gruß
Matten Matten

**Comment by str3000** [comment]
Hatte das gleiche Problem. 
Habe einmal ein falschen Homekit node und einen nichtverwendeten zigbee entfernt und seit dem kein reboot mehr. Hier wird eine exeption nicht abgefangen.
Traue mich grade nicht nodes in homekit einzubauen.

**Comment by hobbyquaker** [comment]
Logs?

**Comment by Matten-Matten** [comment]
ja, wohin sollich das schicken? Adresse?

**Comment by Matten-Matten** [comment]
```
Oct  6 10:45:45 ccu3-webui daemon.err node-red: 6 Oct 10:45:45 - [red] Uncaught Exception:
Oct  6 10:45:45 ccu3-webui daemon.err node-red: 6 Oct 10:45:45 - TypeError: Cannot read property 'getEntries' of null
Oct  6 10:45:45 ccu3-webui daemon.err node-red:     at Function.loadFromDatabaseIfNecessary (/usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:133:55)
Oct  6 10:45:45 ccu3-webui daemon.err node-red:     at Function.all (/usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/node_modules/zigbee-herdsman/dist/controller/model/device.js:153:16)
Oct  6 10:45:45 ccu3-webui daemon.err node-red:     at Controller.getDevices (/usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/node_modules/zigbee-herdsman/dist/controller/controller.js:197:31)
Oct  6 10:45:45 ccu3-webui daemon.err node-red:     at ZigbeeShepherd.checkOverdue (/usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/nodes/shepherd.js:873:27)
Oct  6 10:45:45 ccu3-webui daemon.err node-red:     at Timeout.ZigbeeShepherd.setInterval [as _onTimeout] (/usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/nodes/shepherd.js:480:22)
Oct  6 10:45:45 ccu3-webui daemon.err node-red:     at ontimeout (timers.js:436:11)
Oct  6 10:45:45 ccu3-webui daemon.err node-red:     at tryOnTimeout (timers.js:300:5)
Oct  6 10:45:45 ccu3-webui daemon.err node-red:     at listOnTimeout (timers.js:263:5)
Oct  6 10:45:45 ccu3-webui daemon.err node-red:     at Timer.processTimers (timers.js:223:10)
Oct  6 10:45:45 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 1
```

**Comment by Ixuser-1** [comment]
Kann mich da str3000 anschliessen. Ich hatte es nach dem Wechsel auf Node-Red zuerst auch, dass Node-Red immer wieder nach kurzer Zeit beendet wurde. Das lag hier auch an Nodes aus der vorherigen 0.7.2 von node-red-contrib-zigbee, die nicht mehr zu 0.9.8 passten.

**Comment by hobbyquaker** [comment]
Da scheint irgendein Problem mit der Zigbee Device Datenbank zu sein. Sind die Zigbee Geräte im Herdsman Node / Device Tab noch vorhanden? Funktionieren Sie noch (bis zum Absturz)?
Hilfreich wäre hier mal ein Blick auf den Inhalt des Ordners `/usr/local/addons/redmatic/var/zigbee`, am besten per Mail an hobbyquaker@gmail.com

**Comment by Ixuser-1** [comment]
Nach Löschen der Device-Node aus 0.7.2 und Anlegen der Controller-Node aus 0.9.8 lief es dann wieder bei mir, auch mit der alten Config-Node.

**Comment by Matten-Matten** [comment]
Hallo hobbyquaker kurze Rückinfo
ich hab das Device Node entfernt wie beschrieben. und jetzt läuft Node red auch wieder 
Gruß Matten
