### ISSUE TITLE
Verbindung zum Server verloren

### ISSUE THREAD

**Issue by henneonrails** [rdmtc/RedMatic#256]
die log Datei zeigt für meine Begriffe keine Auffälligkeiten, aber arbeiten ist nicht möglich da eine Fehlermeldung stört. Das ist erst seit dem update auf 5.0 so.

![Bildschirmfoto 2019-10-07 um 18 38 31](https://user-images.githubusercontent.com/123651/66330921-adcbe180-e931-11e9-9a39-7833d4c6eea3.png)
[redmatic.2019-10-07T16_34_44.367Z.log](https://github.com/rdmtc/RedMatic/files/3698525/redmatic.2019-10-07T16_34_44.367Z.log)

**Comment by Sineos** [comment]
Das sieht so aus als wäre NR gar nicht gestartet.
 
Homematic WebIF --> Einstellungen --> Zusatzsoftware --> Redmatic:
![grafik](https://user-images.githubusercontent.com/4459312/66332091-3481be00-e934-11e9-8091-5e7a2dda8ef1.png)

Starten oder Neustart

**Comment by henneonrails** [comment]
Danke, habe ich natürlich schon mehrfach gemacht. Auch die CCU3 habe ich neu gestartet.

Viele Grüße

**Comment by Sineos** [comment]
Wird Node-Red in meinem Screenshot als "running" (grüne Schrift) angezeigt?

Gleiche Seite --> Debug --> Log herunterladen und hier posten

**Comment by Hypnos3** [comment]
Ich denke die Meldung kommt generell wenn keine Webservice-Verbindung besteht.

**Comment by henneonrails** [comment]
> Wird Node-Red in meinem Screenshot als "running" (grüne Schrift) angezeigt?
> 
> Gleiche Seite --> Debug --> Log herunterladen und hier posten

@Sineos Log Datei hängt im Eingangspost schon dran. Ja der Server wird als Grün Running angezeigt.

**Comment by henneonrails** [comment]
habe grad meinen Mac auf Catalina geupdated und der Fehler ist weg??

**Comment by herzsven** [comment]
Hallo, ich habe das gleiche Problem. Ich bekomme den Fernzugriff über die Cloudmatic nicht hin.
Es kommt beim Starten von Node-Red die Meldung "Verbindung zum Server verloren,..."

Hier die Log-Datei:
[redmatic.2021-01-29T22_06_38.573Z.log](https://github.com/rdmtc/RedMatic/files/5896544/redmatic.2021-01-29T22_06_38.573Z.log)

Kann mir jemand weiterhelfen? Eventuell passen irgendwelche Einstellungen an der CCU3 nicht?

Danke

**Comment by johannesscherbaum** [comment]
Hallo, habe soeben dasselbe Problem. RedMatic läuft auf der CCU3. Habe schon sämtliche EInstellungen verändert. Ohne Erfolg.
Anbei mein Log:
[redmatic.2022-11-18T10_41_17.147Z.log](https://github.com/rdmtc/RedMatic/files/10040536/redmatic.2022-11-18T10_41_17.147Z.log)

Kann irgendjemand helfen? Danke im Voraus.

**Comment by johannesscherbaum** [comment]
Nachtrag: Im Safari klappt alles. Chrome macht die Probleme.
