### ISSUE TITLE
Keine Anzeige und Änderung der Flows in Redmatic möglich

### ISSUE THREAD

**Issue by r100gs** [rdmtc/RedMatic#257]
Hallo zusammen,

ich habe einen neuen Node für hass (homeassistant) installiert, jetzt kann ich leider meine flows nicht mehr sehen. Die Flows funktionieren aber nach wie vor.
Irgendeine Idee?
Ich habe bereits neugestartet. Auf einer neuen SD-Karte rasperrymatic neu installiert und ein backup eingespielt. Bringt nichts. Leider habe ich (deppert halt) kein Backup vor Installation des homeassistant nodes gemacht.
Gruß,
Stefan
So sieht es im Browser aus, weiter geht es nicht:

![2019-10-11 08 16 28 192 168 88 86 daa3619e24b7](https://user-images.githubusercontent.com/12609988/66628636-aa6d7a00-ebff-11e9-9da2-8a6b626f86cc.png)

**Comment by Hypnos3** [comment]
Browser Cache gelöscht?
Anderen Browser ausprobiert?

Ich denke zwar nicht das es an der Node für homeassistant liegt, aber alternativ kann man dann noch probieren Node-Red im SaveMode zu starten und dort versuchen die Node für homeassistant zu entfernen:
![image](https://user-images.githubusercontent.com/12692680/66679260-1c7ca800-ec6e-11e9-9ce7-41ab01005037.png)

**Comment by Hypnos3** [comment]
[hier](https://discourse.nodered.org/t/node-red-does-not-load-interface/16599/6) wird genau das selbe Problem diskutiert und auch eine Lösung.

Eventuell sind 2 homeassistant Nodes installiert, welche sich in die Quere kommen. Über den Safe Mode müsste sich eine deinstallieren lassen.

**Comment by r100gs** [comment]
ok, vielen Dank. Ich habe jetzt nodeRed im abgesicherten Modus gestartet und erst mal die Nodes von homeassistant deaktiviert. Jetzt läuft auch alles im normalen Modus wieder. 
Vielen Dank für die Hilfe,
Stefan
