### ISSUE TITLE
Zigbee converter funktioniert nicht mehr nach Update auf RM 5.0.2

### ISSUE THREAD

**Issue by spiu16** [rdmtc/RedMatic#258]
Hallo,
nach Update auf RedMatic 5.0.2 funktioniert leider der zigbee converter node nicht mehr wie vorher. Ich habe einen OSRAM Smart+ plug, welchen ich über HomeKit steuern möchte.
Leider reagiert der OSRAM Plug nicht mehr auf die Befehle, die ich über HomeKit auslöse (ON/OFF). Über den Debug-Node bekomme ich folgende Fehlermeldung:
`"TypeError: Cannot read property 'match' of undefined"`
Mit RM 4.7.1 hat das noch einwandfrei funktioniert.

Meine Nodes:
`[{"id":"7a216f6b.b515a","type":"zigbee-converter","z":"c2e54096.b7b51","shepherd":"9c891896.d6b5f8","name":"OSRAM Plug4","topic":"zigbee/${ieeeAddr}","settopic":"zigbee/${ieeeAddr}/set","device":"0x7cb03eaa0a029a0b","attribute":"","payload":"json","x":680,"y":2020,"wires":[["9cdda4fd.77e7c8","2aaef788.aa9278"]]},{"id":"82700588.b2c4f8","type":"redmatic-homekit-switch","z":"c2e54096.b7b51","bridgeConfig":"5d4337f8.5a4f4","name":"Steckdose4","x":670,"y":2160,"wires":[["d2e254c6.bc65a8"]]},{"id":"33d5ad97.d5a142","type":"change","z":"c2e54096.b7b51","name":"on","rules":[{"t":"set","p":"payload","pt":"msg","to":"on","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"zigbee/$OSRAM Plug4/set","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":510,"y":2000,"wires":[["7a216f6b.b515a"]]},{"id":"d2e254c6.bc65a8","type":"switch","z":"c2e54096.b7b51","name":"On/Off","property":"payload","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":370,"y":2020,"wires":[["33d5ad97.d5a142"],["30b5e3a3.d41ecc"]]},{"id":"30b5e3a3.d41ecc","type":"change","z":"c2e54096.b7b51","name":"off","rules":[{"t":"set","p":"payload","pt":"msg","to":"off","tot":"str"},{"t":"set","p":"topic","pt":"msg","to":"zigbee/$OSRAM Plug4/set","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":510,"y":2040,"wires":[["7a216f6b.b515a"]]},{"id":"9cdda4fd.77e7c8","type":"switch","z":"c2e54096.b7b51","name":"On/Off","property":"payload.state","propertyType":"msg","rules":[{"t":"eq","v":"ON","vt":"str"},{"t":"eq","v":"OFF","vt":"str"}],"checkall":"true","repair":false,"outputs":2,"x":370,"y":2160,"wires":[["9182be7c.43dba"],["8d464500.a56bc8"]]},{"id":"9182be7c.43dba","type":"change","z":"c2e54096.b7b51","name":"on","rules":[{"t":"set","p":"payload","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":510,"y":2140,"wires":[["82700588.b2c4f8"]]},{"id":"8d464500.a56bc8","type":"change","z":"c2e54096.b7b51","name":"off","rules":[{"t":"set","p":"payload","pt":"msg","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":510,"y":2180,"wires":[["82700588.b2c4f8"]]},{"id":"9c891896.d6b5f8","type":"zigbee-shepherd","z":"","name":"zigbee shepherd","path":"/dev/ttyACM0","baudRate":"115200","rtscts":true,"channelList":[11],"led":"disabled"},{"id":"5d4337f8.5a4f4","type":"redmatic-homekit-bridge","z":"","name":"RedMatic Bridge","username":"XX:XX:XX:XX:XX:XX","pincode":"XXX-XX-XXX","port":"51826"}]`

Kann mir jemand helfen?

Danke schon mal vorab!

**Comment by Matten-Matten** [comment]
Hast du hier schon Mal geschaut?

https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/42

**Comment by Matten-Matten** [comment]
Wenn du von der redmatic 4er Version kommst musst du den zigbee converter node löschen dann das 5er  Update installieren. Und den zigbee converter node wieder erstellen.
![Screenshot_20191016_075402](https://user-images.githubusercontent.com/32074970/66891767-3dd0f180-efea-11e9-867d-6e14f645aa5b.jpg)
