### ISSUE TITLE
Link zu Node-Hilfe Herdsman Controller funktioniert nicht

### ISSUE THREAD

**Issue by spiu16** [rdmtc/RedMatic#264]
Hallo,

der Link in der Node-Hilfe vom Herdsman Controller Node funktioniert leider nicht:

![image](https://user-images.githubusercontent.com/45998371/67428080-bed94b80-f5dd-11e9-8867-06a7d2bcac39.png)

Der korrekte Link wäre wohl dieser hier:
https://github.com/Koenkk/zigbee-herdsman/blob/master/docs/api/classes/_controller_controller_.controller.md

@hobbyquaker kannst Du den austauschen?

**Comment by hobbyquaker** [comment]
Ist schon gefixt in der aktuellen Version :)
