### ISSUE TITLE
Not used Notes can´t be delete

### ISSUE THREAD

**Issue by Blackei** [rdmtc/RedMatic#268]
Hi,
when you want to delte a not used Note it is still in Work and you can not delete them

**Comment by hobbyquaker** [comment]
please describe the issue in more detail, I don't understand what you mean.

**Comment by Blackei** [comment]
Eben i Install the Alexa without Cloud Skill, and i don't use Them i can Not deinstall then.

**Comment by hobbyquaker** [comment]
I still don't get it. You mean the uninstall via the Node-RED Palette Manager isn't working? Please deliver exact steps to reproduce as well as log files on debug level (https://github.com/rdmtc/RedMatic/wiki/Loglevel).
ps.: im RedMatic Issue Tracker hab ich auch nichts gegen Deutsch wenn Dir das lieber ist.
