### ISSUE TITLE
keine SysVar gefunden

### ISSUE THREAD

**Issue by MathiasJZ** [rdmtc/RedMatic#27]
Hallo, Sebastian,
nun zum nächsten Problem:
Ich wollte mich spasseshalber mal versuchen.
Aber Redmatic findet keine Systemvariablen.
Stattdessen bekomme ich laufend folgende Meldung:
"rega getVariables SyntaxError: Unexpected number in JSON at position 6468"
Gruß,
Mathias

**Comment by hobbyquaker** [comment]
Könntest Du mal dieses Rega-Script https://raw.githubusercontent.com/hobbyquaker/homematic-rega/master/scripts/variables.rega ausführen und die Ausgabe davon zeigen? Vielleicht mit dem Script-Executor von Anli oder dem HQ-WebUI, müsste aber glaube ich auch unter "Script Testen" im normalen WebUI möglich sein. Irgendwas scheint da leider nicht richtig escaped zu werden...

**Comment by MathiasJZ** [comment]
Hier die Ausgabe:
[{"id": 40, "name": "Alarmmeldungen", "val": 0, "min": 0, "max": 65000, "unit": "", "type": "number", "enum": ""},
{"id": 41, "name": "Servicemeldungen", "val": 1, "min": 0, "max": 65000, "unit": "", "type": "number", "enum": ""},
{"id": 3328, "name": "Alarm", "val": false,"ts":"1970-01-01 01:00:00","min":null,"max":null,"unit":"", "type": "boolean", "enum": "nicht ausgelöst;ausgelöst"},
{"id": 3399, "name": "Alarmanlage", "val": 2,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "number", "enum": "extern scharf;intern scharf;unscharf"},
{"id": 3257, "name": "Alarmzone 1", "val": false,"ts":"1970-01-01 01:00:00","min":null,"max":null,"unit":"", "type": "boolean", "enum": "nicht ausgelöst;ausgelöst"},
{"id": 2296, "name": "Anwesenheit_Familie", "val": false,"ts":"2018-07-11 17:33:26","min":null,"max":null,"unit":"", "type": "boolean", "enum": "abwesend;anwesend"},
{"id": 1687, "name": "Anwesenheit_Mathias", "val": true,"ts":"2018-07-11 17:33:27","min":null,"max":null,"unit":"", "type": "boolean", "enum": "abwesend;anwesend"},
{"id": 1686, "name": "Anwesenheit_Mieter", "val": true,"ts":"2018-07-11 17:33:27","min":null,"max":null,"unit":"", "type": "boolean", "enum": "abwesend;anwesend"},
{"id": 2412, "name": "Anwesenheit_neu", "val": true,"ts":"2018-07-11 17:33:27","min":null,"max":null,"unit":"", "type": "boolean", "enum": "abwesend;anwesend"},
{"id": 59780, "name": "Arbeitstag_heute", "val": false,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "boolean", "enum": "Urlaub;Arbeit"},
{"id": 59781, "name": "Arbeitstag_morgen", "val": false,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "boolean", "enum": "Urlaub;Arbeit"},
{"id": 3704, "name": "Betriebszeit Raspberry", "val": "0%20Tage%2001%20Std%2022%20Min","ts":"2018-07-11 17:30:01","min":null,"max":null,"unit":"", "type": "string", "enum": ""},
{"id": 2340, "name": "Bewegungsmelder_Eingang", "val": false,"ts":"2018-07-11 17:12:40","min":null,"max":null,"unit":"", "type": "boolean", "enum": "keine Bewegung;Bewegung erkannt"},
{"id": 3176, "name": "Bewegungsmelder_Wohnzimmer", "val": true,"ts":"2018-07-11 17:29:12","min":null,"max":null,"unit":"", "type": "boolean", "enum": "keine Bewegung;Bewegung erkannt"},
{"id": 950, "name": "CCU SV Status", "val": false,"ts":"2018-07-11 16:10:03","min":null,"max":null,"unit":"", "type": "boolean", "enum": "Normalbetrieb;Neustart"},
{"id": 2870, "name": "CCU-RemotePC", "val": "nicht%20erreichbar","ts":"2018-07-11 16:11:32","min":null,"max":null,"unit":"", "type": "string", "enum": ""},
{"id": 54846, "name": "Datum_MM.TT", "val": 7.110000,"ts":"2018-07-11 16:09:04","min":0,"max":65000,"unit":"", "type": "number", "enum": ""},
{"id": 3659, "name": "DutyCycle", "val": 3.000000,"ts":"2018-07-11 17:33:00","min":-100,"max":100,"unit":"%", "type": "number", "enum": ""},
{"id": 59841, "name": "Feiertag_heute", "val": false,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "boolean", "enum": "Arbeitstag;Feiertag"},
{"id": 59842, "name": "Feiertag_morgen", "val": false,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "boolean", "enum": "Arbeitstag;Feiertag"},
{"id": 2297, "name": "Fenster_Wohnung", "val": false,"ts":"2018-07-11 17:08:02","min":null,"max":null,"unit":"", "type": "boolean", "enum": "alle Fenster zu;min. 1 Fenster offen"},
{"id": 2720, "name": "Fensterstatus_Wohnzimmer", "val": false,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "boolean", "enum": "alle Fenster zu;mind. 1 Fenster offen"},
{"id": 3679, "name": "Feuer_Eingang", "val": false,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "boolean", "enum": "kein Feuer;Feuer"},
{"id": 3703, "name": "Feuer_Flur", "val": false,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "boolean", "enum": "kein Feuer;Feuer"},
{"id": 4303, "name": "Feuer_Kinderzimmer", "val": false,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "boolean", "enum": "kein Feuer;Feuer"},
{"id": 4302, "name": "Feuer_Schlafzimmer", "val": false,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "boolean", "enum": "kein Feuer;Feuer"},
{"id": 55223, "name": "Firewall", "val": "aktiviert","ts":"2018-07-11 16:10:07","min":null,"max":null,"unit":"", "type": "string", "enum": ""},
{"id": 2231, "name": "GB_Wohnzimmer", "val": false,"ts":"1970-01-01 01:00:00","min":null,"max":null,"unit":"", "type": "boolean", "enum": "nicht ausgelöst;ausgelöst"},
{"id": 62176, "name": "Kommunikation", "val": true,"ts":"2018-07-11 17:33:01","min":null,"max":null,"unit":"", "type": "boolean", "enum": "gestört;ok"},
{"id": 4271, "name": "mi_esszimmer", "val": false,"ts":"2018-07-11 17:31:08","min":null,"max":null,"unit":"", "type": "boolean", "enum": "keine Bewegung;Bewegung erkannt"},
{"id": 4272, "name": "mi_flur", "val": false,"ts":"2018-07-11 17:11:32","min":null,"max":null,"unit":"", "type": "boolean", "enum": "keine Bewegung;Bewegung erkannt"},
{"id": 4270, "name": "mi_kueche", "val": false,"ts":"2018-07-11 17:11:33","min":null,"max":null,"unit":"", "type": "boolean", "enum": "keine Bewegung;Bewegung erkannt"},
{"id": 4273, "name": "mi_wohnzimmer", "val": false,"ts":"2018-07-11 17:31:06","min":null,"max":null,"unit":"", "type": "boolean", "enum": "keine Bewegung;bewegung erkannt"},
{"id": 3506, "name": "random_tp", "val": 0.575777,"ts":"2018-07-11 17:30:01","min":-2,"max":2,"unit":"", "type": "number", "enum": ""},
{"id": 3505, "name": "random_zahl", "val": 0.500267,"ts":"2018-07-11 17:30:01","min":-2,"max":2,"unit":"", "type": "number", "enum": ""},
{"id": 4320, "name": "Rauchmelder", "val": false,"ts":"2018-07-11 16:09:13","min":null,"max":null,"unit":"", "type": "boolean", "enum": "kein Rauch;mind. 1 Melder Rauch erkannt"},
{"id": 3320, "name": "Sabotage_Wohnung", "val": false,"ts":"2018-07-11 16:09:28","min":null,"max":null,"unit":"", "type": "boolean", "enum": "in Ordnung;Sabotage"},
{"id": 3319, "name": "Sabotage_Wohnzimmer", "val": false,"ts":"2018-07-11 16:09:28","min":null,"max":null,"unit":"", "type": "boolean", "enum": "in Ordnung;Sabotage"},
{"id": 25970, "name": "Trockner", "val": false,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "boolean", "enum": "ist fertig;läuft"},
{"id": 59782, "name": "Urlaubstage", "val": 0,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "number", "enum": ""05.03.-09.03.;25.06.-13.07.;22.10.-02.11.""},
{"id": 26587, "name": "Wachmaschine", "val": false,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "boolean", "enum": "ist fertig;läuft"},
{"id": 60657, "name": "Wochentag", "val": 2,"ts":"2018-07-11 16:09:04","min":null,"max":null,"unit":"", "type": "number", "enum": "Montag;Dienstag;Mittwoch;Donnerstag;Freitag;Samstag;Sonntag"},
{"id": 2266, "name": "Wohnungsklingel", "val": false,"ts":"2018-07-11 17:33:21","min":null,"max":null,"unit":"", "type": "boolean", "enum": "ruhig;klingeln"}]

Gruß,
Mathias

**Comment by hobbyquaker** [comment]
Ok, das liegt an den Anführungszeichen in der Enum "Urlaubstage". Mein Rega-Modul escaped bisher nur die Werte von String-Variablen, Enums habe ich dummerweise vergessen zu escapen. Wird asap gefixed.

**Comment by hobbyquaker** [comment]
Ist nun (hoffentlich ;-) mit v1.0.3 gefixed.

**Comment by MathiasJZ** [comment]
Nun läuft es!
danke, Mathias
