### ISSUE TITLE
Get Value aus Gerät auslesen ohne Zwischenspeicher

### ISSUE THREAD

**Issue by CannyDuck** [rdmtc/RedMatic#270]
Der getValue-Node liest den Zustand aus dem Zwischenspeicher der CCU aus und greift nicht direkt auf das Gerät zu. Besteht die Möglichkeit direkt ein Auslesen aus dem Gerät zu triggern?

**Comment by hobbyquaker** [comment]
Bisher nur über RPC Node mit der getValue Methode. Das funktioniert aber nur für bestimmte Geräte, viele Geräte werden auch nur den vom rfd/hmipserver zwischengespeicherten Wert liefern (da sie Homematic-Prinzipbedingt gar nicht aktiv abgefragt werden können, wie z.B. Fensterkontakte)
Was für ein Usecase hast Du da im Sinn? Eigentlich sollte der Status spätestens nach dem ersten zyklischen Statusreport (bei HmIP Fensterkontakten z.B. nach ~ einer Stunde) stimmen, davor kann er aber eh nicht abgefragt werden, insofern frag ich mich ob Du damit eine Limitation des Homematic Systems selbst umgehen willst - was leider nicht möglich wäre.
