### ISSUE TITLE
Behavior msg.topic of ccu-rpc-event in Redmatic

### ISSUE THREAD

**Issue by Groofertje** [rdmtc/RedMatic#272]
I found something weird with the returning msg.topic of the node ccu-rpc-event in Redmatic 5.2.0

In the node the returning msg.topic is declared with "${room}/${datapoint}/${datapointType}/${payload}"
No problem with this al working fine exept when the payload is 0 or false, then the value is NOT showed (integrated) into the msg.topic. (I don't know with negatief value's).

This happend with both HMIP-RF as BIDCOS-RF.
But the msg.payload show the value 0 or false

==> Picture Node HmRFIP No payload 0
![Node HmRFIP No payload 0](https://user-images.githubusercontent.com/25877218/68188280-15b12e80-ffa9-11e9-8ba1-eda775f37530.png)

==> Picture Node BidCos No payload 0
![Node BidCos No payload 0](https://user-images.githubusercontent.com/25877218/68188282-15b12e80-ffa9-11e9-8599-88a3e0f0aacb.png)

Also if the node is declared HMIP-RF with the value OPERATING-VOLTAGE then the room and functions are NOT implemented neither into the msg.topic as in the msg(object). With the BidCos there is NO problem.

==>Picture Node HmRFIP No room
![Node HmRFIP No room](https://user-images.githubusercontent.com/25877218/68188303-1ba70f80-ffa9-11e9-84a1-8583035b629e.png)

I found a solution by redeclaring the topic myself in a separate function

I mentionned this behavior also in rdmtc/node-red-contrib-ccu
Srr for my poor english :)

**Comment by hobbyquaker** [comment]
https://github.com/rdmtc/node-red-contrib-ccu/issues/100
