### ISSUE TITLE
Unterstützung für neue x86-basierte RaspberryMatic Version

### ISSUE THREAD

**Issue by jens-maus** [rdmtc/RedMatic#273]
Mit der nächsten kommenden RaspberryMatic version wird es eine neue zusätzlich Plattform für RaspberryMatic geben. Dabei handelt es sich um eine x86 (i686) basierte Version die als erste Iteration für das erzeugen einer virtuellen RaspberryMatic unter Virtualisierungsumgebungen (sog. "ova" platform) herausgebracht wird.

Da die Binaries im hm-tools Addon momentan lediglich ARM-basierte Binaries sind funktioniert dieses Addon momentan leider nicht mit der neuen "ova" Plattform. Es wäre daher schön wenn das Addon entsprechend um diese zusätzlich Plattform erweitert werden könnte und binaries mit ausgeliefert werden die auf einem i686/x86 System lauffähig sind.

Mehr Information zur neuen "ova" Plattform findet man momentan hier:
https://homematic-forum.de/forum/viewtopic.php?f=65&t=54055#p538104

**Comment by hobbyquaker** [comment]
Ich wehr mich nicht dagegen, Details was es zu tun gibt hab ich Dir grad gemailt. Dennoch möchte ich hier noch anmerken: 
Ich rate bei der Verwendung von RaspberryMatic als VM eigentlich von RedMatic ab. Besser eine weitere VM aufsetzen und dort "ganz normal" Node-RED mit node-red-contrib-ccu nutzen, dann unterliegt man auch nicht der Buildroot-bedingten Beschränkung dass Nodes mit Binärmodulen nur genutzt werden können wenn ich sie vorgebaut für RedMatic liefere (siehe https://github.com/rdmtc/RedMatic/wiki/Node-Installation#nodes-mit-bin%C3%A4rmodulen).

**Comment by hobbyquaker** [comment]
https://homematic-forum.de/forum/viewtopic.php?f=77&t=55267&p=549659

**Comment by hobbyquaker** [comment]
... WIP

**Comment by hobbyquaker** [comment]
Ein erstes Beta Release steht zur Verfügung: https://github.com/rdmtc/RedMatic/releases/tag/v5.5.0-beta.0
