### ISSUE TITLE
Tasterinput vom HmIPW-DRI wird nicht erkannt

### ISSUE THREAD

**Issue by stefanfejfar** [rdmtc/RedMatic#275]
Hallo,

versuche mittels Taster, der am HmIPW-DRI hängt, meine Hues zu steuern.
Nach einigen Fehlversuchen habe ich den Tasteroutput auf den Debug Node ausgegeben - bleibt allerding leer. Mache ich mit demselben Gerät in der CCU eine Direktverknüpfung funktioniert diese. Nehme ich statt dem HmIPW-DRI einen HmIP Taster erhalte ich einen Output im Debug.
Gibt es technische Limitierungen oder bin ich nur zu blöd? :)

Gruß
Stefan

**Comment by Tscherno** [comment]
Leg mal ein leeres Programm auf der CCU an, in dem der der Taster irgendwie abgefragt wird. Damit wird die "Zentralenverknüfpung" hergestellt und Nodered sollte es auch mitbekommen. Das Programm ist danach nicht mehr notwendig.

**Comment by stefanfejfar** [comment]
Danke für die Lösung! Hatte zwar die FAQ überflogen, war allerdings total auf HmIPW-DRI fixiert... 
Jetzt muss ich nur noch einen passenden Flow bauen, der den Status der Hue erkennnt und mit einem Singletaster auf- und abdimmt, sowie zum richtigen Hue State ein- oder ausschaltet.

**Comment by Tscherno** [comment]
Das mit Hue toggle mit einem Taster hab ich auch mal versucht, hat aber nicht funktioniert. Der Author hat später eine Toggle-Funktion eingebaut, die hab ich aber noch nicht probiert.
https://github.com/Foddy/node-red-contrib-huemagic/issues/86

**Comment by DamianosS** [comment]
Ich hab das so gelöst: [Wandschalter 6fach to Hue.txt](https://github.com/rdmtc/RedMatic/files/3830338/Wandschalter.6fach.to.Hue.txt)
