### ISSUE TITLE
Smartmeter-Node nach Update auf 5.2.1 nicht mehr vorhanden

### ISSUE THREAD

**Issue by m50434** [rdmtc/RedMatic#276]
Scheinbar gibt es ein Problem mit dem Smartmeter-Node. 
Nachdem ich Redmatic von 5.2 auf 5.2.1 geupdated habe, wurde (soweit ich das sehen konnte) in diesem Zuge auch das Package "node-red-contrib-smartmeter" geupdated (jetzt bei 0.2.2). 
Nach dem Update ist der Node in Redmatic aber leider nicht mehr da...
Auch eine komplette Neuinstallation von Redmatic hat leider keinen Smartmeter-Node trotz aktiviertem Package.

**Comment by hobbyquaker** [comment]
Da müsste ich mal ein Blick ins Debug Log werfen (https://github.com/rdmtc/RedMatic/wiki/Loglevel)

**Comment by m50434** [comment]
Im Log-File ist einerseits ein Fehler wegen des Smartmeters zu finden, außerdem auch der Fehler, den ich bereits zum Johnny5-Node in dem anderen [Issue 269](https://github.com/rdmtc/RedMatic/issues/269) gepostet habe.


Zum Smartmeter:

Nov 10 21:48:05 homematic-ccu2 daemon.info node-red[5748]: Dashboard version 2.17.1 started at /addons/red/ui
Nov 10 21:48:06 homematic-ccu2 daemon.info node-red[5748]: node-red-contrib-ccu version: 3.1.2
Nov 10 21:48:07 homematic-ccu2 daemon.warn node-red[5748]: ------------------------------------------------------
Nov 10 21:48:07 homematic-ccu2 daemon.warn node-red[5748]: [node-red-contrib-smartmeter/smartmeter] Error: /usr/local/addons/redmatic/lib/node_modules/node-red-contrib-smartmeter/node_modules/smartmeter-obis/node_modules/serialport/build/Release/serialport.node: wrong ELF class: ELFCLASS64
Nov 10 21:48:07 homematic-ccu2 daemon.warn node-red[5748]: ------------------------------------------------------



Zu Johnny5:
Nov 10 21:48:09 homematic-ccu2 daemon.debug node-red[5748]: [j5-platform:a7e087b6.96c53] start plugin raspi-io [{"enableSerial":false,"enableI2C":false,"excludePins":["GPIO2","GPIO3","GPIO4","GPIO5","GPIO6","GPIO7","GPIO8","GPIO9","GPIO10","GPIO11","GPIO12","GPIO13","GPIO14","GPIO15","GPIO16","GPIO17","GPIO18","GPIO19","GPIO20","GPIO21","GPIO22","GPIO23","GPIO24","GPIO25"]}]
Nov 10 21:48:09 homematic-ccu2 daemon.err node-red: 1573418889920 Available Raspi IO  
Nov 10 21:48:10 homematic-ccu2 daemon.info node-red[5748]: Started flows
Nov 10 21:48:10 homematic-ccu2 daemon.debug node-red[5748]: [j5-platform:a7e087b6.96c53] io connected
Nov 10 21:48:10 homematic-ccu2 daemon.err node-red: 1573418890085 Connected Raspi IO  
Nov 10 21:48:10 homematic-ccu2 daemon.debug node-red[5748]: [j5-platform:a7e087b6.96c53] board ready
Nov 10 21:48:10 homematic-ccu2 daemon.err node-red: 25 => 25
Nov 10 21:48:10 homematic-ccu2 daemon.err node-red: [Object: null prototype] {
Nov 10 21:48:10 homematic-ccu2 daemon.err node-red:   supportedModes: [ 0, 1, 3, 4 ],
Nov 10 21:48:10 homematic-ccu2 daemon.err node-red:   mode: [Getter],
Nov 10 21:48:10 homematic-ccu2 daemon.err node-red:   value: [Getter/Setter],
Nov 10 21:48:10 homematic-ccu2 daemon.err node-red:   report: 1,
Nov 10 21:48:10 homematic-ccu2 daemon.err node-red:   analogChannel: 127 }
Nov 10 21:48:10 homematic-ccu2 daemon.err node-red[5748]: [j5-gpio-in:99b0a3ee.654d6] Unknown mode undefined

**Comment by hobbyquaker** [comment]
@m50434 kannst Du mal bitte checken ob RedMatic 5.2.4 diese Probleme aus der Welt geschaffen hat?

**Comment by m50434** [comment]
Hi,
habe jetzt RedMatic 5.2.5 installiert. Der Smartmeter-Node funktioniert jetzt wieder und ich konnte den Node auch erfolgreich testen.

**Comment by dos-ise** [comment]
Hi,

bei mir ist der smartmeter node auch weg. Ich kann leider nicht ausschließen das ich ihn mal deinstalliert habe.

Gibt es eine Möglichkeit ihn zu installieren ohne Redmatic Neuinstallation? 
Über npm geht es ja nicht da er über fehlendes python meckert.

Danke für schonmal für die Hilfe.

Gruß Dennis
