### ISSUE TITLE
RedMatic 5.2.1 - Update lässt sich nicht installieren

### ISSUE THREAD

**Issue by djiwondee** [rdmtc/RedMatic#278]
Auf meiner CCU3-Hardware läuft aktuell RedMatic `5.0.5`, welches ich kurz nach Erscheinen gemäß [Installationsanleitung](https://github.com/rdmtc/RedMatic/wiki/Update) erfolgreich installieren konnte.

Mittlerweile habe ich die CCU3 Firmware auf Version `3.47.22` aktualisiert und wollte das RedMatic Update `5.2.1` nachinstallieren.

Das Update schlug fehl. Die CCU3 meldete diverse Dienste als nicht verfügbar und ist dann wohl abgestürzt:
- _Dauerhaft rotes Leuchten der System-LED_
- _System nicht bereit (mindestens eine Systemkomponente konnte nicht gestartet werden)_ 

Gemäß der Empfehlung zur Fehlerbehebung für die CCU3 _(Starten Sie die Zentrale neu. Bei erneuter Fehlermeldung kontaktieren Sie bitte den Support)_ habe ich die Zentrale vom Strom getrennt und wieder angeschlossen. Das System ist wieder hochgefahren und funktioniert. 

Die Einstellungen für _Zusatzsoftware_ zeigt weiterhin:

<img width="811" alt="image" src="https://user-images.githubusercontent.com/37173958/68577800-0f232b00-0471-11ea-8e2b-4de29f4e093c.png">

Gibt es bitte ein Empfehlung, wie ich weiter verfahren sollte? Vielen Dank im Voraus!

**Comment by Tscherno** [comment]
Versuch es erstmal im abgesicherten Modus ohne Addons. Ansonsten habe ich mit dem Addon rmupdate sehr gute Erfahrungen gemacht. Das macht das ganze auch etwas komfortabler.
https://github.com/j-a-n/raspberrymatic-addon-rmupdate

**Comment by djiwondee** [comment]
@Tscherno: Danke für die Tipps

> Versuch es erstmal im abgesicherten Modus ohne Addons

CCU3 zeigt nach Klick auf Neustart gleich _dauerhaft rotes Leuchten der System-LED_

> Addon rmupdate sehr gute Erfahrungen

Würde gerne erst mal vermeiden, weitere Add-Ons zu installieren, solange es mit RedMatic-Update das Problem gibt. Aber ist das _ rmupdate_ auch für CCU3 Hardware supported?

**Comment by Tscherno** [comment]
Die CCU3 Hardware ist nichts anderes wie ein Raspberry 3 mit verdecktem USB-Port und dem HM-Funkmodul... Aber vermutlich funktioniert es nicht mit der normalen Firmware. Raspberrymatic müsste aber auch auf der CCU3 laufen, hat noch einige andere Vorteile.

**Comment by hobbyquaker** [comment]
das rmupdate Addon funktioniert (für das Update von Addons) auch auf einer CCU3 einwandfrei und ist tatsächlich die bessere Wahl da es wesentlich effizienter zugange ist als der Addon Installationsmechanismus des WebUI (es entpackt die Addons nicht in einem tmpfs/ramdisk und vermeidet damit Probleme mit dem leider nur endlich vorhandenen Speicher ;-)
Ist auch ein "harmloses Addon", solange Du die WebUI des rmupdate Addons nicht aufrufst tut es nichts weiter als nicht nennenswert viel Platz auf der SD Card belegen.

> Die CCU3 meldete diverse Dienste als nicht verfügbar

Das kann im Verlauf einer Addon Installation - genauer gesagt wenn der Reboot passiert - eine normale Reaktion im im CCU-WebUI sein. Nach dem Reboot beginnt dann erst die eigentliche Installation - und die kann durchaus lange (bis ~15 Minuten) dauern. Ob währenddessen die LED rot ist weiss ich allerdings nicht. Wie lange hast Du in dem Zustand gewartet?

**Comment by djiwondee** [comment]
Hallo @hobbyquaker 

vielen Dank für die Antwort auf dieses Problem. Habe es dem neuen Release `5.2.2` erneut versucht. Das Verhalten mit der Ausgabe von nicht verfügbaren Diensten, wie z. B.

<img width="970" alt="Bildschirmfoto 2019-11-17 um 12 05 12" src="https://user-images.githubusercontent.com/37173958/69006834-5576ff00-0935-11ea-88bb-5f0b52c84db3.png">

für `Virtual Devices`, `HmIP-RF`, `BidCos-RF` und `ReGa` sind dieses Mal auch wieder aufgetreten. Nach 10 Minuten Wartezeit stand die CCU3-GUI aber wieder zur Neuanmeldung Verfügung. RedMatic is problemlos mit dem neuen Release gestartet.

Ich hatte so einen Verlauf bei den bisherigen Updates von RedMatic noch nie gesehen. Diesmal gab es auch kein rotes Dauerleuchten der CCU3-Status-LED. Das nächste Mal werde ich hier geduldiger sein.
