### ISSUE TITLE
getRegaVariables Error:

### ISSUE THREAD

**Issue by peterfendt** [rdmtc/RedMatic#280]
Hallo zusammen,
ich habe vor einigen Monaten Redmatic auf meinem Raspberrymatic installiert.
Im Debug log der Redmatic finde ich fortlaufend folgende Fehlermeldung und kann nicht auf die SystemVariablen der CCU3 zugreifen:
msg : string[94]
"getRegaVariables Error: JSON.parse failed. Saved debug data to /tmp/variables.rega.failed.json"
Was soll ich tun?

CCU Version:  3.47.22.20191026
Redmatic:  5.2.2

Error file variables.rega.failed.json siehe Anhang
[variables.rega.failed.txt](https://github.com/rdmtc/RedMatic/files/3884051/variables.rega.failed.txt)

Grüße,
Peter

**Comment by hobbyquaker** [comment]
Der Fehler tritt hier auf:
```
{
		"id": 1390,
		"name": "Regen%20gestern",
		"info": "Regenmenge%20vorheriger%20Tag",
		"val": 0,
		"ts": "2019-11-10 11:31:59",
		"min": 0.000000 / 10,
		"max": 1000.000000,
		"unit": "mm",
		"type": "number",
		"enum": "",
		"channel": "1379"
	},
```

Beim erzeugen dieses JSON kommt bei der Variable `Regen gestern` für das Attribut `min` von der Rega ein sehr seltsamer Wert zurück (`0.000000 / 10`), das macht das JSON invalide. Ich versuch das in einem zukünftigen Release abzufangen, aber es wäre dennoch jetzt interessant zu sehen ob sich das beheben lässt indem Du mal den Min Wert dieser Variable mal auf z.B. 1 änderst und dann wieder auf 0 zurückänderst (danach Node-RED neu starten und mal schauen ob der Fehler immer noch auftritt).

**Comment by peterfendt** [comment]
Hallo Sebastian,
ich habe diese falschen Min Wert (0/10) auf 0 geändert und jetzt läuft es, sogar ohne Neustart der Redmatic. 

Danke!
Peter
