### ISSUE TITLE
Installation scheitert

### ISSUE THREAD

**Issue by rolexplatin** [rdmtc/RedMatic#286]
![D42F12D3-FC97-4408-8226-2E118D4498E2](https://user-images.githubusercontent.com/58333061/69869774-21dd9280-12ae-11ea-9827-060fd3ffdc4f.jpeg)
![5D2065D2-C6B1-44C3-8843-A91ECD630E4A](https://user-images.githubusercontent.com/58333061/69869775-21dd9280-12ae-11ea-99c1-36e5f169bf92.jpeg)
![919C8936-4BF3-4479-8D1B-29DBDD496486](https://user-images.githubusercontent.com/58333061/69869776-21dd9280-12ae-11ea-948a-7b72f8b84769.jpeg)
![C5CD8E91-7FA7-4955-8894-48B06DAE53E0](https://user-images.githubusercontent.com/58333061/69869777-22762900-12ae-11ea-99bb-e9504eceb94d.jpeg)

HI 

Ich bin der Anleitung zum installieren der v5.2.3 Version gefolgt aber meine CCu3 bzw. Teile davon brechen die installation immer wieder ab. Meldung habe ich als bild begefügt! Was mache ich falsch? Dachte erst die CCU3 muss ein update bekommen, braucht Sie aber nicht! VPN habe ich erst einmal auf meinem IPad ausgeschalten, hat auch keinen Erfolg gebracht?!?!

**Comment by djiwondee** [comment]
Hallo @rolexplatin , 

diese Symptome hatte ich auch. Bei mir war Geduld der Schlüssel zum Erfolg. Siehe [hier](https://github.com/rdmtc/RedMatic/issues/278#issuecomment-554460963)

**Comment by hobbyquaker** [comment]
@rolexplatin kannst Du es noch mal versuchen und dabvei beachten was ich in dem von djiwondee verlinkten Kommentar schrieb? Ich vermute auch dass es einfach länger gedauert hätte als Du Geduld hattest ;-)

**Comment by rolexplatin** [comment]
[](url)

> @rolexplatin kannst Du es noch mal versuchen und dabvei beachten was ich in dem von djiwondee verlinkten Kommentar schrieb? Ich vermute auch dass es einfach länger gedauert hätte als Du Geduld hattest ;-)

Ich probiere es noch einmal....
