### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 1001 drain listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by Tscherno** [rdmtc/RedMatic#287]
Da ich seit dem letzten Raspberrymatic-Update mit massiven Probleme zu kämpfen habe, sehe ich gerade alle Logfiles durch. Dabei ist mir bei Nodered folgendes aufgefallen:
Dec  2 17:50:22 homematic daemon.err node-red: (node:1385) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 1001 drain listeners added. Use emitter.setMaxListeners() to increase limit

Der Eintrag kommt direkt nach dem Start von Nodered. Ist das bedenenklich oder kann man es ignorieren?

**Comment by hobbyquaker** [comment]
@Tscherno Kannst Du mir mal das Log zukommen lassen? (Falls Du es nicht öffentlich machen willst an hobbyquaker@gmail.com, aber bitte hier dann Bescheid geben nachdem Du eine Mail geschickt hast)

**Comment by Tscherno** [comment]
Das sind tatsächlich alle Einträge:

Dec  2 17:48:16 homematic daemon.info redmatic: Starting Node-RED after reboot ... waiting 30 seconds...
Dec  2 17:48:46 homematic daemon.info redmatic: RedMatic v5.2.3 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Dec  2 17:48:47 homematic daemon.info redmatic: Waiting 45 seconds before activating monit services
Dec  2 17:48:47 homematic daemon.info redmatic: Starting Node-RED
Dec  2 17:49:31 homematic daemon.err node-red: Checking for Hue Bridge updates…
Dec  2 17:49:31 homematic daemon.err node-red: SoftwareUpdate {
Dec  2 17:49:31 homematic daemon.err node-red:   attributes:
Dec  2 17:49:31 homematic daemon.err node-red:    Attributes {
Dec  2 17:49:31 homematic daemon.err node-red:      attributes:
Dec  2 17:49:31 homematic daemon.err node-red:       { updatestate: 0,
Dec  2 17:49:31 homematic daemon.err node-red:         checkforupdate: true,
Dec  2 17:49:31 homematic daemon.err node-red:         devicetypes: [Object],
Dec  2 17:49:31 homematic daemon.err node-red:         url: '',
Dec  2 17:49:31 homematic daemon.err node-red:         text: '',
Dec  2 17:49:31 homematic daemon.err node-red:         notify: false },
Dec  2 17:49:31 homematic daemon.err node-red:      changed: {} } }
Dec  2 17:49:32 homematic user.info monit[1403]: 'redmatic-diskusage' monitor on user request
Dec  2 17:49:32 homematic user.info monit[1403]: 'redmatic-nodered' monitor on user request
Dec  2 17:49:32 homematic user.info monit[1403]: 'redmatic-nodered' monitor action done
Dec  2 17:49:32 homematic user.info monit[1403]: 'redmatic-diskusage' monitor action done
Dec  2 17:49:33 homematic daemon.err node-red: No Hue Bridge updates available. Checking again in an hour…
Dec  2 17:50:22 homematic daemon.err node-red: (node:1385) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 1001 drain listeners added. Use emitter.setMaxListeners() to increase limit

**Comment by Tscherno** [comment]
Das Logging war auf Error. Ich habe es auf Debug gestellt, aber jetzt kommt der Fehler nicht mehr. Ich habe mittlerweile ein Rollback auf die ältere Raspberrymatic-Version gemacht. Es könnte da einen Zusammenhang geben. Ich hatte massive Probleme mit der neuersten Version, deswegen habe ich überhaupt in die Logfiles geschaut.

https://github.com/jens-maus/RaspberryMatic/issues/745

**Comment by Sineos** [comment]
> Dec 2 17:50:22 homematic daemon.err node-red: (node:1385)

https://nodered.org/docs/user-guide/editor/workspace/search

Kannst du die Node identifizieren, die den Fehler wirft? --> Suche über die ID 1385

**Comment by Tscherno** [comment]
Damit finde ich nichts. Aber sicher, dass es eine Node-ID ist? Die sehen ganz anders aus. Klingt eher wie ne PID.

**Comment by hobbyquaker** [comment]
Ich würde als Ursache als erstes RedMatic-HomeKit verdächtigen, nutzt Du das?

**Comment by hobbyquaker** [comment]
Bin mittlerweile ziemlich sicher dass node-red-contrib-zigbee der Verursacher ist. Habe ein paar Verbesserungen vorgenommen und das Logging etwas "gesprächiger" gemacht, falls das mit RedMatic 5.2.4 noch auftritt bitte mal ein Log auf Debug Level erzeugen das den Node-RED Start sowie einen Full-Deploy beinhaltet.

**Comment by Tscherno** [comment]
Zigbee verwende ich nicht :-| Homekit hingegen schon. Ich hatte auch HM-MQTT aktiv, das habe ich mittlerweile auch rausgeschmissen. Ich kann es leider (bzw. zum Glück) nicht mehr nachvollziehen, daher auch kein neues Logfile erzeugen... Falls es nochmal auftritt, erzeuge ich ein Debug-Log und würde das hier wieder öffnen.
