### ISSUE TITLE
Rega Variablen Abfrage schlägt fehl

### ISSUE THREAD

**Issue by AnMiPe** [rdmtc/RedMatic#292]
Hi!

Habe schon gesehen, dass es das Problem anscheinend schon einmal gab, aber bei mir tritt es jetzt nach einem Upgrade auf die aktuellste Redmatic Version auf. Variablen der CCU3 sind disconnected und HomeKit funktioniert nicht mehr (Partly disconnected). Anbei mein Logfile mit Fehlern wie:

Dec 14 18:41:06 ccu3-webui daemon.info node-red[1321]: [ccu-connection:localhost] regadata saved to /usr/local/addons/redmatic/var/ccu_rega_localhost.json
Dec 14 18:41:34 ccu3-webui daemon.err node-red[1321]: [ccu-connection:localhost] setVariable failed. variables still not known after timeout
Dec 14 18:41:34 ccu3-webui daemon.err node-red[1321]: [ccu-connection:localhost] setVariable failed. variables still not known after timeout
Dec 14 18:41:36 ccu3-webui daemon.err node-red[1321]: [ccu-connection:localhost] getRegaVariables Error: JSON.parse failed. Saved debug data to /tmp/variables.rega.failed.json

Vielen Dank!!!

[redmatic.2019-12-14T17_46_19.841Z.log](https://github.com/rdmtc/RedMatic/files/3964130/redmatic.2019-12-14T17_46_19.841Z.log)

**Comment by hobbyquaker** [comment]
Kannst Du mir mal den Inhalt der Datei `/tmp/variables.rega.failed.json` zeigen? (Kannst Du z.B. mit Filezilla oder WinSCP von der CCU runterkopieren, dazu muss SSH in den CCU Einstellungen aktiviert sein)

**Comment by hobbyquaker** [comment]
related: https://github.com/rdmtc/node-red-contrib-ccu/issues/104

**Comment by AnMiPe** [comment]
Gerne! Inhalt ist:

[{"id": 40, "name": "Alarmmeldungen", "val": 0, "min": 0, "max": 65000, "unit": "", "type": "number", "enum": ""},
{"id": 41, "name": "Servicemeldungen", "val": 0, "min": 0, "max": 65000, "unit": "", "type": "number", "enum": ""},
{"id": 13046, "name": "%24%7BsysVarRainToday%7D", "info": "%24%7BsysVarRainTodayDescr%7D", "val": 0,"ts":"2019-12-14 18:54:34","min":0.000000,"max":1000.000000,"unit":"mm", "type": "number", "enum": "", "channel": "65535"},
{"id": 13047, "name": "%24%7BsysVarRainYesterday%7D", "info": "%24%7BsysVarRainYesterdayDescr%7D", "val": 0,"ts":"2019-12-14 18:54:34","min":0.000000,"max":1000.000000,"unit":"mm", "type": "number", "enum": "", "channel": "65535"},
{"id": 1233, "name": "Alarmzone%20Extern", "info": "Alarmmeldung%20Alarmzone%20Extern", "val": false,"ts":"1970-01-01 01:00:00","min":null,"max":null,"unit":"", "type": "boolean", "enum": "nicht%20ausgel%F6st;ausgel%F6st", "channel": "65535"},
{"id": 7841, "name": "Ankunft", "info": "Zeitperiode%20Ankunft", "val": false,"ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "boolean", "enum": "Deaktiv;Jemand%20kommt%20nach%20Hause", "channel": "65535"},
{"id": 950, "name": "CCU%20Status", "info": "Anwesenheit", "val": false,"ts":"2019-12-14 18:56:41","min":null,"max":null,"unit":"", "type": "boolean", "enum": "L%E4uft;Neustart", "channel": "65535"},
{"id": 3368, "name": "Dunkel", "info": "Nacht%20und%20Tag%20Wechsel", "val": true,"ts":"2019-12-14 18:54:41","min":null,"max":null,"unit":"", "type": "boolean", "enum": "Nicht%20Dunkel;Dunkel", "channel": "65535"},
{"id": 7021, "name": "DutyCycle", "info": "Verbrauch%20DutyCycle", "val": 4.000000,"ts":"2019-12-14 19:00:00","min":0,"max":100,"unit":"%", "type": "number", "enum": "", "channel": "65535"},
{"id": 10718, "name": "Heizperiode", "info": "Zentrale%20Bedingung%20f%FCr%20Heizungssteuerung", "val": true,"ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "boolean", "enum": "Nicht%20Heizen;Heizen", "channel": "65535"},
{"id": 6735, "name": "hk_Anwesenheit", "info": "Anwesenheitserkennung", "val": true,"ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "boolean", "enum": "Niemand%20zu%20Hause;Jemand%20ist%20anwesend", "channel": "65535"},
{"id": 10203, "name": "hk_homeoffice", "info": "", "val": false,"ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "boolean", "enum": "Nein;Ja", "channel": "65535"},
{"id": 4681, "name": "pocketControlPushMessage", "info": "Change%20the%20value%20to%20push.%20Do%20not%20delete!", "val": "CCU%20Reboot%3F%20to(Andre)","ts":"2019-12-14 18:54:42","min":null,"max":null,"unit":"", "type": "string", "enum": "", "channel": "65535"},
{"id": 10051, "name": "Putzfrau%20anwesend", "info": "", "val": false,"ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "boolean", "enum": "Nein;Ja", "channel": "65535"},
{"id": 4408, "name": "W_Aktualisierung", "info": "", "val": "","ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "string", "enum": "", "channel": "65535"},
{"id": 4409, "name": "W_Bedingungen", "info": "", "val": "","ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "string", "enum": "", "channel": "65535"},
{"id": 13162, "name": "W_Helligkeit", "info": "", "val": 78.000000,"ts":"2019-12-14 18:54:34","min":0,"max":10000,"unit":"", "type": "number", "enum": "", "channel": "65535"},
{"id": 4417, "name": "W_Luftdruck", "info": "", "val": 0,"ts":"2019-12-14 18:54:34","min":,"max":,"unit":"mb", "type": "number", "enum": "", "channel": "65535"},
{"id": 4418, "name": "W_Luftdrucktrend", "info": "", "val": "","ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "string", "enum": "", "channel": "65535"},
{"id": 4411, "name": "W_Luftfeuchte", "info": "", "val": 0,"ts":"2019-12-14 18:54:34","min":,"max":,"unit":"%", "type": "number", "enum": "", "channel": "65535"},
{"id": 4407, "name": "W_Station", "info": "", "val": "","ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "string", "enum": "", "channel": "65535"},
{"id": 4419, "name": "W_Taupunkt", "info": "", "val": 0,"ts":"2019-12-14 18:54:34","min":,"max":,"unit":"Â°C", "type": "number", "enum": "", "channel": "65535"},
{"id": 4410, "name": "W_Temperatur", "info": "", "val": 0,"ts":"2019-12-14 18:54:34","min":-50,"max":60,"unit":"Â°C", "type": "number", "enum": "", "channel": "65535"},
{"id": 4420, "name": "W_UV", "info": "", "val": "0.000000","ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "string", "enum": "", "channel": "65535"},
{"id": 4412, "name": "W_Windbedingungen", "info": "", "val": "","ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "string", "enum": "", "channel": "65535"},
{"id": 4416, "name": "W_Windboeen", "info": "", "val": 0,"ts":"2019-12-14 18:54:34","min":,"max":,"unit":"km/h", "type": "number", "enum": "", "channel": "65535"},
{"id": 4415, "name": "W_Windgeschwindigkeit", "info": "", "val": 37.080000,"ts":"2019-12-14 18:54:34","min":,"max":,"unit":"km/h", "type": "number", "enum": "", "channel": "65535"},
{"id": 4414, "name": "W_Windrichtg", "info": "", "val": 250.000000,"ts":"2019-12-14 18:54:34","min":,"max":,"unit":"Â°", "type": "number", "enum": "", "channel": "65535"},
{"id": 4413, "name": "W_Windrichtung", "info": "", "val": "240","ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "string", "enum": "", "channel": "65535"},
{"id": 11728, "name": "WZ_Szenen", "info": "Hue%20Szenen%20f%FCr%20WZ", "val": 0,"ts":"2019-12-14 18:54:34","min":null,"max":null,"unit":"", "type": "number", "enum": "nfzjFQFHHka6q2P%3BHrsQfRAONzPyixo%3B2S52D0TDXUWv3Zu", "channel": "65535"}]

**Comment by AnMiPe** [comment]
Und leider: Obwohl Homekit auf “partly connected” steht sind alle Homematic Geräte auf “Keine Antwort”. Ist das ein Folgefehler? Kann ich dich noch irgendwie mit irgendwas unterstützen?

**Comment by hobbyquaker** [comment]
Sollte mit RedMatic 5.2.6 gefixt sein. @AnMiPe bitte gib Bescheid ob es wie erwartet funktioniert.

**Comment by AnMiPe** [comment]
Funktioniert wieder! Dankeschön und tolle Feiertage und alles Gute für 2020!
