### ISSUE TITLE
Error: EROFS: read-only file system

### ISSUE THREAD

**Issue by Matten-Matten** [rdmtc/RedMatic#294]
Hallo @hobbyquaker 
Erst einmal Frohe Weihnachten.
Mir ist aufgefallen, das Wenn die Homematic Neu gestartet wurde und dementsprechend Redmatic auch, so wie ein manuelles Starten von Redmatic (über homematic script) ,
![Node-RED _ 192 168 27 42-26 12 2019_11_39_41](https://user-images.githubusercontent.com/32074970/71472773-9ab00b80-27d4-11ea-8edb-ca4564a52224.png)

können keine Dateien im Flow beschrieben oder gelesen werden mit folgender Fehlermeldung:

`Schreiben in Datei fehlgeschlagen: Error: EROFS: read-only file system`

erst wenn ich über die Redmatic configurationsmaske Redmatic neu starte funktioniert das wieder. 
![RedMatic-26 12 2019_11_40_08](https://user-images.githubusercontent.com/32074970/71472784-a3a0dd00-27d4-11ea-8a66-3916027291f4.png)

Gibt es da eine möglichkeit das zu beheben?

Gruß
Matten Matten

**Comment by hobbyquaker** [comment]
Bist Du sicher dass das auch nach einem Neustart auftritt? Kann das (bis jetzt) nicht reproduzieren. Und wie genau startest Du RedMatic via Homematic Script neu?

**Comment by Matten-Matten** [comment]
Hey, ja ich bin mir sicher.

Das script:
`system.Exec("/etc/config/rc.d/redmatic start &");`
bzw:
`system.Exec("/etc/config/rc.d/redmatic restart &");`

Datei beschreiben:
![vol](https://user-images.githubusercontent.com/32074970/71520019-66167f80-28ba-11ea-8cef-3313c5f2b76d.png)
Config dieser Datei:
![vol conf](https://user-images.githubusercontent.com/32074970/71520041-834b4e00-28ba-11ea-80df-01c7abbe9353.png)

Datei lesen:
![vol read](https://user-images.githubusercontent.com/32074970/71520054-92320080-28ba-11ea-95e5-71f40099e7e9.png)
Config dieser Datei:
![vol conf](https://user-images.githubusercontent.com/32074970/71520063-9f4eef80-28ba-11ea-8333-f6f20eb446dd.png)

Das selbe bei einem zweiten Redmatic System.

Gruß
Matten Matten

**Comment by hobbyquaker** [comment]
Ah ok, hab's jetzt auch reproduzieren können. Das passiert wenn Du einen relativen Pfad (bei Dir `KuecheVolume`) angibst. Ob ich das Verhalten ändern kann weiss ich nicht, diese File Nodes nutzen bei relativen Pfaden das "cwd" (current working directory), ich befürchte das könnte ich nur ändern wenn ich Node-RED patche, davon würde ich aber lieber absehen. 
Ich würde daher empfehlen einfach ein absoluten Pfad zu nutzen (z.B. `/usr/local/addons/redmatic/var/KuecheVolume` oder noch besser auf einem USB-Stick falls vorhanden, z.B. `/media/usb1/KuecheVolume`). Mit einem absoluten Pfad ist dann auch eindeutig definiert wo die Datei liegt.

**Comment by Matten-Matten** [comment]
Okay, dann teste ich das. Vielen Dank schonmal für die Hilfe!

**Comment by Matten-Matten** [comment]
Der aktuelle pfade der dateien ist:
`/usr/local/addons/redmatic/www`
kann ich den ersteinmal weiter nutzen?

**Comment by hobbyquaker** [comment]
Würde ich von abraten. Grundsätzlich besser auf den USB Stick als auf die SD Karte. Und wenn Du es in `www` speicherst ist es über den Webserver erreichbar - ohne Authentifizierung. Ob das gewünscht ist musst Du abwägen ;-)

**Comment by Matten-Matten** [comment]
Ok, dann auf gar keinen fall! Danke für den tip.

Und noch ein großes Lob für die Zigbee Anbindung! Ich hab gestern meine zickigen Osram plugs angelernt und musste nicht einmal mehr den Z-Stack resetten. 

Schönes Wochenende. 
Gruß
Matten Matten
