### ISSUE TITLE
Probleme mit Taster (Real wie virtuell)

### ISSUE THREAD

**Issue by TheBassfly** [rdmtc/RedMatic#296]
Moin

Ich hab real neu Redmatic nun drauf und hab auch meine ersten Flows erstellt. Gerade Homekit ist Mega.
Aber nun mein Problem:
Ich nutze einen WRC6 und ich habe das Problem, daß ich nur aus dem Taster 1 (Channel 1) einen Wert bekomme.
Ich nutze 1 und 2 als An/Aus Taster für Beleuchtung. Drücke ich die 1 kommt auch ein Wert der auch ausgegeben wird. 
Auf der 2 passiert dahingehend garnix. Aktuell ist mein Workaround, das in der CCU der Taster 2 ein Programm auslöst, das mit auf den virtuellen BidCo Taster 1 die Taste drückt. Dann funktioniert es auch in der Redmatic.
Aus Spaß habe ich auch mal probiert, daß der Taster stattdessen die BidCo Taste 2 drückt. Auch dann passiert in Redmatic wieder nichts. Gibt es da eine Limitierung oder übersehe ich da in den Flows etwas? Muss ich den Channel Index vergeben? Nutze bisher den RPC-Event Node.

Danke und Gruß

**Comment by DamianosS** [comment]
Hi @TheBassfly!

Du musst jedem Schalter des WRC6 auf der Homematic-Seite einmalig ein Programm zuweisen (das gar nichts tun braucht, kannst danach auch wieder löschen). Dann sind die Events auch extern sichtbar. War bei mir (Home Assisstant) auch so.

Gruß, Damos

**Comment by TheBassfly** [comment]
Danke für den Tip. Den habe ich schon probiert, aber der funktioniert nicht. Mal davon ab, daß es dann ja für den BidCo Channel 2 auch gelten müsste. Der funktioniert ja auch nicht.
Hab auch schon mit dem Homematic Manager probiert. Ebenso kein Erfolg.

**Comment by hobbyquaker** [comment]
Zeig mal bitte Dein Flow (Screenshot der RPC Event Config, JSON Export)

**Comment by TheBassfly** [comment]
![Bildschirmfoto 2020-01-03 um 13 06 51](https://user-images.githubusercontent.com/59471393/71722729-2dcaf000-2e2a-11ea-9bc3-1771c4ddd0aa.png)

`[
    {
        "id": "fce0c19c.43d228",
        "type": "tab",
        "label": "Homekit",
        "disabled": false,
        "info": ""
    },
    {
        "id": "935e8d22.eb345",
        "type": "redmatic-homekit-homematic-devices",
        "z": "fce0c19c.43d228",
        "ccuConfig": "38263145.35ea0e",
        "bridgeConfig": "bfaad174.ed00a",
        "devices": {
            "0000DA499255AF:1": {
                "type": "Door",
                "disabled": false
            },
            "QEQ0094250:1": {
                "type": "Lightbulb",
                "disabled": false
            },
            "00085A49930C99:4": {
                "type": "Lightbulb",
                "disabled": false
            },
            "PEQ2221966:1": {
                "type": "Lightbulb",
                "disabled": false
            },
            "00085A49902209:4": {
                "type": "Lightbulb",
                "disabled": false
            },
            "PEQ2221765:1": {
                "type": "Lightbulb",
                "disabled": false
            }
        },
        "x": 900,
        "y": 480,
        "wires": []
    },
    {
        "id": "57d293ba.6fd1ec",
        "type": "redmatic-homekit-programmableswitch",
        "z": "fce0c19c.43d228",
        "bridgeConfig": "bfaad174.ed00a",
        "name": "KücheOff",
        "count": "1",
        "x": 500,
        "y": 420,
        "wires": []
    },
    {
        "id": "a31e1cd1.2c522",
        "type": "redmatic-homekit-programmableswitch",
        "z": "fce0c19c.43d228",
        "bridgeConfig": "bfaad174.ed00a",
        "name": "KücheOn",
        "count": "1",
        "x": 540,
        "y": 480,
        "wires": []
    },
    {
        "id": "67f2b1a8.831738",
        "type": "ccu-rpc-event",
        "z": "fce0c19c.43d228",
        "name": "",
        "iface": "HmIP-RF",
        "ccuConfig": "38263145.35ea0e",
        "rooms": "",
        "roomsRx": "str",
        "functions": "",
        "functionsRx": "str",
        "device": "",
        "deviceRx": "str",
        "deviceName": "6fach Taster Flur EG",
        "deviceNameRx": "str",
        "deviceType": "",
        "deviceTypeRx": "str",
        "channel": "",
        "channelRx": "str",
        "channelName": "HmIP-WRC6 000B5A4992D97D:1",
        "channelNameRx": "str",
        "channelType": "",
        "channelTypeRx": "str",
        "channelIndex": "",
        "channelIndexRx": "str",
        "datapoint": "PRESS_SHORT",
        "datapointRx": "str",
        "change": false,
        "working": false,
        "cache": false,
        "topic": "${channelIndex}/${datapoint}",
        "x": 280,
        "y": 420,
        "wires": [
            [
                "57d293ba.6fd1ec"
            ]
        ]
    },
    {
        "id": "9324106c.ffc55",
        "type": "ccu-rpc-event",
        "z": "fce0c19c.43d228",
        "name": "",
        "iface": "HmIP-RF",
        "ccuConfig": "38263145.35ea0e",
        "rooms": "",
        "roomsRx": "str",
        "functions": "",
        "functionsRx": "str",
        "device": "",
        "deviceRx": "str",
        "deviceName": "6fach Taster Flur EG",
        "deviceNameRx": "str",
        "deviceType": "",
        "deviceTypeRx": "str",
        "channel": "",
        "channelRx": "str",
        "channelName": "HmIP-WRC6 000B5A4992D97D:2",
        "channelNameRx": "str",
        "channelType": "",
        "channelTypeRx": "str",
        "channelIndex": "",
        "channelIndexRx": "str",
        "datapoint": "PRESS_SHORT",
        "datapointRx": "str",
        "change": false,
        "working": false,
        "cache": false,
        "topic": "${channelIndex}/${datapoint}",
        "x": 280,
        "y": 480,
        "wires": [
            [
                "a31e1cd1.2c522"
            ]
        ]
    },
    {
        "id": "38263145.35ea0e",
        "type": "ccu-connection",
        "z": "",
        "name": "localhost",
        "host": "localhost",
        "regaEnabled": true,
        "bcrfEnabled": true,
        "iprfEnabled": true,
        "virtEnabled": true,
        "bcwiEnabled": false,
        "cuxdEnabled": false,
        "regaPoll": true,
        "regaInterval": "30",
        "rpcPingTimeout": "60",
        "rpcInitAddress": "127.0.0.1",
        "rpcServerHost": "127.0.0.1",
        "rpcBinPort": "2047",
        "rpcXmlPort": "2048",
        "queueTimeout": "5000",
        "queuePause": "250",
        "contextStore": ""
    },
    {
        "id": "bfaad174.ed00a",
        "type": "redmatic-homekit-bridge",
        "z": "",
        "name": "RedMatic Homekit",
        "username": "CC:22:3D:EF:10:86",
        "pincode": "320-02-076",
        "port": "51826"
    }
]`

**Comment by TheBassfly** [comment]
[
    {
        "id": "fce0c19c.43d228",
        "type": "tab",
        "label": "Homekit",
        "disabled": false,
        "info": ""
    },
    {
        "id": "935e8d22.eb345",
        "type": "redmatic-homekit-homematic-devices",
        "z": "fce0c19c.43d228",
        "ccuConfig": "38263145.35ea0e",
        "bridgeConfig": "bfaad174.ed00a",
        "devices": {
            "0000DA499255AF:1": {
                "type": "Door",
                "disabled": false
            },
            "QEQ0094250:1": {
                "type": "Lightbulb",
                "disabled": false
            },
            "00085A49930C99:4": {
                "type": "Lightbulb",
                "disabled": false
            },
            "PEQ2221966:1": {
                "type": "Lightbulb",
                "disabled": false
            },
            "00085A49902209:4": {
                "type": "Lightbulb",
                "disabled": false
            },
            "PEQ2221765:1": {
                "type": "Lightbulb",
                "disabled": false
            }
        },
        "x": 900,
        "y": 480,
        "wires": []
    },
    {
        "id": "57d293ba.6fd1ec",
        "type": "redmatic-homekit-programmableswitch",
        "z": "fce0c19c.43d228",
        "bridgeConfig": "bfaad174.ed00a",
        "name": "KücheOff",
        "count": "1",
        "x": 500,
        "y": 420,
        "wires": []
    },
    {
        "id": "a31e1cd1.2c522",
        "type": "redmatic-homekit-programmableswitch",
        "z": "fce0c19c.43d228",
        "bridgeConfig": "bfaad174.ed00a",
        "name": "KücheOn",
        "count": "1",
        "x": 540,
        "y": 480,
        "wires": []
    },
    {
        "id": "67f2b1a8.831738",
        "type": "ccu-rpc-event",
        "z": "fce0c19c.43d228",
        "name": "",
        "iface": "HmIP-RF",
        "ccuConfig": "38263145.35ea0e",
        "rooms": "",
        "roomsRx": "str",
        "functions": "",
        "functionsRx": "str",
        "device": "",
        "deviceRx": "str",
        "deviceName": "6fach Taster Flur EG",
        "deviceNameRx": "str",
        "deviceType": "",
        "deviceTypeRx": "str",
        "channel": "",
        "channelRx": "str",
        "channelName": "HmIP-WRC6 000B5A4992D97D:1",
        "channelNameRx": "str",
        "channelType": "",
        "channelTypeRx": "str",
        "channelIndex": "",
        "channelIndexRx": "str",
        "datapoint": "PRESS_SHORT",
        "datapointRx": "str",
        "change": false,
        "working": false,
        "cache": false,
        "topic": "${channelIndex}/${datapoint}",
        "x": 280,
        "y": 420,
        "wires": [
            [
                "57d293ba.6fd1ec"
            ]
        ]
    },
    {
        "id": "9324106c.ffc55",
        "type": "ccu-rpc-event",
        "z": "fce0c19c.43d228",
        "name": "",
        "iface": "HmIP-RF",
        "ccuConfig": "38263145.35ea0e",
        "rooms": "",
        "roomsRx": "str",
        "functions": "",
        "functionsRx": "str",
        "device": "",
        "deviceRx": "str",
        "deviceName": "6fach Taster Flur EG",
        "deviceNameRx": "str",
        "deviceType": "",
        "deviceTypeRx": "str",
        "channel": "",
        "channelRx": "str",
        "channelName": "HmIP-WRC6 000B5A4992D97D:2",
        "channelNameRx": "str",
        "channelType": "",
        "channelTypeRx": "str",
        "channelIndex": "",
        "channelIndexRx": "str",
        "datapoint": "PRESS_SHORT",
        "datapointRx": "str",
        "change": false,
        "working": false,
        "cache": false,
        "topic": "${channelIndex}/${datapoint}",
        "x": 280,
        "y": 480,
        "wires": [
            [
                "a31e1cd1.2c522"
            ]
        ]
    },
    {
        "id": "38263145.35ea0e",
        "type": "ccu-connection",
        "z": "",
        "name": "localhost",
        "host": "localhost",
        "regaEnabled": true,
        "bcrfEnabled": true,
        "iprfEnabled": true,
        "virtEnabled": true,
        "bcwiEnabled": false,
        "cuxdEnabled": false,
        "regaPoll": true,
        "regaInterval": "30",
        "rpcPingTimeout": "60",
        "rpcInitAddress": "127.0.0.1",
        "rpcServerHost": "127.0.0.1",
        "rpcBinPort": "2047",
        "rpcXmlPort": "2048",
        "queueTimeout": "5000",
        "queuePause": "250",
        "contextStore": ""
    },
    {
        "id": "bfaad174.ed00a",
        "type": "redmatic-homekit-bridge",
        "z": "",
        "name": "RedMatic Homekit",
        "username": "CC:22:3D:EF:10:86",
        "pincode": "320-02-076",
        "port": "51826"
    }
]

**Comment by hobbyquaker** [comment]
Das Problem ist dass Du über den ChannelName auf Kanal :2 gefilter hast. Setze mal nur ein Filter auf Device und bei Datapoint die RegExp `PRESS_.*` - dann sollte es funktionieren.

**Comment by TheBassfly** [comment]
Naja, es geht ja im den Kanal 2.
Der Kanal 1 Funktioniert ja nur bei 2 reagiert nichts, oder verstehe ich da gerade im Umgang mit den Kanälen etwas falsch?

So, hab diesen Filter mal weg genommen. Jetzt wird der Trigger ausgelöst wenn ich den Taster 1 (Kanal 1) drücke aber bei zwei passiert immer noch nichts.

**Comment by hobbyquaker** [comment]
Ah ok, dann hab ich das falsch verstanden, ich dachte Du willst einen RPC Event Node für alle Tasten eines Gerätes nutzen. Wenn Du je Taste ein eigenen anlegst kannst/musst natürlich auf Kanal filtern. Dann würde ich aber umgekehrt dazu raten den Filter auf DeviceName zu löschen, es reicht wenn Du den Kanal eindeutig gefiltert hast, ist dann eine Bedingung weniger die Verarbeitet werden muss.
Nächster Schritt wäre mal mit einem Debug Node zu schauen ob da wirklich keine Nachricht rauskommt oder ob das Problem erst später im Flow zu tage tritt. Wenn wirklich keine Nachricht rauskommt müsstest das Loglevel mal auf Debug stellen und mir das Log zeigen (und vermerken zu welcher genauen Uhrzeit Du die Taste gedrückt hast). 
Beim Thema reportValueUsage/Dummy-Programm: nach dem anlegen eines Dummy-Programms müsste eine CONFIG_PENDING Servicemessage erscheinen ("Konfigurationsdaten stehen zur Übertragung an"). Erst wenn die Config vom WRC übernommen wurde und die Servicemeldung weg ist kann es dann funktionieren. War das der Fall?

**Comment by TheBassfly** [comment]
Also beim drücken der Taste kommt im Debug:

"invalid topic 2/PRESS_SHORT"

**Comment by TheBassfly** [comment]
> Beim Thema reportValueUsage/Dummy-Programm: nach dem anlegen eines Dummy-Programms müsste eine CONFIG_PENDING Servicemessage erscheinen ("Konfigurationsdaten stehen zur Übertragung an"). Erst wenn die Config vom WRC übernommen wurde und die Servicemeldung weg ist kann es dann funktionieren. War das der Fall?

Kann ich nicht konkret sagen. Aber die Taste löst ja was aus, weil ich ja aktuell ein Programm mit der Taste laufen habe, die eine virtuelle Taste in der CCU drückt. Das spielt auch. Knackpunkt hier ist immer wieder: Channel 1 (Egal ob WRC oder BidCos) wird erkannt. Alles was darüber hinausgeht nicht bzw bekommt diese Meldung oben.

**Comment by hobbyquaker** [comment]
Hmm, das "invalid topic" macht mich stutzig. Möglicherweise doch ein Bug, muss ich untersuchen. Log wäre dennoch hilfreich.

**Comment by TheBassfly** [comment]
Sehr gerne. Welches der Logs benötigst du denn?

**Comment by hobbyquaker** [comment]
Hmm, also wenn der Tastendruck im Debug Node ankommt dann ist RedMatic- bzw. node-red-contrib-ccu seitig erst mal alles iO. Lass mal die Config des Switch Nodes sehen bitte

**Comment by hobbyquaker** [comment]
Ah, ich glaub ich seh das Problem :-)
Bau den Flow mal um. Nimm __nur einen__ RPC Event Node für den WRC 6-Fachtaster. Konfigurier da nur ein Filter auf Device(Name) und auf Datapoint so dass er die Events aller 6 Tasten ausgibt. Dann schließt da __nur einen__ HomeKit Event Node an - konfigurierst bei dem aber 6 Tasten.

**Comment by hobbyquaker** [comment]
Oh - ich seh grad der HomeKit Event Node erlaubt keine 6 Tasten, nimm einfach erst mal 8. Ich reich eine Möglichkeit 6 Tasten zu konfigurieren mit dem nächsten Update nach.

**Comment by hobbyquaker** [comment]
Ah und noch eine Ergänzung. Wenn Du unbedingt ein eigenen Event Node für jede Taste nutzen willst geht das schon auch - da musst dann aber dafür sorgen dass das Topic immer mit `1/` beginnt, also im CCU RPC Event die Topickonfiguration von `${channelIndex}/${datapoint}` in `1/${datapoint}` ändern.

**Comment by TheBassfly** [comment]
[redmatic.2020-01-03T18_10_26.638Z.log](https://github.com/rdmtc/RedMatic/files/4020297/redmatic.2020-01-03T18_10_26.638Z.log)


Hier schonmal der Log. 
Deine Vorschlag funktioniert tatsächlich. Hat beim einrichten die Home App und Redmatic kurz zum Absturz gebracht aber jetzt läuft das so. Schonmal gut.
Aber für mein Verständnis:
Wenn ich jetzt Ikea Lampen mit dem Tradfri Node ansteuern will, benötige ich ja eigentlich pro Taste wieder einen RPC Node. Wie löse ich dann das? (Gerade wenn ich mit dem Long Press ja dann dimmen will).

**Comment by TheBassfly** [comment]
Ah okay. Gerade den Nachtrag gelesen. Danke für den Tip.

**Comment by hobbyquaker** [comment]
Wenn Du node-red-contrib-tradfri mit Homematic Tasten ansteuern willst wirst ein Konstrukt aus Change und evtl. Switch Nodes brauchen um `msg.payload` und u.U. `msg.topic` anzupassen. Da würde ich aber drum bitten bei Fragen dazu ein neuen Issue aufzumachen, ich mach den hier mal zu.

**Comment by DamianosS** [comment]
Ohne klugsch... zu wollen (bin eigentlich Anfänger), ich hab das so gelöst, vielleicht ist das irgendwie eine Hilfe, @TheBassfly ? Sind ein paar unterschiedliche Konzepte mit drin.
![Bild](https://user-images.githubusercontent.com/13657180/71743258-67205180-2e64-11ea-8ba0-670b042af187.jpg)

`[{"id":"a7ebbd73.c918d","type":"ccu-value","z":"6e3772a4.f70b4c","name":"#6 Short","iface":"HmIP-RF","channel":"000B5A499867B6:6 Wall Switch 06","datapoint":"PRESS_SHORT","mode":"","start":true,"change":true,"cache":false,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":160,"y":420,"wires":[[]]},{"id":"c9611cbb.50699","type":"hue-light","z":"6e3772a4.f70b4c","name":"Schreibtisch","bridge":"6a97fb71.89e304","lightid":"12","colornamer":true,"x":870,"y":300,"wires":[[]]},{"id":"a8102651.f44d08","type":"change","z":"6e3772a4.f70b4c","name":"Toggle light","rules":[{"t":"set","p":"payload","pt":"msg","to":"{}","tot":"json"},{"t":"set","p":"payload.toggle","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":470,"y":300,"wires":[["c9611cbb.50699"]]},{"id":"3a0528f5.509588","type":"ccu-value","z":"6e3772a4.f70b4c","name":"#5 Short","iface":"HmIP-RF","channel":"000B5A499867B6:5 Wall Switch 05","datapoint":"PRESS_SHORT","mode":"","start":true,"change":true,"cache":false,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":160,"y":360,"wires":[["8c60bf42.3c0ac"]]},{"id":"30271eb1.66fc32","type":"ccu-value","z":"6e3772a4.f70b4c","name":"#4 Short","iface":"HmIP-RF","channel":"000B5A499867B6:4 Wall Switch 04","datapoint":"PRESS_SHORT","mode":"","start":true,"change":true,"cache":false,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":160,"y":300,"wires":[["a8102651.f44d08"]]},{"id":"16e79a3a.746b26","type":"ccu-value","z":"6e3772a4.f70b4c","name":"#1 Short","iface":"HmIP-RF","channel":"000B5A499867B6:1 Wall Switch 01","datapoint":"PRESS_SHORT","mode":"","start":true,"change":true,"cache":false,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":160,"y":120,"wires":[["1932fb7d.42d775"]]},{"id":"889de75d.324378","type":"ccu-value","z":"6e3772a4.f70b4c","name":"#2 Short","iface":"HmIP-RF","channel":"000B5A499867B6:2 Wall Switch 02","datapoint":"PRESS_SHORT","mode":"","start":true,"change":true,"cache":false,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":160,"y":180,"wires":[["1932fb7d.42d775"]]},{"id":"7f2189c3.3855e8","type":"ccu-value","z":"6e3772a4.f70b4c","name":"#3 Short","iface":"HmIP-RF","channel":"000B5A499867B6:3 Wall Switch 03","datapoint":"PRESS_SHORT","mode":"","start":true,"change":true,"cache":false,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":160,"y":240,"wires":[["1f07f6da.403f89"]]},{"id":"2ff9dfe2.4d9b3","type":"ccu-value","z":"6e3772a4.f70b4c","name":"Blind Up/Down","iface":"HmIP-RF","channel":"00115A4998EE3E:4 HmIP-FROLL 00115A4998EE3E:4","datapoint":"LEVEL","mode":"","start":true,"change":false,"cache":false,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":1180,"y":120,"wires":[[]]},{"id":"c1bebc65.89e33","type":"change","z":"6e3772a4.f70b4c","name":"#1: Blind up","rules":[{"t":"set","p":"payload","pt":"msg","to":"1","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":890,"y":100,"wires":[["2ff9dfe2.4d9b3"]]},{"id":"f9ac3630.999938","type":"ccu-value","z":"6e3772a4.f70b4c","name":"Blind Stop","iface":"HmIP-RF","channel":"00115A4998EE3E:4 HmIP-FROLL 00115A4998EE3E:4","datapoint":"STOP","mode":"","start":true,"change":true,"cache":false,"queue":false,"on":0,"onType":"undefined","ramp":0,"rampType":"undefined","working":false,"ccuConfig":"38263145.35ea0e","topic":"${CCU}/${Interface}/${channel}/${datapoint}","x":650,"y":160,"wires":[[]]},{"id":"3491d8a0.358b78","type":"switch","z":"6e3772a4.f70b4c","name":"which button pressed?","property":"channelIndex","propertyType":"msg","rules":[{"t":"eq","v":"1","vt":"num"},{"t":"eq","v":"2","vt":"num"}],"checkall":"false","repair":false,"outputs":2,"x":680,"y":120,"wires":[["c1bebc65.89e33"],["4404f7ac.049308"]]},{"id":"4404f7ac.049308","type":"change","z":"6e3772a4.f70b4c","name":"#2: Blind down","rules":[{"t":"set","p":"payload","pt":"msg","to":"0","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":900,"y":140,"wires":[["2ff9dfe2.4d9b3"]]},{"id":"1932fb7d.42d775","type":"ccu-switch","z":"6e3772a4.f70b4c","name":"get blind working state","ccuConfig":"38263145.35ea0e","iface":"HmIP-RF","channel":"00115A4998EE3E:4 HmIP-FROLL 00115A4998EE3E:4","sysvar":"Alarmmeldungen","sysvarProperty":"value","datapoint":"ACTIVITY_STATE","datapointProperty":"working","property":"payload","propertyType":"msg","rules":[{"t":"false"},{"t":"true"}],"checkall":"false","repair":false,"outputs":2,"x":400,"y":140,"wires":[["3491d8a0.358b78"],["f9ac3630.999938"]]},{"id":"1f07f6da.403f89","type":"change","z":"6e3772a4.f70b4c","name":"Toggle light","rules":[{"t":"set","p":"payload","pt":"msg","to":"{}","tot":"json"},{"t":"set","p":"payload.toggle","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":350,"y":240,"wires":[["4fdc3c63.96d3a4"]]},{"id":"4fdc3c63.96d3a4","type":"hue-light","z":"6e3772a4.f70b4c","name":"Office Floor Light","bridge":"6a97fb71.89e304","lightid":"17","colornamer":true,"x":550,"y":240,"wires":[[]]},{"id":"8c60bf42.3c0ac","type":"function","z":"6e3772a4.f70b4c","name":"Set Payload = TOGGLE","func":"msg.payload = \"TOGGLE\";\nreturn msg;","outputs":1,"noerr":0,"x":510,"y":360,"wires":[["4c090ea7.ebbd9"]]},{"id":"4c090ea7.ebbd9","type":"mqtt out","z":"6e3772a4.f70b4c","name":"","topic":"fgg/firstfloor/officeroom/OfficeRoomMainLight/cmnd/POWER","qos":"2","retain":"","broker":"cc35da64.c37bc8","x":900,"y":360,"wires":[]},{"id":"ff0e5967.232e78","type":"comment","z":"6e3772a4.f70b4c","name":"Office Room","info":"","x":110,"y":80,"wires":[]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":true,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","queueTimeout":"5000","queuePause":"250","contextStore":""},{"id":"6a97fb71.89e304","type":"hue-bridge","z":"","name":"Philips hue","bridge":"192.168.0.37","key":"dQFjNHzPQcW5IUEFkW6yr876nTgznqT1Bz4c6uZQ","interval":"3000"},{"id":"cc35da64.c37bc8","type":"mqtt-broker","z":"","name":"Mosquito running on CCU3","broker":"192.168.0.100","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]`
