### ISSUE TITLE
Fehlerhafte Darstellung in der Funktions-Node bei der Theme "midnight red"....

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/RedMatic#303]
Hallo Hobbyquaker,

durch Zufall habe ich folgendes festgestellt.

Wenn ich die Theme: midnight-red aktiviert habe dann habe ich in der "function Node" eine fehlerhafte Darstellung der Cursorposition. Ich schreibe z.B. "Thomas_geht_nach_Hause" dann zeigt er auf dem Bildschirm so etwas an: "Thomas_geht_nach_Ha|use" wobei der "|" die Cursorposition ist. Wird in "If" Funktionen echt unübersichtlich.

Sobald ich die Theme auf "Standard" stelle ist alles wieder ok.

Gruß Thomas

**Comment by hobbyquaker** [comment]
Da würde ich Dich bitten hier ein Issue dafür aufzumachen: https://github.com/bonanitech/node-red-contrib-theme-midnight-red/issues
