### ISSUE TITLE
Debug output steht nicht in /var/log/messages

### ISSUE THREAD

**Issue by jogi4github** [rdmtc/RedMatic#309]
Hallo,

leider konnte ich keine Hinweis finden, wie ich von mir in Flows gesetzte Debug Infomationen in die Logdatei schreiben lassen kann. Wenn ich die Node-Red Doku hier richtig verstehe, sollte es ausreichen, den metric Wert in der settings.json Datei auf true zu setzen. Genau das habe ich gemacht, nur leider Erfolg. Der Debug Level scheint auch keine Lösung hierfür zu sein, da er zu viel Informationen die Logdatei schreibt und diese somit sehr schnell rotiert wird.
Zur Info meine Redmatic Installation läuft in einer Homemetic pivccu LXC Umgebung auf einem Raspberry PI 3B.
Mich wundert etwas, dass ich überhaupt keine Hinweise in den Foren und/oder auf GitHub hierzu gefunden habe. Ich bin davon ausgegangen, dass Debug Informationen, grundsätzlich von Interesse sind und nicht nur zur Laufzeit. Im Augenblick kann ich die Debugnachrichten ausschließlich zur Laufzeit analysieren. Mache ich hier einen riesigen Denkfehler, oder fehlt das Umsetzen dieser Funktion in RedMatic (oder liegt es an meiner pivccu Installation...???)

Viele Grüße
   Jörg

**Comment by hobbyquaker** [comment]
Du meinst das was der _Debug_ Node in der Sidebar ausgeben? Das landet nicht im Logfile. Wenn Du aus einem Flow heraus ins Logfile loggen willst könntest mit einem _File_ Node einfach was an die Datei anhängen oder mit einem _Exec_ Node den "logger" aufrufen.

**Comment by Hypnos3** [comment]
Die Debug Node hat auch eine extra Option das mit ins Log aufzunehmen (diese ist standardmäßig nicht ausgewählt).

**Comment by Sineos** [comment]
Well, according to the NR documentation it should:

https://github.com/node-red/node-red/blob/504d13943df699e53faa8cd21ec8c2743d188521/packages/node_modules/node-red/settings.js#L262

https://nodered.org/docs/user-guide/runtime/logging#metrics

**Comment by jogi4github** [comment]
@Hypnos3 Vielen Dank für die Info zur Debug Node. Sobald ich den Haken "to system console" setze funktioniert auch das Logging in das message Logfile.

**Comment by jogi4github** [comment]
Aus meiner Sicht kann das Issue geschlossen werden. Die Rückmeldung von Hypnos3 beschreibt eindeutig die Lösung meiner Anfrage.
