### ISSUE TITLE
RedMatik in der OVA-Version

### ISSUE THREAD

**Issue by HMelzer** [rdmtc/RedMatic#315]
In der Übersicht zu Redmatic ist zu lesen, dass eine OVA-Version (noch) nicht unterstützt wird.
Wann wäre denn eventuell damit zu rechnen?

**Comment by Sineos** [comment]
Siehe https://homematic-forum.de/forum/viewtopic.php?f=77&t=55267&sid=b6a1c5a1533d42884b021106d80a7789#p549659

**Comment by hobbyquaker** [comment]
#273
