### ISSUE TITLE
Intel NUC

### ISSUE THREAD

**Issue by garosp** [rdmtc/RedMatic#322]
Hallo,
danke für die super Arbeit.

Ich überlege die Hardware zu wechseln.
Intel Nuc mit Proxmox und RaspberryMatic-ova Image wäre die Idee.  (aber nicht ohne Redmatic ;-).
Du schreibst es wird "noch nicht" unterstützt. Ist da was in der Pipeline ?

Könnte ich den Redmatic-Part auf einem zweiten Node-Red System betreiben am besten auch virtualisiert ? Gibt es dazu Anmerkungen - hat das schon jemand versucht ?  
Habe dazu nichts gefunden

Danke für jeden Kommentar

**Comment by hobbyquaker** [comment]
Ist in der Mache, muss nur noch um ein "bisschen" Geduld bitten.

Dup #273

**Comment by garosp** [comment]
Hallo,

alles gut, wollte nur wissen wie Du zu dem Thema stehst.

Nochmals Danke für deine Super-Arbeit.

VG

 

 

Von: Sebastian Raff <notifications@github.com> 
Gesendet: Donnerstag, 5. März 2020 19:39
An: rdmtc/RedMatic <RedMatic@noreply.github.com>
Cc: Domotics <roland@familie-spitzer.de>; Author <author@noreply.github.com>
Betreff: Re: [rdmtc/RedMatic] Intel NUC (#322)

 

Ist in der Mache, muss nur noch um ein "bisschen" Geduld bitten.

Dup #273 <https://github.com/rdmtc/RedMatic/issues/273>
