### ISSUE TITLE
Smartmeter CRC ignorieren

### ISSUE THREAD

**Issue by Jemeins** [rdmtc/RedMatic#323]
Moin,

ist es möglich im Smartmeter Plugin die CRC checksum zu ignorieren?
Eventuell in der Konfiguration mit einer Checkbox?
Bei meinem Zähler (Holley DTZ541) gibt es Bekannterweise CRC Fehler.

Mit freundlichen Grüßen

**Comment by Hypnos3** [comment]
Hier geht es doch um die extra Node [node-red-contrib-smartmeter]( https://github.com/coolchip/node-red-contrib-smartmeter), wäre es da nicht besser angebracht auch zu dieser Node den Wunsch zu äußern?

**Comment by Jemeins** [comment]
Ich konnte mein Problem anderweitig lösen, trotzdem vielen Dank :)
