### ISSUE TITLE
[Doku] Context-Storage - Wert 30

### ISSUE THREAD

**Issue by Subnum12** [rdmtc/RedMatic#324]
In der [Doku](https://github.com/rdmtc/RedMatic/wiki/Context-Storage) ist die Variable "30" leider nirgends beschreiben. 
Werden bis zu 30 Paremeter im RAM gehalten, wird nach 30s/Min. in das File geschreiben...?

**Comment by hobbyquaker** [comment]
Das ist der Intervall in Sekunden wie oft der Context auf den Datenträger geschrieben wird.

**Comment by Subnum12** [comment]
Danke!

**Comment by hobbyquaker** [comment]
ich mach den noch mal auf um nicht zu vergessen dass hier die Doku noch vervollständigt werden muss

**Comment by Subnum12** [comment]
hatte ich doch schon nachgetragen ;-)

**Comment by hobbyquaker** [comment]
ah, top, danke :)
