### ISSUE TITLE
node-red-contrib-ui-artless-gauge

### ISSUE THREAD

**Issue by marowsky** [rdmtc/RedMatic#328]
Die Value Farbe ist in RedMatic unsichtbar.
In Node-RED funkioniert es. Gibt es eine Lösung?

![Anmerkung 2020-03-14 150720](https://user-images.githubusercontent.com/15909379/76687751-3fe5bd80-6627-11ea-9e49-45f4a86aec0b.jpg)

**Comment by djiwondee** [comment]
Hallo @marowsky 
mal eine Frage nebenbei: wo sind denn die schicken Gauge-Diagramme her?

**Comment by SirBrendan** [comment]
Hallo. Kann den Fehler mit der nicht sichtbaren Farbe bestätigen (habe ich genau so).

Darüber hinaus führen auch andere Animationen in Anzeigen zu Fehlverhalten: Bei node-red-contrib-ui-level funktioniert die Anzeige nur noch, wenn man die Animationen ausschaltet. Jede andere Auswahl (soft, rective oder rocket) führt zu einer eingefrorenen Anzeige mit hohen maximalen Werten:
![Beispiel 1](https://user-images.githubusercontent.com/62263267/76796361-883de080-67cb-11ea-9f29-a43e64027361.jpg)

Hat vielleicht was damit zu tun? Habe auch erst vor ein paar Tagen das Update durchgeführt. Vorher keine Probleme damit gehabt (weiß aber gerade nicht mehr welche Version, sorry, aber schon was älter ~2 Monate?).

Das ist mein erster Post hier (Frischling), also Entschuldigung, falls ich mich blöd anstelle.

**Comment by SirBrendan** [comment]
So, nachdem ich mal ein Blick auf meine installierten Module in der Palette geworfen habe und ein Update aller möglichen Module durchgeführt habe, funktionieren beide o.g. Grafiken wieder nach einem Neustart von RedMatic, als ob nichts gewesen wäre (also node-red-contrib-ui-artless-gauge & node-red-contrib-ui-level).
@marowsky : Vielleicht auch mal probieren?

**Comment by marowsky** [comment]
Problem ist gelöst. 
Mit der Version "node-red-contrib-ui-artless-gauge 0.1.24" gerade probiert. Alles Bestens.
Vielen Dank für die gute Arbeit. ;-)
