### ISSUE TITLE
RedMatic für Debmatic ein Traum 

### ISSUE THREAD

**Issue by AndynordSee** [rdmtc/RedMatic#330]
Moin,

bin schon seit längerem begeistert von deinem Addon, vielen Dank für dein Arbeit.
Würde mich sehr freuen wenn es möglich wäre dein Addon unter Debmatic nutzen zu können. 
Mir ist der weg über Node-RED mit node-red-contrib-ccu bewust.
Denke aber das man so Redmatic einer viel größere Nutzerschaft zugänglich machen könnte.

Ich würde mich echt sehr freuen, den mit der Debmatic und CUXD und deiner Redmatic wäre ja quasi eine Performante Zentrale für Homematic möglich.

**Comment by hobbyquaker** [comment]
Da kann ich Dir (stand heute) keine Hoffnung machen. Ein Umbau von RedMatic als .deb halte ich nicht für sinnvoll, ich glaube auch nicht dass die Zielgruppe wirklich groß ist (siehe dazu die Tabelle "CCU Products" hier: https://telemetry.redmatic.de/#90 - piVCCU und die RaspberryMatic "ova" Variante sind im Subprozentbereich. Ich empfehl Dir (insofern Debmatic gesetzt ist) einfach Node-RED - ohne RedMatic - selbst zu managen.
