### ISSUE TITLE
Möglichkeit zum Suchen / Ersetzen von Text

### ISSUE THREAD

**Issue by JoeWiseman** [rdmtc/RedMatic#339]
Hallo zusammen,

ich bin noch relativ neu bei RedMatic, bin aber jetzt schon begeistert von der Art des Programmierens. Manchmal muss man zwar etwas um die Ecke denken, aber die Einbindung von irgendwelchen http-Geräten und MQTT-Geräten finde ich super einfach gelöst.
Als alter CCU2-Nutzer habe ich mich immer wieder über die umständliche Art der Programmierung über das WebUI der HM-Steuerung "geärgert".

_Zu eigentlichen Thema:_ 
Da man sich manchmal überlegt Variablen umzubenennen (dabei kann man ja bei den Nodes durch Einfügen eines Punktes auch Datenstrukturen erzeugen) wäre es super, wenn es so eine Funktion: "Suchen und Ersetzen" gäbe.
Jetzt muss man wirklich noch alle Nodes einzeln abklappern und die Daten manuell umbenennen.

_Eine andere Frage habe ich auch noch:_ 
Wenn ich Nodes selektiere kann ich diese ja über Exportieren als Text in die Zwischenablage kopieren. Füge ich diese dann in Notepad++ (oder einen anderen Editor) ein, so steht alles in einer Zeile.
Im Netz habe ich für _Node-Red_ unter:
  https://discourse.nodered.org/t/not-required-now-editing-my-flow-json-file-manually/2490/7
gefunden, dass man über die Einstellung:
  flowFilePretty: true,
  in der settings.js
den Zeilenumbruch "einfügen" kann.
Geht so etwas in RedMatic dann auch, oder gibt es einen geeigneten Editor, der eigenständig die Zeilenumbrüche setzt?

Viele Grüße

**Comment by Hypnos3** [comment]
Beim exportieren von nodes kann man doch wählen (schmale Buttons) ob das formatiert werden soll oder nicht.

Für größeres Suchen und ersetzen kann man sich mittels ssh mit der HomeMatic verbinden und die flow.json (Node-RED vorher stoppen und Sicherungskopie anlegen) mit einem Texteditor bearbeiten. Man sollte aber wissen was man da macht. Alternativ kannst du die Frage ja auch mal im Node Red Forum https://discourse.nodered.org/ stellen.

**Comment by JoeWiseman** [comment]
Vielen Dank für die Antwort!  Den Button mit dem formatiert oder nicht hatte ich gar nicht gesehen ....
... und für das Ersetzen von Zeichenketten über eine SSH-Schnittstelle und dann das ändern - am besten noch mit dem "vi" :-D  sollte doch heutzutage auch geschmeidiger zu lösen sein....

Viellecht findet diese Anregung ja doch einmal Gehör und wird als Feature implementiert?!

Viele Grüße

**Comment by hobbyquaker** [comment]
Das müsstest dann mal im Node-RED [Slack](https://nodered.org/slack/) oder [Forum](https://discourse.nodered.org/) als Featurewunsch äußern.

**Comment by JoeWiseman** [comment]
Danke für den Hinweis. Ich werde mich da mal anmelden und den Vorschlag posten. Ich tippe mal, dass ich nicht der einzige bin, der so eine Funktion nützlich finden würde ;-)
Viele Grüße & Danke nochmals für die Anworten!
