### ISSUE TITLE
Redmatic Update 5.3.9 -> 5.5.3 schlägt fehl: CCU3 stürzt ab

### ISSUE THREAD

**Issue by tgmann** [rdmtc/RedMatic#349]
Update auf 5.5.3: beim Installieren auf stürzt CCU3 ab, Medlung im Webinterface das diverse Komponenten nicht mehr reagieren. Nach Neustart ernuet versucht, auch wieder 5.3.9 drüber installieren: gleiches Ergebnis.

Das Starten von RedMatic ist seitdem auch nciht mehr möglich.

`
{
   "ccu": {
      "VERSION": "3.51.6",
      "PRODUCT": "ccu3",
      "PLATFORM": "rpi3"
   },
   "redmatic": "5.3.9",
   "nodejs": null,
   "ain2": "3.0.0",
   "node-red": "1.0.3",
   "node-red-contrib-theme-midnight-red": "1.0.24",
   "node-red-node-sqlite": "0.4.1",
   "npm": "6.13.4",
   "node-red-contrib-advanced-ping": "1.2.0",
   "node-red-contrib-ccu": "3.1.4",
   "node-red-contrib-combine": "1.8.1",
   "node-red-contrib-deconz": "1.1.9",
   "node-red-contrib-moment": "3.0.3",
   "node-red-contrib-mqtt-json": "1.0.1",
   "node-red-contrib-statistics": "2.2.2",
   "node-red-contrib-sun-position": "1.0.1",
   "node-red-contrib-telegrambot": "8.1.0",
   "node-red-contrib-tplink-smarthome": "0.1.1",
   "node-red-contrib-tradfri": "1.2.0",
   "node-red-dashboard": "2.19.3",
   "node-red-node-email": "1.7.3",
   "node-red-node-rbe": "0.2.6",
   "node-red-node-smooth": "0.1.2",
   "redmatic-led": "1.1.0",
   "redmatic-webapp": "0.3.1"
}
Segmentation fault

Apr 10 20:53:07
Package node-red-node-serialport update 0.7.0 to 0.8.0
Get https://github.com/rdmtc/RedMatic/releases/download/v4.1.0/redmatic-pkg-node-red-node-serialport-0.8.0.tar.gz
Extracting node-red-node-serialport.tar.gz
Done.
Package node-red-node-sqlite 0.3.6 is up-to-date
Package node-red-contrib-smartmeter update 0.2.0 to 0.2.1
Get https://github.com/rdmtc/RedMatic/releases/download/v4.1.0/redmatic-pkg-node-red-contrib-smartmeter-0.2.1.tar.gz
Extracting node-red-contrib-smartmeter.tar.gz
Done.
Package node-red-contrib-modbus update 4.1.1 to 4.1.3
Get https://github.com/rdmtc/RedMatic/releases/download/v4.1.0/redmatic-pkg-node-red-contrib-modbus-4.1.3.tar.gz
Extracting node-red-contrib-modbus.tar.gz
Done.
Package node-red-contrib-mysensors update 3.2.0 to 3.3.0
Get https://github.com/rdmtc/RedMatic/releases/download/v4.1.0/redmatic-pkg-node-red-contrib-mysensors-3.3.0.tar.gz
Extracting node-red-contrib-mysensors.tar.gz
Done.
Package redmatic-homekit update 1.9.1 to 2.1.2
Get https://github.com/rdmtc/RedMatic/releases/download/v4.1.0/redmatic-pkg-redmatic-homekit-2.1.2.tar.gz
Extracting redmatic-homekit.tar.gz
Done.
Jul 28 11:19:05
Package node-red-node-serialport update 0.8.0 to 0.8.3
Get https://github.com/rdmtc/RedMatic/releases/download/v4.7.1/redmatic-pkg-node-red-node-serialport-0.8.3.tar.gz
Downloaded 470K in 2 seconds
File integrity check successful
Extracting node-red-node-serialport.tar.gz
Done.
Package node-red-node-sqlite update 0.3.6 to 0.3.7
Get https://github.com/rdmtc/RedMatic/releases/download/v4.7.1/redmatic-pkg-node-red-node-sqlite-0.3.7.tar.gz
Downloaded 6M in 5 seconds
File integrity check failed
  Expected sha512-+72VcTcG4GxeD77WGO1GDj9VQWfj7/DneX1IBlE0inNd/Wseii/qDzo4V26t5Vuz49nBFGOyBne8Pnv+1dPybg==
  Got      sha512-42SLijIT7fMOjXwlXDT8vGkpfPIxFeSNpAh/PRx01k/Frx10t+kNve5VvnbfFd0duKxe6yh4ZzhjKe2hBzUcog==
Error: Install failed.
Package node-red-contrib-smartmeter 0.2.1 is up-to-date
Package node-red-contrib-modbus 4.1.3 is up-to-date
Package node-red-contrib-mysensors 3.3.0 is up-to-date
Package redmatic-homekit update 2.1.2 to 2.3.3
Get https://github.com/rdmtc/RedMatic/releases/download/v4.7.1/redmatic-pkg-redmatic-homekit-2.3.3.tar.gz
Downloaded 17M in 12 seconds
File integrity check successful
Extracting redmatic-homekit.tar.gz
Done.

Jul 28 11:52:52
Package node-red-node-serialport 0.8.3 is up-to-date
Package node-red-node-sqlite update 0.3.6 to 0.3.7
Get https://github.com/rdmtc/RedMatic/releases/download/v4.7.1/redmatic-pkg-node-red-node-sqlite-0.3.7.tar.gz
Downloaded 6M in 33 seconds
File integrity check failed
  Expected sha512-+72VcTcG4GxeD77WGO1GDj9VQWfj7/DneX1IBlE0inNd/Wseii/qDzo4V26t5Vuz49nBFGOyBne8Pnv+1dPybg==
  Got      sha512-42SLijIT7fMOjXwlXDT8vGkpfPIxFeSNpAh/PRx01k/Frx10t+kNve5VvnbfFd0duKxe6yh4ZzhjKe2hBzUcog==
Error: Install failed.
Package node-red-contrib-smartmeter 0.2.1 is up-to-date
Package node-red-contrib-modbus 4.1.3 is up-to-date
Package node-red-contrib-mysensors 3.3.0 is up-to-date
Package redmatic-homekit 2.3.3 is up-to-date

Aug 01 09:50:24
Package node-red-node-serialport 0.8.3 is up-to-date
Package node-red-node-sqlite update 0.3.6 to 0.3.7
Get https://github.com/rdmtc/RedMatic/releases/download/v4.7.1/redmatic-pkg-node-red-node-sqlite-0.3.7.tar.gz
Downloaded 6M in 4 seconds
File integrity check failed
  Expected sha512-+72VcTcG4GxeD77WGO1GDj9VQWfj7/DneX1IBlE0inNd/Wseii/qDzo4V26t5Vuz49nBFGOyBne8Pnv+1dPybg==
  Got      sha512-42SLijIT7fMOjXwlXDT8vGkpfPIxFeSNpAh/PRx01k/Frx10t+kNve5VvnbfFd0duKxe6yh4ZzhjKe2hBzUcog==
Error: Install failed.
Package node-red-contrib-smartmeter 0.2.1 is up-to-date
Package node-red-contrib-modbus 4.1.3 is up-to-date
Package node-red-contrib-mysensors 3.3.0 is up-to-date
Package redmatic-homekit 2.3.3 is up-to-date

Aug 13 09:29:55
Package node-red-node-serialport 0.8.3 is up-to-date
Package node-red-node-sqlite update 0.3.6 to 0.3.7
Get https://github.com/rdmtc/RedMatic/releases/download/v4.7.1/redmatic-pkg-node-red-node-sqlite-0.3.7.tar.gz
Downloaded 6M in 4 seconds
File integrity check failed
  Expected sha512-+72VcTcG4GxeD77WGO1GDj9VQWfj7/DneX1IBlE0inNd/Wseii/qDzo4V26t5Vuz49nBFGOyBne8Pnv+1dPybg==
  Got      sha512-42SLijIT7fMOjXwlXDT8vGkpfPIxFeSNpAh/PRx01k/Frx10t+kNve5VvnbfFd0duKxe6yh4ZzhjKe2hBzUcog==
Error: Install failed.
Package node-red-contrib-smartmeter 0.2.1 is up-to-date
Package node-red-contrib-modbus 4.1.3 is up-to-date
Package node-red-contrib-mysensors 3.3.0 is up-to-date
Package redmatic-homekit 2.3.3 is up-to-date

Aug 13 18:02:53
Package node-red-node-serialport 0.8.3 is up-to-date
Package node-red-node-sqlite update 0.3.6 to 0.3.7
Get https://github.com/rdmtc/RedMatic/releases/download/v4.7.1/redmatic-pkg-node-red-node-sqlite-0.3.7.tar.gz
Downloaded 6M in 5 seconds
File integrity check failed
  Expected sha512-+72VcTcG4GxeD77WGO1GDj9VQWfj7/DneX1IBlE0inNd/Wseii/qDzo4V26t5Vuz49nBFGOyBne8Pnv+1dPybg==
  Got      sha512-42SLijIT7fMOjXwlXDT8vGkpfPIxFeSNpAh/PRx01k/Frx10t+kNve5VvnbfFd0duKxe6yh4ZzhjKe2hBzUcog==
Error: Install failed.
Package node-red-contrib-smartmeter 0.2.1 is up-to-date
Package node-red-contrib-modbus 4.1.3 is up-to-date
Package node-red-contrib-mysensors 3.3.0 is up-to-date
Package redmatic-homekit 2.3.3 is up-to-date

Aug 16 20:22:44
Package node-red-node-serialport 0.8.3 is up-to-date
Package node-red-node-sqlite update 0.3.6 to 0.3.7
Get https://github.com/rdmtc/RedMatic/releases/download/v4.7.1/redmatic-pkg-node-red-node-sqlite-0.3.7.tar.gz
Downloaded 6M in 4 seconds
File integrity check failed
  Expected sha512-+72VcTcG4GxeD77WGO1GDj9VQWfj7/DneX1IBlE0inNd/Wseii/qDzo4V26t5Vuz49nBFGOyBne8Pnv+1dPybg==
  Got      sha512-42SLijIT7fMOjXwlXDT8vGkpfPIxFeSNpAh/PRx01k/Frx10t+kNve5VvnbfFd0duKxe6yh4ZzhjKe2hBzUcog==
Error: Install failed.
Package node-red-contrib-smartmeter 0.2.1 is up-to-date
Package node-red-contrib-modbus 4.1.3 is up-to-date
Package node-red-contrib-mysensors 3.3.0 is up-to-date
Package redmatic-homekit 2.3.3 is up-to-date

Oct 02 22:33:09
Package node-red-node-serialport 0.8.3 is up-to-date
Package node-red-node-sqlite update 0.3.6 to 0.3.7
Get https://github.com/rdmtc/RedMatic/releases/download/v4.7.1/redmatic-pkg-node-red-node-sqlite-0.3.7.tar.gz
Downloaded 6M in 34 seconds
File integrity check failed
  Expected sha512-+72VcTcG4GxeD77WGO1GDj9VQWfj7/DneX1IBlE0inNd/Wseii/qDzo4V26t5Vuz49nBFGOyBne8Pnv+1dPybg==
  Got      sha512-42SLijIT7fMOjXwlXDT8vGkpfPIxFeSNpAh/PRx01k/Frx10t+kNve5VvnbfFd0duKxe6yh4ZzhjKe2hBzUcog==
Error: Install failed.
Package node-red-contrib-smartmeter 0.2.1 is up-to-date
Package node-red-contrib-modbus 4.1.3 is up-to-date
Package node-red-contrib-mysensors 3.3.0 is up-to-date
Package redmatic-homekit 2.3.3 is up-to-date

Oct 18 19:16:57
Package node-red-node-serialport update 0.8.3 to 0.8.8
Get https://github.com/rdmtc/RedMatic/releases/download/v5.0.5/redmatic-pkg-node-red-node-serialport-0.8.8.tar.gz
Downloaded 533K in 1 seconds
File integrity check successful
Extracting node-red-node-serialport.tar.gz
Done.
Package node-red-node-sqlite update 0.3.6 to 0.4.0
Get https://github.com/rdmtc/RedMatic/releases/download/v5.0.5/redmatic-pkg-node-red-node-sqlite-0.4.0.tar.gz
Downloaded 6M in 5 seconds
File integrity check successful
Extracting node-red-node-sqlite.tar.gz
Done.
Package node-red-contrib-smartmeter 0.2.1 is up-to-date
Package node-red-contrib-modbus 4.1.3 is up-to-date
Package node-red-contrib-mysensors 3.3.0 is up-to-date
Package redmatic-homekit update 2.3.3 to 2.4.2
Get https://github.com/rdmtc/RedMatic/releases/download/v5.0.5/redmatic-pkg-redmatic-homekit-2.4.2.tar.gz
Downloaded 16M in 12 seconds
File integrity check successful
Extracting redmatic-homekit.tar.gz
Oct 18 19:17:38
Package node-red-node-serialport 0.8.8 is up-to-date
Package node-red-node-sqlite 0.4.0 is up-to-date
Package node-red-contrib-smartmeter 0.2.1 is up-to-date
Package node-red-contrib-modbus 4.1.3 is up-to-date
Package node-red-contrib-mysensors 3.3.0 is up-to-date
Get https://github.com/rdmtc/RedMatic/releases/download/v5.0.5/redmatic-pkg-redmatic-homekit-2.4.2.tar.gz
gzip: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Error: Install failed.

Downloaded 16M in 28 seconds
File integrity check successful
Extracting redmatic-homekit.tar.gz
Done.

Nov 02 23:38:27
Package node-red-node-serialport 0.8.8 is up-to-date
Package node-red-node-sqlite 0.4.0 is up-to-date
Package node-red-contrib-smartmeter 0.2.1 is up-to-date
Package node-red-contrib-modbus 4.1.3 is up-to-date
Package node-red-contrib-mysensors 3.3.0 is up-to-date
Package redmatic-homekit update 2.4.2 to 2.6.0
Get https://github.com/rdmtc/RedMatic/releases/download/v5.2.0/redmatic-pkg-redmatic-homekit-2.6.0.tar.gz
Downloaded 16M in 12 seconds
File integrity check successful
Extracting redmatic-homekit.tar.gz
Done.

Nov 26 15:05:58
Package node-red-node-serialport update 0.8.8 to 0.9.1
Get https://github.com/rdmtc/RedMatic/releases/download/v5.2.3/redmatic-pkg-node-red-node-serialport-0.9.1.tar.gz
Downloaded 531K in 2 seconds
File integrity check successful
Extracting node-red-node-serialport.tar.gz
Done.
Package node-red-node-sqlite update 0.4.0 to 0.4.1
Get https://github.com/rdmtc/RedMatic/releases/download/v5.2.3/redmatic-pkg-node-red-node-sqlite-0.4.1.tar.gz
Downloaded 6M in 6 seconds
File integrity check successful
Extracting node-red-node-sqlite.tar.gz
Done.
Package node-red-contrib-smartmeter update 0.2.1 to 0.2.2
Get https://github.com/rdmtc/RedMatic/releases/download/v5.2.3/redmatic-pkg-node-red-contrib-smartmeter-0.2.2.tar.gz
Downloaded 2M in 3 seconds
File integrity check successful
Extracting node-red-contrib-smartmeter.tar.gz
Done.
Package node-red-contrib-modbus 4.1.3 is up-to-date
Package node-red-contrib-mysensors 3.3.0 is up-to-date
Package redmatic-homekit update 2.6.0 to 2.6.3
Get https://github.com/rdmtc/RedMatic/releases/download/v5.2.3/redmatic-pkg-redmatic-homekit-2.6.3.tar.gz
Downloaded 16M in 18 seconds
File integrity check successful
Extracting redmatic-homekit.tar.gz
Done.

Jan 05 19:48:48
Package node-red-node-sqlite 0.4.1 is up-to-date
Package node-red-contrib-mysensors update 3.3.0 to 3.3.1
Get https://github.com/rdmtc/RedMatic/releases/download/v5.3.6/redmatic-pkg-node-red-contrib-mysensors-3.3.1.tar.gz
Downloaded 7M in 6 seconds
File integrity check successful
Extracting node-red-contrib-mysensors.tar.gz
Done.

Jan 08 20:24:06
Package node-red-node-sqlite 0.4.1 is up-to-date
Package node-red-contrib-mysensors 3.3.1 is up-to-date

May 03 23:33:54
/usr/local/addons/redmatic/bin/jq: error while loading shared libraries: libjq.so.1: cannot open shared object file: No such file or directory

May 03 23:45:40
/usr/local/addons/redmatic/bin/jq: error while loading shared libraries: libjq.so.1: cannot open shared object file: No such file or directory

May 04 00:01:21
Package node-red-node-sqlite 0.4.1 is up-to-date

May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (84339/2147483647)
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (92290/2147483647)
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (84340/2147483647)
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (92291/2147483647)
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (84341/2147483647)
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (92292/2147483647)
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (84342/2147483647)
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (92293/2147483647)
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (84343/2147483647)
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (92294/2147483647)
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (84344/2147483647)
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (92295/2147483647)
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (84345/2147483647)
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (92296/2147483647)
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (92297/2147483647)
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (84346/2147483647)
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (92298/2147483647)
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (84347/2147483647)
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (84348/2147483647)
May  4 00:26:04 ccu3-webui daemon.warn redmatic: Restarting Node-RED (92299/2147483647)
May  4 00:26:04 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139
`

**Comment by Sineos** [comment]
Schonmal den "Safe Mode" probiert, bzw. auch das Logging auf "Debug". So gibt das Log nicht viel her.

Vor allem würde ich mal probieren das SQLite Paket zu deaktivieren.

**Comment by tgmann** [comment]
Vielen Dank für die Hinweise. 
Log war mit "Debug" erzeugt. Safe mode half auch nicht. Am Ende habe ich einen Factory reset auf der CCU3 gemacht und Backup eingespielt. Jetzt läuft wieder alles wie vorher, auch mit neuer Redmatic-Version.

Ich schließe dann mal.
