### ISSUE TITLE
Installation, Deinstallation und Updates in der Palette schlagen fehl

### ISSUE THREAD

**Issue by rauchmandl** [rdmtc/RedMatic#355]
Hoffe, dass ich nichts übersehen habe, aber das Problem konnte ich im Issue Tracker nicht finden.

Ich kann wie in der Überschrift beschrieben, eigentlich nichts mehr hinzufügen oder löschen. Auch Updates können nicht ohne entsprechende Fehlermeldung durchgeführt werden. Auch das Starten im Safe Mode ändert nichts am Verhalten. Eine Deinstallation und neues einspielen des CCU Backups brachten auch nichts. 
Ich hoffe die Fehlermeldung im Anhang hilft bei der Fehlersuche.Danke und  LG Josef

<img width="920" alt="Bildschirmfoto 2020-05-22 um 09 35 34" src="https://user-images.githubusercontent.com/47750394/82643742-610eef80-9c10-11ea-941a-77b817219e7c.png">

**Comment by rauchmandl** [comment]
Habe soeben das 6.0.0 Update installiert. Leider keine Veränderung im Verhalten. LG Josef

**Comment by rauchmandl** [comment]
Bin jetzt auf 6.0.3. keine Änderung des Verhaltens. Kann ich irgendetwas testen oder probieren? LG Josef

**Comment by hklages** [comment]
Kennst du dich mit ssh, putty, etc aus? 
Dann wäre der erste Schritt die package.json zu verifizieren. Da scheint es ja Probleme zu geben.
Wie: Download auf deinen Laptop, dann den ganzen Inhalt ins clipboard und hier prüfen lassen [JSON check](https://jsonformatter.curiousconcept.com/)

Wenn das OK ist, müssen man weiterschauen.

**Comment by rauchmandl** [comment]
Hallo, danke erstmal für deine Hilfe.

ssh verbindung aufbauen stellt kein Problem dar. Aber ich kenne leider die notwendigen Befehle nicht. Konnte bisher durch kopieren der Befehle aus Anleitungen aber alles bewerkstelligen. Was muss ich eingeben damit ich zu der Datei komme?

Vielen Dank
LG Josef

**Comment by hklages** [comment]
Wenn ssh funktioniert kannst du ganz einfach mit [WINSCP](https://winscp.net/eng/index.php) die Datei `package.json` im Verzeichnis `/usr/local/addons/redmatic/var` auf Deinen PC kopieren und dann den JSON Check machen. 

Bei putty ist es wohl der `get` befehl. Mit `cd` bewegst du dich auf der CCU ins obige Verzeichnis. Tab macht vervollständigung.

**Comment by rauchmandl** [comment]
habe einen Mac, daher habe ich statt WINSCP, CyberDuck genommen. Habe die Datei geladen. Sie ist aber leer! 
Das wird das Problem sein.

**Comment by hklages** [comment]
Ja. Lasse es uns nochmal verifizieren. 

Geh in das Verzeichnis und gib `more package.json` ein. Das zeigt den Inhalt an. Blättern mit Leertaste. 

Hast du ein Backup von der Zeit vor dem Issue? Mit 7-zip oder einem ähnlichen Programm kannst du reinschauen und die Datei rausholen. 

So sollte die Datei aussehen: 
`{
  "name": "node-red-project",
  "description": "A Node-RED Project",
  "version": "0.0.1",
  "dependencies": {
    "node-red-contrib-aedes": "~0.3.6",
    "node-red-contrib-alexa-home-skill": "~0.1.17",
    "node-red-contrib-ccu": "3.2.1",
    "node-red-contrib-combine": "1.8.1",
    "node-red-contrib-credentials": "~0.2.1",
    "node-red-contrib-fs-ops": "~1.5.0",
    "node-red-contrib-huemagic": "~3.0.0",
    "node-red-contrib-os": "~0.1.7",
    "node-red-contrib-polly-tts": "0.0.13",
    "node-red-contrib-pushover": "~0.2.0",
    "node-red-contrib-sonos-plus": "~4.3.4",
    "node-red-contrib-sun-position": "1.1.7",
    "node-red-dashboard": "~2.23.3",
    "node-red-node-rbe": "0.2.9",
    "node-red-node-ui-table": "~0.3.6",
    "redmatic-led": "1.1.0"
  }
}
`

**Comment by rauchmandl** [comment]
<img width="425" alt="Bildschirmfoto 2020-10-25 um 12 41 06" src="https://user-images.githubusercontent.com/47750394/97106027-86bc8b00-16bf-11eb-89a1-d2353ba250ef.png">

**Comment by rauchmandl** [comment]
da passiert nichts
ich hoffe du meintest das in der Kommandozeile.

**Comment by hklages** [comment]
Ja, das meinte ich. Schau in den Backup rein. 
Findest du die Datei?

Oder schreib deine Module zusammen dan bauen wie eine neue Datei.

**Comment by rauchmandl** [comment]
{
  "name": "node-red-project",
  "description": "A Node-RED Project",
  "version": "0.0.1",
  "dependencies": {
    "node-red-contrib-better-sonos": "~0.1.21",
    "node-red-contrib-ccu": "3.1.2",
    "node-red-contrib-combine": "1.8.1",
    "node-red-contrib-denon": "~0.1.5",
    "node-red-contrib-samsung-tv": "~0.2.0",
    "node-red-contrib-sun-position": "0.5.4",
    "node-red-dashboard": "2.18.0",
    "node-red-node-email": "1.7.2",
    "node-red-node-rbe": "0.2.5",
    "redmatic-led": "1.1.0",
    "redmatic-webapp": "0.3.1"
  }
}


ist leider schon ein paar Monate alt, habs anscheinend erst recht spät gemerkt

soll ich das einfach in die Package.json einfügen?

**Comment by hklages** [comment]
Sieht doch ganz gut aus. 
Schauen wir mal nach den aktuellen Werten. 
Wieder mit putty auf das system und die Befehle eingeben (der letzte braucht etwas Zeit)

`source /usr/local/addons/redmatic/home/.profile`
`cd /usr/local/addons/redmatic/var`
'npm list --depth=0'

Mit diesen Werte die obige Datei aktualisieren. Dann in den JSON parser zum Prüfen geben.  Und dann zeig es mir hier noch und ich schau auch noch mal drüber.

**Comment by rauchmandl** [comment]
{
  "name": "node-red-project",
  "description": "A Node-RED Project",
  "version": "0.0.1",
  "dependencies": {
    "node-red-contrib-better-sonos": "~0.1.21",
    "node-red-contrib-ccu": "3.2.1",
    "node-red-contrib-combine": "1.8.1",
    "node-red-contrib-denon": "~0.1.5",
    "node-red-contrib-samsung-tv": "~0.2.0",
    "node-red-contrib-sun-position": "1.1.7",
    "node-red-dashboard": "2.23.4",
    "node-red-node-email": "1.7.11",
    "node-red-node-rbe": "0.2.9",
    "redmatic-led": "1.1.0",
    "redmatic-webapp": "0.3.1"
  }
}

.json laut website valide

**Comment by hklages** [comment]
Sieht gut aus. 
Mach sicherheitshalber einen Backup der CCU (ich bin manchmal über vorsichtig) und dann kopier die Datei zurück in das richtige Verzeichnis. Am besten noch einen "more" zur Prüfung ... 

und dann bin ich gespannt.

**Comment by rauchmandl** [comment]
Was soll ich sagen:

Funktioniert wieder tadellos! Soeben das gewünschte Node installiert.

Vielen Dank für die Geduld und die (nicht selbstverständliche) Hilfe!!!

**Comment by hklages** [comment]
Gern. Du solltest nochmal booten - einfach um sicherzugehen, dass auch nach einem Booten alles läuft. 

Und wenn du Hilfe brauchst um von better-sonos (die wird nicht mehr gewartet) auf node-red-contrib-sonos-plus umzustellen kannst du dich gern an nrcsplus@gmail.com wenden.

**Comment by rauchmandl** [comment]
Vielen lieben Dank für den Hinweis mit Sonos!
Werde ich beizeiten versuchen umzustellen.

Danke nochmal und einen schönen Sonntag !
LG Josef
