### ISSUE TITLE
Integration des HmIP-WRCR funktioniert nicht mit RedMatic@CCU3

### ISSUE THREAD

**Issue by BortDeveloper** [rdmtc/RedMatic#358]
Hallo zusammen,

ich versuche gerade den Drehtaster HmIP-WRCR einzubinden, bekomme ueber Redmatic aber nur RSSI events zurueckgeliefert. Hat jemand Erfahrungen oder eine Idee, wie diese Komponente integriert werden kann?

Vielen Dank im voraus

Mein simpler Flow zur Anzeige der Messages:

`[{"id":"f465ed2f.c410c","type":"tab","label":"Test","disabled":false,"info":""},{"id":"7321dda8.16abd4","type":"debug","z":"f465ed2f.c410c","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":870,"y":260,"wires":[]},{"id":"eb841626.dcb768","type":"ccu-rpc-event","z":"f465ed2f.c410c","name":"","iface":"HmIP-RF","ccuConfig":"38263145.35ea0e","rooms":"","roomsRx":"str","functions":"","functionsRx":"str","device":"","deviceRx":"str","deviceName":"DIM_EG_WoziTerasse","deviceNameRx":"str","deviceType":"","deviceTypeRx":"str","channel":"","channelRx":"str","channelName":"","channelNameRx":"str","channelType":"","channelTypeRx":"str","channelIndex":"","channelIndexRx":"str","datapoint":"","datapointRx":"str","change":true,"working":false,"cache":true,"topic":"${CCU}/${Interface}/${channelName}/${datapoint}","x":520,"y":300,"wires":[["7321dda8.16abd4"]]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"localhost","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"300","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","queueTimeout":"5000","queuePause":"250","contextStore":""}]`

Beispiel Debugausgaben (einmal gedrueckt, einmal gedreht):

`{"topic":"localhost/HmIP-RF/DIM_EG_WoziTerasse:0/RSSI_DEVICE","payload":-80,"ccu":"localhost","iface":"HmIP-RF","device":"SerialNo","deviceName":"DIM_EG_WoziTerasse","deviceType":"HmIP-WRCR","channel":"SerialNo:0","channelName":"DIM_EG_WoziTerasse:0","channelType":"MAINTENANCE","channelIndex":0,"datapoint":"RSSI_DEVICE","datapointName":"HmIP-RF.SerialNo:0.RSSI_DEVICE","datapointType":"INTEGER","datapointMin":-128,"datapointMax":127,"datapointDefault":0,"value":-80,"valuePrevious":-77,"valueStable":-80,"rooms":[],"functions":[],"ts":1590223094179,"tsPrevious":1590223086980,"lc":1590223094179,"change":true,"cache":false,"uncertain":false,"stable":true,"_msgid":"dcd25f7f.4ba32"}`

**Comment by BortDeveloper** [comment]
Rechts gedreht:
`{"topic":"localhost/HmIP-RF/DIM_EG_WoziTerasse:0/RSSI_DEVICE","payload":-76,"ccu":"localhost","iface":"HmIP-RF","device":"00285BE989F6E5","deviceName":"DIM_EG_WoziTerasse","deviceType":"HmIP-WRCR","channel":"00285BE989F6E5:0","channelName":"DIM_EG_WoziTerasse:0","channelType":"MAINTENANCE","channelIndex":0,"datapoint":"RSSI_DEVICE","datapointName":"HmIP-RF.00285BE989F6E5:0.RSSI_DEVICE","datapointType":"INTEGER","datapointMin":-128,"datapointMax":127,"datapointDefault":0,"value":-76,"valuePrevious":-84,"valueStable":-76,"rooms":[],"functions":[],"ts":1590230735005,"tsPrevious":1590230724113,"lc":1590230735005,"change":true,"cache":false,"uncertain":false,"stable":true,"_msgid":"f08ae1e.a920f2"}`


Links gedreht:

{"topic":"localhost/HmIP-RF/DIM_EG_WoziTerasse:0/RSSI_DEVICE","payload":-82,"ccu":"localhost","iface":"HmIP-RF","device":"00285BE989F6E5","deviceName":"DIM_EG_WoziTerasse","deviceType":"HmIP-WRCR","channel":"00285BE989F6E5:0","channelName":"DIM_EG_WoziTerasse:0","channelType":"MAINTENANCE","channelIndex":0,"datapoint":"RSSI_DEVICE","datapointName":"HmIP-RF.00285BE989F6E5:0.RSSI_DEVICE","datapointType":"INTEGER","datapointMin":-128,"datapointMax":127,"datapointDefault":0,"value":-82,"valuePrevious":-76,"valueStable":-82,"rooms":[],"functions":[],"ts":1590230737826,"tsPrevious":1590230735005,"lc":1590230737826,"change":true,"cache":false,"uncertain":false,"stable":true,"_msgid":"b470170.cd4fde8"}

**Comment by hobbyquaker** [comment]
vermutlich das "reportValueUsage" Problem. Siehe https://github.com/rdmtc/RedMatic/wiki/Faq#Tastendruck-erzeugt-keine-Events
Bitte gibt Bescheid ob das Dein Problem lösen konnte.
