### ISSUE TITLE
Node Red 1.0.6

### ISSUE THREAD

**Issue by Bono1969** [rdmtc/RedMatic#366]
Guten Abend,
Ist es gewollt dass man über Palettenverwaltung den node-red Node von 1.0.5 nicht auf die aktuelle 1.0.6 updaten kann.
Verwende einen Charly mit der aktuellsten RedMatic und Raspberrymatic Version.

**Comment by hklages** [comment]
Node-RED ist die Basis auf der alle Nodes basieren. Die Nodes kann man per Palettte aktualisieren. 

Node-RED wird aber über npm aktualisiert oder in diesem Fall (CCU) durch eine neue Version von RedMatic (vielleicht 5.5.4). Node-RED 1.1 ist aktuell bereits im Betatest und hat ein paar interessante Neuerungen wie Blocks. 

Wahrscheinlich ist deine Folgefrage: Wann kommt die nächste RedMatic Version mit Node-RED 1.06 oder 1.1 -> die gebe ich weiter an @hobbyquaker  mit der zusätzlichen Frage zu Node.js 12+, da beide Punkte mittlerweile von einigen Nodes (Beispiel Huemagic) als Prereq gefragt sind.

**Comment by unclej84** [comment]
Mag vielleicht nicht zum Thema gehören, aber Jens Maus hat im letzten RaspberryMatic-Release auch Änderungen bzw. npm gemacht - vielleicht hat das ja auch einen Einfluss auf das nächste Release. Node-RED ist ja jetzt auch in Version 1.1 verfügbar.
Das Problem mit den Prereq und Huemagic habe ich leider auch - also Node.js 12+ wäre super.

**Comment by hobbyquaker** [comment]
Zum Thema Node.js Update siehe #374

**Comment by hobbyquaker** [comment]
Zum Thema Node-RED: ein neues Release mit Node-RED v1.1.1 ist in der Mache, ich schließe hier mal.
