### ISSUE TITLE
Nach Backup: Neuinstallation hilft nicht, Deinstallation nicht möglich, Redmatic startet nicht mehr

### ISSUE THREAD

**Issue by AC411** [rdmtc/RedMatic#369]
Hallo zusammen,

ich musste leider ein Backup der CCU einspielen und stehe seitdem ziemlich auf dem Schlauch. Ich vermute, dass die reduzierte Version gewählt war, weiß es aber leider nicht genau. Das Backup als solches ist aber auch zweitrangig, es geht mehr darum Redmatic wieder ans Laufen zu bekommen.
Es erscheint bei mir der Punkte Redmatic unter Systemsteuerung. Nach einem Klick öffnet die Website noch, allerdings kann nicht gestartet werden. Ebenso ist stoppen oder ein restart nicht möglich. Ich habe es neu installiert unter Zusatzsoftware. Das ändert allerdings leider gar nichts. Hat jemand einen Tipp wie es deinstallieren kann, weil es leider nicht unter Zusatzsoftware gelistet wird?

**Comment by hklages** [comment]
Hallo. 
Sehr merkwürdig, dass es nicht unter Zusatzsoftware aufgeführt ist.

- Was steht im log auf der RedMatic Seite - unter Tab debug (download log)
- Was steht im log der CCU  (settings, control panel, ccu maintenance, log? 



Hast du Erfahrung mit ssh/winscp um auf die CCU zuzugreifen und manuell Änderung durchzuführen?

**Comment by AC411** [comment]
Hallo,

ich habe mal beide log Dateien hochgeladen, kann da aber selbst leider nichts draus erkennen.
Mit ssh habe ich bisher nur Erfahrungen über meinen Raspberry Pi. 
Kann man denn nicht irgendwo in der CCU sehen welche Prozesse laufen? Wirklich merkwürdig finde ich, dass der Button Redmatic noch in den Einstellungen zu finden ist. Die Konfigurationsseite wird dann ja auch noch geladen, aber von da aus passiert leider nichts mehr. Jemand irgend eine Idee?

[redmatic.2020-06-30T20_57_53.317Z.log](https://github.com/rdmtc/RedMatic/files/4854418/redmatic.2020-06-30T20_57_53.317Z.log)
[ccu3-webui-2020-06-30.log](https://github.com/rdmtc/RedMatic/files/4854419/ccu3-webui-2020-06-30.log)

**Comment by AC411** [comment]
Habe meine Lösung hier gerade gefunden: Trotzdem danke für die Hilfe! https://homematic-forum.de/forum/viewtopic.php?t=54095

**Comment by hklages** [comment]
Sehr gut - dann mach dieses issue dicht (close and comment)  :-)

**Comment by AC411** [comment]
danke für die Hilfe!
