### ISSUE TITLE
Frage: CCU programmatisch auswählen?

### ISSUE THREAD

**Issue by tsjensen** [rdmtc/RedMatic#370]
Man kann bei Value Nodes ja wie [hier beschrieben](https://github.com/rdmtc/RedMatic/wiki/CCU-Nodes#input) die Auswahl des Datenpunktes programmatisch machen.

Ich habe mehrere CCUs.

Geht die programmatische Auswahl auch für die CCU, d.h. kann ich auf dieselbe Art und Weise den Parameter `CCU` setzen? Ich habe schon mal `msg.ccu` probiert, das hat nicht gewirkt. Der Node gilt nur als "korrekt konfiguriert", wenn eine CCU im Dialog ausgewählt ist, und die zählt dann, egal was in der Message steht.

Danke für die Hilfe!

**Comment by hklages** [comment]
Kann ich mir nicht vorstelllen. Die ccu wird über eine config node gegeben und diese kann man nicht per Befehl auswählen. 

Was willst du machen? Wenn es nur ein Befehl ist kannst du die ccu direct über http ansprechen oder xml api verwenden. Da hast du die Flexibilität.

**Comment by tsjensen** [comment]
Danke für die schnelle Antwort!

Dann werde ich das mit einem Subflow lösen, der einen Switch für die CCUs enthält.

Aber man will ja immer dazulernen: Hast Du einen Link mit einem Beispiel, wie ich Werte programmatisch mittels HTTP oder per XML API abfragen kann (aus Node-RED heraus)? Danke!!

**Comment by hklages** [comment]
Hier ist ein Beispielflow für das Lesen der Systemzeit (sollte immer funktionieren) und dann das Lesen einer Systemvariablen `Basics.SVSystemMessages`   - die muss natürlich existieren. 
CCU hier: `192.168.178.25`, %22 steht für `"`.

`[{"id":"2f9a4425.b9b22c","type":"http request","z":"c7dda7fc.3747d8","name":"","method":"GET","ret":"txt","paytoqs":false,"url":"","tls":"","persist":false,"proxy":"","authType":"","x":630,"y":100,"wires":[["928904a2.b2b808"]]},{"id":"e42f913.962867","type":"inject","z":"c7dda7fc.3747d8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":160,"y":100,"wires":[["9c0c296d.b420a8"]]},{"id":"9c0c296d.b420a8","type":"change","z":"c7dda7fc.3747d8","name":"system date","rules":[{"t":"set","p":"url","pt":"msg","to":"http://192.168.178.25:8181/Test.exe?rsp=system.Date()","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":310,"y":100,"wires":[["2f9a4425.b9b22c"]]},{"id":"928904a2.b2b808","type":"xml","z":"c7dda7fc.3747d8","name":"","property":"payload","attr":"","chr":"","x":770,"y":100,"wires":[["96ebfdfa.517fc"]]},{"id":"96ebfdfa.517fc","type":"debug","z":"c7dda7fc.3747d8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload.xml.rsp[0]","targetType":"msg","x":950,"y":100,"wires":[]},{"id":"fb90006b.8dbb","type":"inject","z":"c7dda7fc.3747d8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":160,"y":160,"wires":[["9ae97c26.d7ac4"]]},{"id":"9ae97c26.d7ac4","type":"change","z":"c7dda7fc.3747d8","name":"variable Basics.SVSystemMessages","rules":[{"t":"set","p":"url","pt":"msg","to":"http://192.168.178.25:8181/Test.exe?rsp=dom.GetObject(%22Basics.SVSystemMessages%22).Variable()","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":390,"y":160,"wires":[["2f9a4425.b9b22c"]]}]`

Man kann mit `dom.GetObject` fast alles machen: Programme starten, Systemvariablen lesen/schrieben, Geräte Datenpunkte lesen/schreiben ... 

Allerdings ist es mit dem Package "CCU"/ RedMatic und den nodes x mal eleganter. Ich hatte früher alles als http Befehl und jetzt nutze ich (weil auch nur eine CCU) ausschließlich RedMatic. 

Beispiel für Lesen Datenpunkt ist: `rsp=dom.GetObject(%22HmIP-RF.0002170993CA67:3.STATE%22).Value()` und schreiben (falls boolen 0|1): `rsp=dom.GetObject(%22HmIP-RF.0002170993CA67:3.STATE%22).State(0)`

**Comment by tsjensen** [comment]
Cool, danke! Frage beantwortet 😃
