### ISSUE TITLE
Feedback 5.6.0 mit Node-RED 1.1.1

### ISSUE THREAD

**Issue by hklages** [rdmtc/RedMatic#372]
- Die Installation dauert sehr sehr lange - man kann nervös werden
- Node-RED 1.1.1 flows braucht etwas länger zum Laden
- bis her läuft es stabil mit diversen Packages (dashboard, sonos-plus, huemagic, aedes MQTT, cron-plus, ...

Danke!

**Comment by hklages** [comment]
2 auffällige Meldungen im debug: 
`Jul  9 20:33:02 ccu3-webui daemon.err node-red: (node:949) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Jul  9 20:33:03 ccu3-webui daemon.info node-red[949]: Loading palette nodes`

`Jul  9 20:33:27 ccu3-webui daemon.err node-red: Thu, 09 Jul 2020 18:33:27 GMT node-telegram-bot-api deprecated Automatic enabling of cancellation of promises is deprecated.
Jul  9 20:33:27 ccu3-webui daemon.err node-red: In the future, you will have to enable it yourself.
Jul  9 20:33:27 ccu3-webui daemon.err node-red: See https://github.com/yagop/node-telegram-bot-api/issues/319. at internal/modules/cjs/loader.js:778:30`

**Comment by hobbyquaker** [comment]
in der 5.6.0-beta.0 gab es ein Fehler im Buildprozess, dadurch wurde das Redmatic Paket unnötig aufgebläht. Schau mal in die Paketverwaltung, da werden vermutlich paar Nodes installiert sein die Du gar nicht haben willst ;) die musst manuell wieder rauswerfen.

**Comment by hklages** [comment]
Die Installation geht jetzt wesentlich schneller

Die Paket discovery, chatbot, reswitch2 sind auch nach einem "remove" unter Pakete und einem reboot weiterhin in der Palette. Allerdings ausgegraut und enable funktioniert nicht. 

Nochmal in Paket reswitch2 installiert, enabled, removed und jetzt sind keine der Pakete mehr sichtbar. Etwas "strange" aber so passt es. 

Die Buffer meldung ist weiterhin im log, die telegram logischerweise nicht.

**Comment by stuckis6er** [comment]
Hallo,
ich benutzt ein Android Tablet. Bei der Touch-Bedienung lässt sich der Arbeitsbereich nicht mehr verschieben. Gestestet mit verschiedenen Browsern. Bein Chrome Browser lässt sich der Arbeitsbereich zwar verschieben dafür kann ich die Nodes nicht mehr verbinden.
