### ISSUE TITLE
Vorschlag: setting.js in /usr/local/addons/redmatic/var

### ISSUE THREAD

**Issue by hklages** [rdmtc/RedMatic#373]
Bei den neueren Installationen von Node-RED ist es standard, dass

a) setting.js ist in user dir also `/usr/local/addons/redmatic/var`
b) eine Kopie des default setting.js verwendet wird und nur "auskommentiert"/geändert wird. 

Vorschlag ist, dies auch bei RedMatic so zu handhaben.

**Comment by hobbyquaker** [comment]
RedMatic erzeugt die Settings dynamisch aus den Defaults die Node-RED liefert und einer JSON Datei die durch das RedMatic UI erzeugt wird. Kannst hier anschauen: 
https://github.com/rdmtc/RedMatic/blob/master/addon_files/redmatic/lib/settings.js

Sehe jetzt spontan kein Grund das zu ändern, kannst Du erläutern was da Dein Hintergedanke dabei ist?

**Comment by hklages** [comment]
In anderen Installationen (Raspberry, Docker images) ist settings.js in `user dir`. Dies sagt auch die Node-RED Dokumentation: 
[Node-RED Dokumentation](https://nodered.org/docs/user-guide/runtime/settings-file): 

> Where is my settings file?
When Node-RED starts, it looks for a file called settings.js in your Node-RED user directory, ~/.node-red. If it does not find one there, it will copy in a default settings file to that directory and use it.

Alternatively, the --settings command-line argument can be used when starting Node-RED to point at a different file.

If you have not yet run Node-RED and want to edit the settings file, you can copy the default settings file in manually from here.

Es ist aber nichts wesentlich. Vielen Dank für den schnellen Upgrade auf 1.1.x - damit kann ich jetzt viele Flows einfacher gestalten - Stichwort JSONata $moment.

**Comment by hobbyquaker** [comment]
ok, dann mach ich hier zu ;)
