### ISSUE TITLE
Node-RED Touch-Bedienung

### ISSUE THREAD

**Issue by hobbyquaker** [rdmtc/RedMatic#375]
Hallo,
ich benutzt ein Android Tablet. Bei der Touch-Bedienung lässt sich der Arbeitsbereich nicht mehr verschieben. Gestestet mit verschiedenen Browsern. Bein Chrome Browser lässt sich der Arbeitsbereich zwar verschieben dafür kann ich die Nodes nicht mehr verbinden.

_Originally posted by @stuckis6er in https://github.com/rdmtc/RedMatic/issues/372#issuecomment-656374635_

**Comment by hobbyquaker** [comment]
https://github.com/node-red/node-red/issues/2647

**Comment by stuckis6er** [comment]
Ist mit der Version 1.1.2 behoben. Danke.
