### ISSUE TITLE
armv6l (Raspberry Pi 1 und Zero) Support einstellen?

### ISSUE THREAD

**Issue by hobbyquaker** [rdmtc/RedMatic#376]
Da weniger als 1% der RedMatic User noch alte Raspberry Pi 1 einsetzen - und es für armv6 nur noch inoffizielle Node.js Builds gibt - auf armv7 gehen und den Pi 2 zur Mindestvorraussetzung machen?

**Comment by Ixuser-1** [comment]
Sehe ich auch als sinnvoll an, obwohl ich aktuell bei einer kleineren Applikation auch noch alten Pi 1 einsetze.

**Comment by hobbyquaker** [comment]
Solange es auf https://unofficial-builds.nodejs.org/ noch armv6l Builds gibt bleibt der Support für die RaspberryMatic Platform _rpi0_ erhalten. Ich rate jedoch ausdrücklich davon ab RedMatic mit nur 512MB RAM zu nutzen, ein Upgrade auf pi3/pi4 sollte durchgeführt werden ;)
