### ISSUE TITLE
Redmatic 6.0.0 Startet nicht

### ISSUE THREAD

**Issue by TheBassfly** [rdmtc/RedMatic#379]
Moin

Habe eben meine CCU3 auf die neue Redmatic Version gehoben. Leider startet die Redmatic nicht mehr. Es kommt immer nur die Meldung "Ein Fehler ist aufgetreten."
Ebenfalls im Safe Mode.
Im Log wird angegeben das Redmatic am laufen wäre, aber in der UI steht immer "Stopped" und auch in Homekit wird kein Gerät gefunden.

Gibt es da eine Lösung?

LG

**Comment by hobbyquaker** [comment]
Lässt sich via RedMatic UI ein Restart auslösen? Kannst Du bitte mal ein Debug Log erstellen? (https://github.com/rdmtc/RedMatic/wiki/Loglevel)

**Comment by TheBassfly** [comment]
Da ich wieder arbeiten musste und das System daheim funktionieren muss wenn ich weg bin, bin ich wieder auf 5.5.3 gewechselt. Daher muss ich das verneinen bzw. Kann frühestens am Dienstag wieder mit experimenten anfangen.

**Comment by docNeptun** [comment]
Moin,
ich habe nach dem Update das gleiche Problem.
Debug log meldet: "Error: Cannot find module '/usr/local/addons/redmatic/lib/node_modules/node-red/red.js'"
Details folgen...

**Comment by hobbyquaker** [comment]
> Aug 2 16:18:05 ccu3-webui daemon.err node-red: Error: Cannot find module '/usr/local/addons/redmatic/lib/node_modules/node-red/red.js'

Das sieht nach einer unvollständigen Installation aus. Da würd ich empfehlen es noch mal "drüber" zu installieren.

**Comment by docNeptun** [comment]
> > Aug 2 16:18:05 ccu3-webui daemon.err node-red: Error: Cannot find module '/usr/local/addons/redmatic/lib/node_modules/node-red/red.js'
> 
> Das sieht nach einer unvollständigen Installation aus. Da würd ich empfehlen es noch mal "drüber" zu installieren.

Leider hat eine erneute Installation keine Verbesserung erbracht... gleicher Fehler.
Ich versuche jetzt ein Downgrade auf die letzte stable Version.

**Comment by alphabravocharly72** [comment]
Hab auch das gleiche Problem.

**Comment by hklages** [comment]
Bei mir läuft die 6.0.0 seit 18 Stunden. Installation war über beta0->beta1-> final. Installation dauert 15 bis 30 Minuten auf einer CCU3 ohne jegliche CCU Programme (ich nutze ausschließlich Node-RED für die Steuerung). 

Ich hänge meine installierten Module hier an - mit denen lief die Installation durch.
![Screenshot_20200803-072548_Edge](https://user-images.githubusercontent.com/17273119/89148805-1a683a80-d55b-11ea-9a41-7f572bf90c48.jpg)

**Comment by dehsgr** [comment]
Bei mir lief eben die Installation auch problemlos von der letzten 5.x kommend problemlos (und schnell) durch, auch vollkommen komplikationslos. Danke für den Release und die Arbeit an dieser Stelle!

**Comment by alphabravocharly72** [comment]
Hallo hobbyquaker,
hier mein log, vlt kannst du mir weiter helfen. Auch die gesicherten flows funktionieren nicht mehr. 
Danke alpha

[redmatic.2020-08-03T21_54_20.405Z.log](https://github.com/rdmtc/RedMatic/files/5018932/redmatic.2020-08-03T21_54_20.405Z.log)

**Comment by hobbyquaker** [comment]
@alphabravocharly72 hast Du mal versucht im Safe-Mode zu starten (https://github.com/rdmtc/RedMatic/wiki/Safe-Mode)? Ich glaube da werden ein paar Nodes verwendet die irgendwie Probleme machen, möglicherweise wurden die beim Update "beschädigt"

```
Aug  3 23:53:51 ccu3-webui daemon.info node-red[1559]: Waiting for missing types to be registered:
Aug  3 23:53:51 ccu3-webui daemon.info node-red[1559]:  - pwsapikey
Aug  3 23:53:51 ccu3-webui daemon.info node-red[1559]:  - ui_led
Aug  3 23:53:51 ccu3-webui daemon.info node-red[1559]:  - pws-observations
Aug  3 23:53:51 ccu3-webui daemon.info node-red[1559]:  - pws-historical
Aug  3 23:53:51 ccu3-webui daemon.info node-red[1559]:  - pws-forecast
Aug  3 23:53:51 ccu3-webui daemon.info node-red[1559]:  - pws-7day-summary
Aug  3 23:53:51 ccu3-webui daemon.info node-red[1559]:  - pws-7day-hourly
Aug  3 23:53:51 ccu3-webui daemon.info node-red[1559]:  - pws-1day-all
```

**Comment by alphabravocharly72** [comment]
hi, ja, auch hier das gleiche Problem. Im safe mode wird node red nicht gestartet. Geht nach ein paar seconds auf stopped.
Eigentlich gehts mir jetzt mehr darum das ich meine gesicherten flows wieder unter der letzen funktionierenden Installation zum laufen bekomme (5.5.3). 
Hab das log von der 5.5.3 Installation inkl. der gesicherten, installierten files (flows, flows_cred und credentials) angehängt. Die 5.5.3 kann ich starten nur die ganzen flows sind nicht connected mit der CCU3 und das Dashboard funktioniert auch nicht (bekomme nur den Start Bildschrim zu sehen).
Danke für deine Hilfe
alpha
[redmatic.2020-08-03T23_09_17.624Z.log](https://github.com/rdmtc/RedMatic/files/5019263/redmatic.2020-08-03T23_09_17.624Z.log)

**Comment by hobbyquaker** [comment]
Kannst Du bitte noch mal den Safe Mode Start machen und danach direkt ein Log herunterladen? Man sieht im letzten Log wieder dass aufgrund fehlender Nodes die Flows nicht starten, ein Safe-Mode Start ist in den beiden Logs aber nicht ersichtlich.

**Comment by alphabravocharly72** [comment]
Guten morgen, hab jetzt alle nicht benützen nodes gelöscht, bei configuration waren zwei dashboard group nodes die unknown  waren. Habe diese zwei gelöscht jetzt funktioniert es wieder. Somit funktioniert die 5.53 wieder.
Das Problem mit der 6.0 ist nach wie vor. Hab
[redmatic.2020-08-03T23_09_17.624Z.log](https://github.com/rdmtc/RedMatic/files/5021098/redmatic.2020-08-03T23_09_17.624Z.log)
 ein log angehängt im safe mode mit der 6.0 hoffe du findest was. Danke für deine Hilfe. alpha

**Comment by alphabravocharly72** [comment]
Wie du am Bild sehen kannst sind die zwei buttons oben recht ausgegraut, auch Neustart und stop.
Sobald ich start drücke egal ob normal oder safe mode startet es für ein paar Sekunden und dann kommt stopped (wie am Bild zu sehen). Habe die 5.5.3 vorher deinstalliert und einen neu start der CCU3 gemacht und dann die 6.0 installiert. Bekomme das gleiche Ergebnis auch wenn ich es über die 5.5.3 drüber installiere.
![image](https://user-images.githubusercontent.com/59312982/89275180-37c40400-d642-11ea-8e69-c392f9ea9039.png)

**Comment by bka-git** [comment]
Hallo,

habe ein ähnliches Problem. Nach der Installation von Redmatic 6.0.0 und Restart der ccu3 behauptet die Plugin Seite redmatic wäre gestoppt. Jedoch kann ich die node-red Seite über http://ccu3/addons/red/ erreichen und auch Änderungen vornehmen.

[redmatic.2020-08-05T11 42 37.330Z.log](https://github.com/rdmtc/RedMatic/files/5028067/redmatic.2020-08-05T11.42.37.330Z.log)

**Comment by djiwondee** [comment]
Hallo @bka-git,

das ist ein typisches Symptom, wenn der Browser-Cache nach einem CCU-Neustart noch alte Session-Daten beinhaltet. Eine Leeren des selben mit anschließendem Browser-Neustart sollte wieder alles "normal" aussehen lassen. In Deinem Fall hast Du wohl versucht in er "alten Session" Node-Red noch einmal zu starten. Deshalb geht das wieder auf "Stopped"

**Comment by bka-git** [comment]
vielen Dank für die schnelle Hilfe. Das wars, funktioniert einwandfrei :-)
<img width="1608" alt="Bildschirmfoto 2020-06-02 um 17 20 53" src="https://user-images.githubusercontent.com/62538029/89410460-47f7e400-d713-11ea-9165-d33755b13b05.png">

**Comment by alphabravocharly72** [comment]
Jetzt funktioniert es bei mir auch wieder.
Danke

**Comment by euskij** [comment]
bei mir läufts auch wieder, ohne, dass ich etwas tun musste....

**Comment by TheBassfly** [comment]
Moin

Also ich hab heute auch mal wieder probiert und der Tip mit dem Cache leeren hat mutmaßlich was gebracht. Jetzt ist bei mir wieder alles normal mit der V6 👍 
Danke
