### ISSUE TITLE
CCU3 nach Redmatic 6.0 Update nicht mehr erreichbat

### ISSUE THREAD

**Issue by euskij** [rdmtc/RedMatic#380]
Hallo zusammen,

hab eben die neue Redmatic Version heruntergeladen und einen Update auf der CCU3 gestartet (einfach drüber gebügelt). Jetzt ist die CCU3 bereits 10min nicht mehr erreichbar. Eine Idee?

BG

**Comment by hobbyquaker** [comment]
Kann durchaus auch über 10 Minuten dauern, falls etwas schief läuft müsstest Du mir mal das Debug Log zeigen https://github.com/rdmtc/RedMatic/wiki/Loglevel

**Comment by euskij** [comment]
nnach einem Neustart war die CCU wieder erreichbar, habe aber dasselbe Problem, dass RedMAtic leider nicht startet. Erneutes installieren hat leider auch nicht geholfen. Ich schließe diesen thread und würde den ersten zu diesem Fehler weiter verfolgen. Vielen DAnk! LG

**Comment by euskij** [comment]
Issue bereits aufgenommen
