### ISSUE TITLE
Frage: Globale Variable ccu-localhost

### ISSUE THREAD

**Issue by hklages** [rdmtc/RedMatic#382]
Ich habe unter meinen globalen Variablen eine "ccu-localhost" - die wird wahrscheinlich von CCU angelegt - richtig?
Mein "default" für global variablen ist file-system. Passt das auch für diese Variable oder ist aus performance gründen besser auf "memory" zu setzen. Für eine globale variable sind viel Daten gespeichert - die Datenpunkte unter anderem.

**Comment by hobbyquaker** [comment]
Die Abwägung musst Du selbst treffen :)
Vorteil von Filesystem: Es werden beim Node-RED/Flow Neustart evtl. überflüssige "Change" Events vermieden weil sich ggü. dem Zustand vor dem Neustart nichts geändert hat. Ich würde Filesystem aber nur mit einem USB Stick nutzen, ich rate davon ab das mit einer SD zu machen.

**Comment by hklages** [comment]
Danke. Verstanden.
