### ISSUE TITLE
Redmatic Probleme mit Firmware CCU3 Update 3.53.2

### ISSUE THREAD

**Issue by TheBassfly** [rdmtc/RedMatic#388]
Moin

Habe eben meine CCU auf die neue Firmware gebracht und jetzt werden mir in Home alle Homematic Geräte mit "Keine Antwort" gezeigt, obwohl Redmatic keine Fehler aufwirft.

Ich hab mal das Debug Log erstellen lassen. Eventuell hilft es.

lg
[redmatic.2020-08-18T09_46_47.204Z.log](https://github.com/rdmtc/RedMatic/files/5089610/redmatic.2020-08-18T09_46_47.204Z.log)

**Comment by TheBassfly** [comment]
Kleines Update.
Ich hab ein Downgrade auf die Firmware 3.51.6 gemacht. Jetzt funktioniert die Redmatic garnicht mehr. Im Fenster "Zusatzsoftware" tauch sie nicht mehr auf, aber in der System Steuerung steht es noch und wenn ich drauf klicke versucht es stundenlang zu starten. Eine neu Installation hat bisher nicht geholfen. Deinstallieren geht ja irgendwie auch nicht.

**Comment by TheBassfly** [comment]
Nächstes Update und Problem:

Redmatic ist hinüber und ich kann es nicht mehr deinstallieren. Hat eventuell jemand einen Tip, wie man das z.B. über SSH lösen könnte? Oder muss ich auf ein Update warten?

**Comment by Sineos** [comment]
Du kannst über SSH den ganzen Redmatic Ordner löschen:

`/usr/local/addons/redmatic`

Deinen Flow vorher sichern: https://github.com/rdmtc/RedMatic/wiki/Backup

**Comment by TheBassfly** [comment]
Danke
Nach eine Nacht Aktion mit Downgrade, CCU Rosetten und Backup einspielen ist dann die Redmatic auch wieder da auf der alten Firmware Version.
Dann warten wir mal, bis Redmatic kompatibel ist.

**Comment by hobbyquaker** [comment]
Das Log zeigt keinerlei Auffälligkeiten, ich glaube auch nicht dass es ein allgemeines Problem mit der 3.53.x gibt - mittlerweile läuft das bei knapp 300 Leuten und auch bei meinen Tests hier hatte ich keine Probleme entdeckt. 
Spekulation - aber nicht unwahrscheinlich: ich habe schon mehrfach gesehen wie CCU Updates die Firewall-Regeln zurückgesetzt haben. Das wäre eine Mögliche Erklärung warum in HomeKit alles unerreichbar wurde.

**Comment by TheBassfly** [comment]
Moin

Also heißt es im Grunde, daß kein Update notwendig ist und ich es einfach nochmal versuchen sollte mit dem Update? Ich bin da etwas gehemmt jetzt, weil der Downgrade alleine bei mir schon gut 6 Stunden und drei versuche benötigte bis auch die Redmatic wieder einwandfrei drin war.

**Comment by hobbyquaker** [comment]
Mjo, oder Du wartest gleich auf das nächste Release, das werd ich vermutlich in 8 Tagen machen.

**Comment by TheBassfly** [comment]
Naja, solange kann ich erstmal warten. Und wenn nicht melde ich mich einfach für Hilfe hier nochmal. Gibt es denn einen Tip für das Update? Eventuell Redmatic vorher deinstallieren oder so?

**Comment by hobbyquaker** [comment]
Ne, eigentlich sollte das "einfach so" funktionieren. Falls es wieder zu Problemen mit HomeKit kommt würde ich wie gesagt als erstes die Firewall-Einstellungen der CCU kontrollieren (https://github.com/rdmtc/RedMatic/wiki/Homekit#ccu-firewall)

**Comment by TheBassfly** [comment]
So, ich habe es al nochmal probiert und einfach die neue Firmware drauf geschmissen.
Was soll ich sagen: Jetzt läuft alles ohne Probleme. Ich denke das erste Update hatte sich verschluckt.
Danke für die Hilfe hier.
