### ISSUE TITLE
kein '.replace(/x/g, "y")' im Funktions Node mehr möglich

### ISSUE THREAD

**Issue by Matten-Matten** [rdmtc/RedMatic#390]
Hallo,
kein '.replace(/x/g, "y")' im Funktions Node mehr möglich. 
es wir nur des fehler "TypeError: Cannot read property 'replace' of undefined" im debug
Fenster angezeigt.

Gruß
Matten Matten

**Comment by Sineos** [comment]
Das ist mit großer Wahrscheinlichkeit kein Redmatic Fehler.
Vermutlich ist an irgendeinem Punkt in deinem Code `XX` von `XX.replace(...)` undefined oder kein String. Lass es dir per `node.warn(XX)` ausgeben.

**Comment by Matten-Matten** [comment]
hmm ok mein ganzer code sieht so aus:
msg.ecomode ist ein boolean wert...

`var ecomode = msg.ecomode.replace(/true/g, "im Eco Modus").replace(/false/g, "");`

**Comment by Sineos** [comment]
Wie wärs damit?

`[{"id":"c24015ec.e8f848","type":"inject","z":"2808bf91.f42188","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":1030,"y":60,"wires":[["2c26a879.5884c8"]]},{"id":"2c26a879.5884c8","type":"function","z":"2808bf91.f42188","name":"","func":"var bla = msg.payload ? \"im eco\" : \"nönö\"\nnode.warn(bla)","outputs":1,"noerr":0,"initialize":"","finalize":"","x":1220,"y":60,"wires":[[]]},{"id":"4abfc23f.32fb34","type":"inject","z":"2808bf91.f42188","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"false","payloadType":"bool","x":1030,"y":100,"wires":[["2c26a879.5884c8"]]}]`

**Comment by Matten-Matten** [comment]
@Sineos ,
vielen dank! das hilft mir bei boolean werten sehr weiter! 
Ich nehme an vor dem Doppelpunkt ist immer true und dahinter false? 
`"im eco" : "nönö"`
`   true  : false  `

das `.replace(//g, "")` funktioniert dann nur mit string werten?


Gruß
Matten Matten

**Comment by Sineos** [comment]
Gerne.

Ist im Prinzip die Kurzform von:
```
if (msg.payload === true) {
    bla = "eco"
} else {
    bla = "nönö"
}
node.warn(bla)
```

bzw.:

```
if (msg.payload) {
    bla = "eco"
} else {
    bla = "nönö"
}
node.warn(bla)
```

Wenn du den Vergleichswert weg lässt, wird immer auf true / false geprüft. Hat aber den Nachteil, dass "absolut falsch" in JS auch true ist.

Für die Kurzform siehe: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Operators/Conditional_Operator
