### ISSUE TITLE
Thermostat ändert Schaltzustand spät

### ISSUE THREAD

**Issue by theo-69** [rdmtc/RedMatic#393]
Hallo ich habe ein Wandthermostat mit einem Unterputzschalter als direkte Verbindung verknüpft. Ändere ich die Temperatur am Thermostat schaltet der Schalter sofort. Ändere ich die Temperatur via HomeKit dauert es ca. 5min. Was mache ich falsch oder wie kann ich das Problem beheben?

**Comment by Sineos** [comment]
Naja, mit diesen spärlichen Informationen wirds schwierig zu helfen.

Als ersten Ansatz würde ich überall Debug Nodes hin bauen und schauen, ob die gewünschten Messages ankommen oder eben wo sie hängen bleiben.

**Comment by theo-69** [comment]
ist ein internes bekanntes Homematic Problem
