### ISSUE TITLE
Segfault after upgrade to 6.0.3

### ISSUE THREAD

**Issue by xLerate** [rdmtc/RedMatic#397]
After upgrading to 6.0.3 (from 5.3.10) on ccu3, redmatic fails to start with error code 139 (segfault). Even in safe-mode.
`Sep22 00:04:07 ccu3-webui daemon.info redmatic: RedMatic v6.0.3 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Sep 22 00:04:07 ccu3-webui daemon.info redmatic: Starting Node-RED
Sep 22 00:04:07 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 139`

I tried to debug a bit. I can successfully run node and node-red from commandline. But i need a bit help on how to start from commandline with my former configuration. There are many env-variables to set for a proper start.

Where i should start debugging?

**Comment by Sineos** [comment]
See https://github.com/rdmtc/RedMatic/issues/187

**Comment by xLerate** [comment]
thx, i already saw this ticket, but i was looking for the root cause. nevertheless, due to lack of time i solved my issue exactly this way.

- manual backup of redmatic by creating a tar-ball from `/usr/local/addons/redmatic`
- uninstall redmatic from CCU3-ui
- reinstall redmatic
- stop redmatic and restore `var`-dir (and if neccessary the same for credentials and settings) - see https://github.com/rdmtc/RedMatic/wiki/Backup for details

There is only one issue remaining: the start/stop-status of  redmatic is not shown correctly. After successful start its going back to stop-state, even though redmatic is up and running.
Regardless of this minor issue i gonna close this ticket.
