### ISSUE TITLE
Offset bei Inject Enhanced Node funktioniert nicht mehr

### ISSUE THREAD

**Issue by UserRG** [rdmtc/RedMatic#400]
Ich bin auf Version 6.0.3 gegangen, seitdem funktioniert der Offset bei dem o.g. Node nicht mehr.
Egal welcher Offset erfasst wird, es bleibt bei derselben Uhrzeit. Einen Anzeigefehler kann ich ausschließen, da ich darüber meine Rollosteuerung starte. Obwohl ein Offset von -45 erfasst war, startete der Flow erst zu Offset 0.

**Comment by Sineos** [comment]
Einfach über den Pallettenmanger die `node-red-contrib-sun-position` aktualisieren und das Problem sollte behoben sein.

**Comment by UserRG** [comment]
OMG... Ich ging davon aus, dass es schon die aktuellste Version ist... Danke... Hat natürlich geholfen...
Dafür geht nach update auf 6.0.3 die Harmony-websocket-Nodes nicht mehr... :-(

**Comment by Sineos** [comment]
Kenne ich leider nicht.
Diese https://github.com/lopelex/node-red-contrib-harmony oder diese https://github.com/Aietes/node-red-contrib-harmony ?

**Comment by UserRG** [comment]
Die erste von lopelex. Vermute das hat was mit den Binärmodulen zu tun. Habe ein neues Issue dafür aufgemacht.

**Comment by UserRG** [comment]
es lag tatsächlich an der alten Version
