### ISSUE TITLE
Fehler beim Schreiben des Kontextes: Error: EROFS: read-only file system, open '/media/usb1...

### ISSUE THREAD

**Issue by djiwondee** [rdmtc/RedMatic#401]
Seit ein paar Tagen läuft bei mir die Datei `/var/log/messages/`mit folgendem Fehler(n) voll:
```
...daemon.err node-red[5867]: Fehler beim Schreiben des Kontextes: Error: EROFS: read-only file system, open '/media/usb1/context/...
```

Trifft für alle Kontext-Dateien der Flows zu, die auf dem angeschlossenen USB-Stick und umgestellter Konfiguration [gemäß Anleitung](https://github.com/rdmtc/RedMatic/wiki/Context-Storage) ihre Daten abspeichern.

In den Issues habe ich dazu schon mal recherchiert [z. B. in dem Track](https://github.com/rdmtc/RedMatic/issues/320). Werde daraus aber nicht schlau. Ist der USB-Stick defekt? Das Symptom ist ja das selbe.

Habe auch mit dem `root`-User mal versucht über das Terminal eine Datei anzulegen. Selber Fehler:
```
touch: test.txt: Read-only file system
```

Ich benutze `redmatic 6.0.3` auf einer `CCU3 mit Release 3.53.30`. Letzteres habe ich vor ein paar Tagen aktualisiert. Hängt das ggf. damit zusammen? Wird der usb-Stick vielleicht read-only gemounted?
```
Filesystem           Type            Size      Used Available Capacity Mounted on
/dev/sda1            vfat           14.9G    944.0K     14.9G   0% /media/usb1
```
Die Nutzung des USB-Stick hat vorher lange funktioniert. Ich verwende den Context-Store für viele Anwendungsfälle (node, flow und global) auf dem USB-Stick seit der Erstinbetriebnahme von Redmatic. Vielen Dank im Voraus für Hilfe.

**Comment by djiwondee** [comment]
Nach dem ich auch auf der CCU3 keine Diagramme anlegen konnte (die schreiben ja auch die Meassurements auf den gemounteten USB-Stick), habe ich auf der CCU3 mal das System log geprüft:

```
...
java.io.FileNotFoundException: /media/usb0/measurement/1.rrd (Read-only file system)
...
Sep 28 14:52:37 de.eq3.lib.datalogging.rrd.RrdDatalogging ERROR [vert.x-worker-thread-1] The diagram 1 could not be created 
```

Ein Neustart der CCU hat das Problem beseitigt. Diagramme gehen wieder und auch das Schreiben der Node-Red-Context-values. Jedoch die Ursache habe ich dafür (bisher) nicht identifizieren können. Es wundert mich, dass in dem log `/media/usb0`auftaucht. Das wird gar nicht per `mount` eingebunden.

**Comment by guny74** [comment]
Hallo,

ich würde den Issue gerne (wieder) aufmachen, denn ich habe das gleiche Problem, ein Neustart behebt das Problem nur Temporär.
Ich habe auch schon den USB Stick getauscht und non-quick Format durchgeführt, aber es hält eben danach nur einige Tage.

Was kann die Ursache sein ?

Danke

**Comment by Sineos** [comment]
Mit ziemlicher Sicherheit ein defekter USB Stick. Zufällig ein Sandisk?

**Comment by guny74** [comment]
Hallo,

ja zwar nen sandisk, aber ich habe den Stick schon getauscht.

Ich habe den letzten "neuen" Stick mit 
`dosfsck -rw /dev/sda1   
`
repariert.
Nach einen "sauberen" Reboot desr "raspberrymatic" bekomme ich beim gleiben Befehl wieder die Meldung  

```
CP437: Invalid argument
fsck.fat 4.1 (2017-01-24)
0x41: Dirty bit is set. Fs was not properly unmounted and some data may be corrupt.

```
als wenn beim Reboot der USB nicht richtig unmounted wird....
Ich werde es aber nochmal mit einem ganz neuen Stick probieren....

**Comment by Sineos** [comment]
Das sind aber klare Meldung des Betriebssystems und die haben nichts mit RedMatic zu tun. 
Das Betriebssystem sagt hier klar und deutlich, dass es mit dem Stick nicht einverstanden ist.

Bzgl. Sandisk: Ich hatte mit zwei Sandisk Sticks den gleichen Zirkus in meiner CCU und wenn du nach diesem Effekt googelst, sind wir hier nicht allein: Die Dinger scheinen ganz empfindlich (speziell auf unsauberes Beenden) zu reagieren und sich dann in einen Art "Read Only" Modus zu setzen aus dem es dann auch kein Entkommen mehr gibt.

**Comment by guny74** [comment]
Hallo,

als ich meine ersten Post hier drangehängt habe, hatte ich das mit den Befehlen noch nicht heraus gefunden.
Ich versuche es mal mit nem anderen Stick oder frage wegen sauberen unmount bei "raspberrymatic" nach.

Danke für die Tips.

**Comment by hannoverRed** [comment]
hi, wie kann ich über node red den usb stick leeren? und optional alles was älter als 30 tage ist löschen?
lg

**Comment by djiwondee** [comment]
@hannoverRed 
Das Filesystem auf dem USB-Stick ist ggf. dahingehend beschädigt, dass eine oder mehrere Dateien, die einen Node/Flow/Global Kontext repräsentieren verwaist sind. Das kann z. B.  passieren, wenn die CCU vom Strom getrennt wurde, ohne sie vorher ordnungsgemäß runterzufahren. Da sind die Files offengeblieben und beim nächsten Booten mounted die CCU das Filesystem des Sticks  nur read only. Beim Booten läuft ein Diskckeck, der die korrupten Einträge im Filesystem erkennt. Durch das read-only kann das OS nicht mehr schreiben und der o. g. Fehler tritt auf. 

Wirkliche Abhilfe bringt nur, den Stick mittels eines Festplatten-Dienstprogramms zu prüfen, und ihn damit zu reparieren, sofern er nicht wirklich defekt ist. Ist diese Reparatur erfolgreich, lassen sich die korrumpierten Files löschen. Das sollte gehen, wenn man den Stick mit  read/write gemounted hat. (Z. B. am PC/Mac) Anschließend den Stick wieder in die CCU stecken und hochfahren.
