### ISSUE TITLE
5.6.0beta2 install ok, 6.03 new install and upgrade from 5.6 fails to start

### ISSUE THREAD

**Issue by StephanBieker** [rdmtc/RedMatic#403]
x86 virtual
5.6.0beta 2 installs ok
6.03 fails to start after fresh install, fails also to start after upgrade from 5.6.0beta 2
[Uploading redmatic.2020-09-29T15_38_39.695Z.log…]()

**Comment by hobbyquaker** [comment]
Seems that log upload failed. Did you clear your Browser Cache after the Update? That's a known problem when updating from 5.x to 6 and leads to a disfunctional RedMatic UI.
Possible duplicate: #407

**Comment by StephanBieker** [comment]
Redmatic fails to start also after a fresh clean install from 6.03.

Sebastian Raff <notifications@github.com> schrieb am Fr., 2. Okt. 2020,
21:32:

**Comment by StephanBieker** [comment]
[redmatic.2020-09-29T15_38_39.695Z.log](https://github.com/rdmtc/RedMatic/files/5321148/redmatic.2020-09-29T15_38_39.695Z.log)

**Comment by hobbyquaker** [comment]
Ah - I see. Sorry to say that RedMatic 6.x is not (yet) compatible with a virtual RaspberryMatic. Missed that in your first post. I'm working on it, but can't promise when it's done, hopefully in october. See also https://github.com/rdmtc/RedMatic/issues/374
