### ISSUE TITLE
WRC6 funktioniert nicht mehr in HomeKit 

### ISSUE THREAD

**Issue by TheBassfly** [rdmtc/RedMatic#410]
Hello zusammen

Seit einigen Tagen habe ich auf einmal Probleme mit meinem WRC6 in HomeKit. Bisher lief er einwandfrei die Taster haben in HomeKit Szenen getriggert.
Jetzt bekomm ich angezeigt, daß eine Verbindung zur Steuerzentrale nicht möglich wäre. 
Habe den HomeKit Event Node und den RPC Node beide mal neu installiert. Gestern lief es dann nochmal kurz aber heute morgen ohne das ich was geändert habe, ist es wieder gestört.

Ich befürchte der Fehler liegt in der Redmatic da auch die Homematic keine Kommunikationsstörung anzeigt.

CCU3, Firmware 3.53.30

Danke für eure Hilfe.

**Comment by TheBassfly** [comment]
Kleines Update:
Das Debug in Node red gibt bei einem Tastendruck das hier aus:

"TypeError: Cannot read property 'getCharacteristic' of undefined"

**Comment by TheBassfly** [comment]
So, also habe nochmal etwas romprobiert und habe einfach mal einen virtuellen Taster als RPC-Event angelegt und das ganze dann an HomeKit als Event ausgegeben.
Da funktioniert nichts mehr. Kann es sein, daß da in der Redmatic was zerschossen wurde?

**Comment by TheBassfly** [comment]
Hat da keiner aktuell eine Idee oder Lösung oder fehlt es noch an Infos?

**Comment by TheBassfly** [comment]
Also ich hab nochmal gecheckt.
Mit einem Debüt Node wird angezeigt, daß der RPC Node den Tastendruck ausgibt. Aber der HomeKit Event Node kann es nicht mehr verarbeiten. Da kommt dann die Meldung:
"TypeError: Cannot read property 'getCharacteristic' of undefined"

**Comment by hobbyquaker** [comment]
Da müsstest mal ein Log auf Level Debug zeigen (siehe https://github.com/rdmtc/RedMatic/wiki/Loglevel)

**Comment by TheBassfly** [comment]
[redmatic.2020-10-10T17_44_01.388Z.log](https://github.com/rdmtc/RedMatic/files/5359564/redmatic.2020-10-10T17_44_01.388Z.log)

Anbei mal das gewünschte Log.

**Comment by hobbyquaker** [comment]
Oh, ich glaub das ist Loglevel Trace, das loggt soviel dass nur ein sehr kurzer Zeitraum enthalten ist (der auch den Fehler nicht zeigt...). Kannst Du bitte das Loglevel mal auf "Debug" setzen, Node-RED Neustarten, dann paar Minuten warten, den Fehler reproduzieren und danach das Log herunterladen?

**Comment by TheBassfly** [comment]
Eigentlich stand es auf Debug

Naja, ich hab mal neu gestartet und einfach mal einen Taste gedrückt. Das Log ist anbei.

[redmatic.2020-10-11T18_45_17.296Z.log](https://github.com/rdmtc/RedMatic/files/5361738/redmatic.2020-10-11T18_45_17.296Z.log)

**Comment by TheBassfly** [comment]
Nur mal als Ansatz: Könnte es vielleicht mit Update auf IO14.2 liegen (Public Beta). Oder wäre das er Redmatic egal?

**Comment by TheBassfly** [comment]
Gibt es schon neue Erkenntnisse?

**Comment by TheBassfly** [comment]
Guten Tag
Also ich hab die CCU auf das aktuelle Firmware Update 3.53.34 gebracht.

Das Problem besteht immer noch, daß der Event Node immer die Fehlermeldung:
TypeError: Cannot read property 'getCharacteristic' of undefined

ausgibt. Entsprechend funktionieren die Taster nicht mit HomeKit.


Hier mal die Konfiguration der beiden Nodes (Vielleicht hab ich da ja den Fehler drin):
[
    {
        "id": "193e6161.30272f",
        "type": "ccu-rpc-event",
        "z": "46efb210.4b9bac",
        "name": "WRC6 Tasten",
        "iface": "HmIP-RF",
        "ccuConfig": "38263145.35ea0e",
        "rooms": "",
        "roomsRx": "str",
        "functions": "",
        "functionsRx": "str",
        "device": "",
        "deviceRx": "str",
        "deviceName": "WRC6 Flur EG",
        "deviceNameRx": "str",
        "deviceType": "",
        "deviceTypeRx": "str",
        "channel": "",
        "channelRx": "str",
        "channelName": "",
        "channelNameRx": "str",
        "channelType": "",
        "channelTypeRx": "str",
        "channelIndex": "",
        "channelIndexRx": "str",
        "datapoint": "",
        "datapointRx": "str",
        "change": false,
        "working": false,
        "cache": false,
        "topic": "${CCU}/${Interface}/${devicelName}/${datapoint}",
        "x": 280,
        "y": 280,
        "wires": [
            [
                "c0c1587c.f63338",
                "30b03dd8.57bc52"
            ]
        ]
    },
    {
        "id": "c0c1587c.f63338",
        "type": "redmatic-homekit-programmableswitch",
        "z": "46efb210.4b9bac",
        "bridgeConfig": "50242591.e1579c",
        "name": "WRC6 EG",
        "count": "6",
        "x": 600,
        "y": 280,
        "wires": []
    },
    {
        "id": "38263145.35ea0e",
        "type": "ccu-connection",
        "z": "",
        "name": "localhost",
        "host": "localhost",
        "regaEnabled": true,
        "bcrfEnabled": true,
        "iprfEnabled": true,
        "virtEnabled": true,
        "bcwiEnabled": false,
        "cuxdEnabled": true,
        "regaPoll": true,
        "regaInterval": "30",
        "rpcPingTimeout": "60",
        "rpcInitAddress": "127.0.0.1",
        "rpcServerHost": "127.0.0.1",
        "rpcBinPort": "2047",
        "rpcXmlPort": "2048",
        "queueTimeout": "5000",
        "queuePause": "250",
        "contextStore": ""
    },
    {
        "id": "50242591.e1579c",
        "type": "redmatic-homekit-bridge",
        "z": "",
        "name": "RedMatic Homekit",
        "username": "CC:22:3D:EF:10:86",
        "pincode": "040-33-957",
        "port": "51826"
    }
]

**Comment by TheBassfly** [comment]
Hab mal das Update auf Redmatic 7 gemacht, aber auch dort bisher keine Änderung bzw. Lösung des Problems.

**Comment by TheBassfly** [comment]
Neues Update.

Ich habe das ganze nochmal nach der Anleitung aus dem Redmatic Wiki angelegt und siehe das. In Home zuckt der Taste schonmal. ABER die dem Taster zugewiesenen Aktionen werden nicht ausgeführt.
Hinzu kommt, daß der Debug Node folgendes ausgibt:
"invalid topic 0/RSSI_DEVICE"

Was kann das sein? Wir kommen wohl einem Ziel langsam näher .-)

**Comment by TheBassfly** [comment]
Ich kann ja verstehen daß das hier nur wein Hobby ist, und man durchaus anderes zu tun hat. Aber es wäre ja nett, wenigstens etwas Feedback zu bekommen, ob es zumindest an mir liegt oder wirklich ein Problem in Redmatic vorliegt.

**Comment by TheBassfly** [comment]
Hat man das Projekt aufgegeben?

**Comment by hobbyquaker** [comment]
> Hat man das Projekt aufgegeben?

Nein. Seltsame Frage - 6 Tage nachdem eine neue Version released wurde.

> Ich kann ja verstehen daß das hier nur wein Hobby ist, und man durchaus anderes zu tun hat. 

Gut.

> Aber es wäre ja nett, wenigstens etwas Feedback zu bekommen, ob es zumindest an mir liegt oder wirklich ein Problem in Redmatic vorliegt.

Ich schau's mir an sobald ich Zeit dafür finde, ich weiss es Stand jetzt nicht.

**Comment by TheBassfly** [comment]
Gute  Morgen

Alles klar. Das reicht mir doch erst einmal als Antwort, das es nicht daran liegt, das ich zu blöd bin da etwas einzustellen. Ich war ja nur irritiert das ich einen Monat hier einen Monooig gehalten hatte ohne irgend eine Reaktion. Ich warte weiter ab.
Lg

**Comment by Tscherno** [comment]
Naja, das hier ist auch weniger Diskussionforum, als direkte Kommunikation mit dem Entwickler. Vermutlich ist eine erste Anfrage im Homematic-Forum zuerst besser aufgehoben, da sich dort eher mehr Menschen mit der entsprechenden Hardware und eventuell mehr Zeit zu antworten finden. Versetz dich mal in die Lage von hobbyquaker. Kümmert sich entgeltfrei um dieses tolle Projekt und soll dabei auch noch zeitnah auf jede Anfrage antworten...

**Comment by TheBassfly** [comment]
Der ist lustig. Als ich damals das erste mal ein Problem hatte, wurde mir in dem Forum gesagt, ich solle mich doch bitte direkt an den Entwickler hierhin wenden. Mir geht es ja auch nicht um die Diskussion sondern um ein konkretes Problem daß der WRC6 in der Redmatic plötzlich nicht mehr funktioniert. Ich habe nie ausgeschlossen, daß der Fehler bei mir liegt, aber da ich nichts geändert hatte, außer einem Firmware Update wollte ich erst einmal die Einschätzung des Entwicklers. Und nach dem Logs gab es nichts mehr. Und ich halte auch nichts davon, sowas über mehrere Plattformen zu puschen und in der Vergangenheit hat es ja auch hier funktioniert. Und ich habe ja auch Geduld. Nur hat es mich gewundert der daß halt garnichts mehr kam.

**Comment by Tscherno** [comment]
Kannst Du mal bitte das ganze in einen neuen Beispielflow stecken und den hier posten. Ich würde es mir gerne mal ansehen.

**Comment by TheBassfly** [comment]
Muss ich heute Abend schauen. Ich hab die Alten Todes alle gelöscht und mir ein Provisorium gebastelt, was aktuell zumindest etwas funktioniert. Daher muss ich es neu aufbauen. Aber sollte machbar sein.

**Comment by TheBassfly** [comment]
Guten Abend

Nachdem ich ja die Redmatic nochmal komplett neu anlegen musste mit neuer MAC hab ich das ganze probiert und der WRC6 funktioniert jetzt auf einmal wieder wie er soll. Am Ende hat sich mit der Zeit über die Redmatic und IOS Updates sich da etwas verschluckt.
Daher kann es von meiner Seite geschlossen werden.
