### ISSUE TITLE
BidCos-RF setValue {"faultCode":-1,"faultString":"Failure"}

### ISSUE THREAD

**Issue by drMaxxi** [rdmtc/RedMatic#413]
Guten Abend,

Mit den folgenden Flows soll das Licht ein-und ausgeschaltet werden. Leider funktioniert dies nicht jedes mal und ich erhalte die im Screenshot angeführten Fehlermeldungen.

`[{"id":"58e4245a.2b2044","type":"ccu-set-value","z":"38ea2e0c.ce710a","name":"Stiegen UNTEN Beleuchtung","iface":"BidCos-RF","ccuConfig":"38263145.35ea0e","rooms":"","roomsRx":"str","functions":"","functionsRx":"str","device":"","deviceRx":"str","deviceName":"","deviceNameRx":"str","deviceType":"","deviceTypeRx":"str","channel":"","channelRx":"str","channelName":"Stiegen UNTEN Beleuchtung:1","channelNameRx":"str","channelType":"","channelTypeRx":"str","channelIndex":"","channelIndexRx":"str","datapoint":"STATE","datapointRx":"str","force":false,"x":780,"y":460,"wires":[]},{"id":"db22832.65862","type":"ccu-rpc-event","z":"38ea2e0c.ce710a","name":"1. Stock Taster:2 - PRESS_SHORT (oben)","iface":"BidCos-RF","ccuConfig":"38263145.35ea0e","rooms":"","roomsRx":"str","functions":"","functionsRx":"str","device":"","deviceRx":"str","deviceName":"","deviceNameRx":"str","deviceType":"","deviceTypeRx":"str","channel":"","channelRx":"str","channelName":"1. Stock Büro Taster:2","channelNameRx":"str","channelType":"","channelTypeRx":"str","channelIndex":"","channelIndexRx":"str","datapoint":"PRESS_SHORT","datapointRx":"str","change":false,"working":false,"cache":false,"topic":"${CCU}/${Interface}/${channelName}/${datapoint}","x":240,"y":460,"wires":[["cf1554.6a79eab","a39b824c.196618"]]},{"id":"cf1554.6a79eab","type":"change","z":"38ea2e0c.ce710a","name":"set to true","rules":[{"t":"set","p":"payload","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":530,"y":460,"wires":[["58e4245a.2b2044"]]},{"id":"ae1ec91.3ef94b8","type":"ccu-set-value","z":"38ea2e0c.ce710a","name":"Stiegen UNTEN Beleuchtung","iface":"BidCos-RF","ccuConfig":"38263145.35ea0e","rooms":"","roomsRx":"str","functions":"","functionsRx":"str","device":"","deviceRx":"str","deviceName":"","deviceNameRx":"str","deviceType":"","deviceTypeRx":"str","channel":"","channelRx":"str","channelName":"Stiegen UNTEN Beleuchtung:1","channelNameRx":"str","channelType":"","channelTypeRx":"str","channelIndex":"","channelIndexRx":"str","datapoint":"STATE","datapointRx":"str","force":false,"x":780,"y":520,"wires":[]},{"id":"4566a3ba.fe46ec","type":"ccu-rpc-event","z":"38ea2e0c.ce710a","name":"1. Stock Taster:1 - PRESS_SHORT (unten)","iface":"BidCos-RF","ccuConfig":"38263145.35ea0e","rooms":"","roomsRx":"str","functions":"","functionsRx":"str","device":"","deviceRx":"str","deviceName":"","deviceNameRx":"str","deviceType":"","deviceTypeRx":"str","channel":"","channelRx":"str","channelName":"1. Stock Büro Taster:1","channelNameRx":"str","channelType":"","channelTypeRx":"str","channelIndex":"","channelIndexRx":"str","datapoint":"PRESS_SHORT","datapointRx":"str","change":false,"working":false,"cache":false,"topic":"${CCU}/${Interface}/${channelName}/${datapoint}","x":240,"y":520,"wires":[["21a52072.cf06f8","eee7bfd7.680d88"]]},{"id":"21a52072.cf06f8","type":"change","z":"38ea2e0c.ce710a","name":"set to false","rules":[{"t":"set","p":"payload","pt":"msg","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":530,"y":520,"wires":[["ae1ec91.3ef94b8"]]},{"id":"38263145.35ea0e","type":"ccu-connection","z":"","name":"CCU Wohnung","host":"localhost","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"127.0.0.1","rpcServerHost":"127.0.0.1","rpcBinPort":"2047","rpcXmlPort":"2048","contextStore":""}]`

<img width="302" alt="Bildschirmfoto 2020-10-09 um 18 57 28" src="https://user-images.githubusercontent.com/44581521/95610875-4de6aa00-0a61-11eb-8951-874d308b67e8.png">

**Comment by hobbyquaker** [comment]
Das ist eine Fehlermeldung die vom Schnittstellenprozess (rfd) zurückkommt, da kann ich RedMatic-seitig nichts dran drehen. Mögliche Ursachen könnte z.B. schlicht eine gestörte Funkverbindung sein, hast Du von diesem Gerät auch "Gerätekommunikation gestört" Meldungen (UNREACH) im CCU WebUI?

**Comment by drMaxxi** [comment]
Danke, schlechter Empfang ist möglich. UNREACH ist es zwar nicht, aber der Empfang könnte das Problem erklären: das Gerät ist doch etwas von der CCU entfernt.
