### ISSUE TITLE
Redmatic-Paket ohne Node-Module

### ISSUE THREAD

**Issue by jensrossbach** [rdmtc/RedMatic#414]
Wäre es möglich, ein Redmatic-Paket (insbesondere für Updates) ohne die einzelnen Node-Module zu schnüren? Also nur mit den Core-Komponenten wie nodejs, node-red usw.

#### Hintergrund:
Da ich einige der vorinstallierten Nodes nicht benötige und um Speicher zu sparen und die Palette schlanker zu halten, habe ich diese deinstalliert. Wenn ich dann auf eine neue Redmatic-Version aktualisiere, sind die Nodes wieder installiert und ich muss diese erneut deinstallieren. Ein anderes Problem tritt ein, wenn in dem Update-Paket nicht die neuesten Versionen der Nodes sind. Habe ich diese Nodes bereits über die Palette aktualisiert, werden sie dann durch das Redmatic-Update wieder auf eine ältere Version zurückgesetzt.

**Comment by hobbyquaker** [comment]
dup: https://github.com/rdmtc/RedMatic/issues/351
see also https://homematic-forum.de/forum/viewtopic.php?f=77&t=58583&p=581054&
