### ISSUE TITLE
RedMatic v6.0.4 permanenter abort unter Raspberrymatic 3.53.30.20200919

### ISSUE THREAD

**Issue by armin34320** [rdmtc/RedMatic#415]
Redmatic 6.0.4 auf Tinkerboard-S unter Raspberrymatic 3.53.30.20200919 installiert.

Permanenter abort. Siehe Logs. Danach wieder auf V5.5.3 zurück.

Oct 12 15:53:13 schl_ccu3 daemon.info redmatic: RedMatic v6.0.4 (c) Sebastian Raff https://github.com/rdmtc/RedMatic
Oct 12 15:53:13 schl_ccu3 daemon.info redmatic: Waiting 45 seconds before activating monit services
Oct 12 15:53:13 schl_ccu3 daemon.info redmatic: Starting Node-RED
Oct 12 15:53:20 schl_ccu3 daemon.err node-red[17251]: [ccu-connection:CCU3] Local address 192.168.0.161 not available. Using 192.168.0.162 instead.
Oct 12 15:53:21 schl_ccu3 daemon.err node-red: (node:17251) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Oct 12 15:53:21 schl_ccu3 daemon.err node-red: (Use `node --trace-deprecation ...` to show where the warning was created)
Oct 12 15:53:21 schl_ccu3 daemon.err node-red[17251]: [alexa-remote-init:6ccf04ae.f8a2ac] account must be initialised before refreshing
Oct 12 15:53:23 schl_ccu3 user.info monit[5027]: 'redmatic-nodered' process is running with pid 17251
Oct 12 15:53:23 schl_ccu3 daemon.err node-red: 12 Oct 15:53:23 - [red] Uncaught Exception:
Oct 12 15:53:23 schl_ccu3 daemon.err node-red: 12 Oct 15:53:23 - TypeError: Cannot read property 'end' of null
Oct 12 15:53:23 schl_ccu3 daemon.err node-red:     at IncomingMessage.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-alexa-remote2/node_modules/alexa-cookie2/alexa-cookie.js:110:36)
Oct 12 15:53:23 schl_ccu3 daemon.err node-red:     at IncomingMessage.emit (events.js:326:22)
Oct 12 15:53:23 schl_ccu3 daemon.err node-red:     at endReadableNT (_stream_readable.js:1252:12)
Oct 12 15:53:23 schl_ccu3 daemon.err node-red:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Oct 12 15:53:23 schl_ccu3 daemon.err node-red: Node-RED exited with non-zero exit status 1
Oct 12 15:53:23 schl_ccu3 daemon.warn redmatic: Restarting Node-RED (1/3)
Oct 12 15:53:30 schl_ccu3 daemon.err node-red[17434]: [ccu-connection:CCU3] Local address 192.168.0.161 not available. Using 192.168.0.162 instead.
Oct 12 15:53:31 schl_ccu3 daemon.err node-red: (node:17434) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Oct 12 15:53:31 schl_ccu3 daemon.err node-red: (Use `node --trace-deprecation ...` to show where the warning was created)
Oct 12 15:53:31 schl_ccu3 daemon.err node-red[17434]: [alexa-remote-init:6ccf04ae.f8a2ac] account must be initialised before refreshing
Oct 12 15:53:33 schl_ccu3 daemon.err node-red: 12 Oct 15:53:33 - [red] Uncaught Exception:
Oct 12 15:53:33 schl_ccu3 daemon.err node-red: 12 Oct 15:53:33 - TypeError: Cannot read property 'end' of null
Oct 12 15:53:33 schl_ccu3 daemon.err node-red:     at IncomingMessage.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-alexa-remote2/node_modules/alexa-cookie2/alexa-cookie.js:110:36)
Oct 12 15:53:33 schl_ccu3 daemon.err node-red:     at IncomingMessage.emit (events.js:326:22)
Oct 12 15:53:33 schl_ccu3 daemon.err node-red:     at endReadableNT (_stream_readable.js:1252:12)
Oct 12 15:53:33 schl_ccu3 daemon.err node-red:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Oct 12 15:53:33 schl_ccu3 daemon.err node-red: Node-RED exited with non-zero exit status 1
Oct 12 15:53:33 schl_ccu3 daemon.warn redmatic: Restarting Node-RED (2/3)
Oct 12 15:53:40 schl_ccu3 daemon.err node-red[17598]: [ccu-connection:CCU3] Local address 192.168.0.161 not available. Using 192.168.0.162 instead.
Oct 12 15:53:41 schl_ccu3 daemon.err node-red: (node:17598) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Oct 12 15:53:41 schl_ccu3 daemon.err node-red: (Use `node --trace-deprecation ...` to show where the warning was created)
Oct 12 15:53:41 schl_ccu3 daemon.err node-red[17598]: [alexa-remote-init:6ccf04ae.f8a2ac] account must be initialised before refreshing
Oct 12 15:53:42 schl_ccu3 user.info monit[5027]: 'redmatic-diskusage' unmonitor on user request
Oct 12 15:53:42 schl_ccu3 user.info monit[5027]: 'redmatic-nodered' unmonitor on user request
Oct 12 15:53:42 schl_ccu3 user.info monit[5027]: 'redmatic-nodered' unmonitor action done
Oct 12 15:53:42 schl_ccu3 user.info monit[5027]: 'redmatic-diskusage' unmonitor action done
Oct 12 15:53:42 schl_ccu3 daemon.info redmatic: Stopping Node-RED
Oct 12 15:53:43 schl_ccu3 daemon.err node-red: 12 Oct 15:53:43 - [red] Uncaught Exception:
Oct 12 15:53:43 schl_ccu3 daemon.err node-red: 12 Oct 15:53:43 - TypeError: Cannot read property 'end' of null
Oct 12 15:53:43 schl_ccu3 daemon.err node-red:     at IncomingMessage.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-alexa-remote2/node_modules/alexa-cookie2/alexa-cookie.js:110:36)
Oct 12 15:53:43 schl_ccu3 daemon.err node-red:     at IncomingMessage.emit (events.js:326:22)
Oct 12 15:53:43 schl_ccu3 daemon.err node-red:     at endReadableNT (_stream_readable.js:1252:12)
Oct 12 15:53:43 schl_ccu3 daemon.err node-red:     at processTicksAndRejections (internal/process/task_queues.js:80:21)
Oct 12 15:53:44 schl_ccu3 daemon.info redmatic: Node-RED stopped

**Comment by Sineos** [comment]
Lt. Log liegt das an `node-red-contrib-alexa-remote2`
Einfach mal deinstallieren und dann schauen ob es läuft. Danach neu installieren

**Comment by hklages** [comment]
.... Da ist noch eine Meldung` [alexa-remote-init:6ccf04ae.f8a2ac] account must be initialised before refreshing` 
Vielleicht mal per Browser bei Amazon Account einloggen und sehen, ob dort was initiert werden muss.

**Comment by armin34320** [comment]
Da node-red nicht läuft kann ich nichts deinstallieren/installieren oder neu konfigurieren.

Brauche hier also eine andere Lösung.

**Comment by Sineos** [comment]
Siehe https://github.com/rdmtc/RedMatic/issues/424

**Comment by armin34320** [comment]
Ok. Danke. 

Am 27. Oktober 2020 12:34:11 MEZ schrieb Sineos <notifications@github.com>:
>Siehe https://github.com/rdmtc/RedMatic/issues/424
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rdmtc/RedMatic/issues/415#issuecomment-717180799

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by hobbyquaker** [comment]
Hier sollte auch der Safe-Mode helfen können um die Nodes zu deinstallieren (siehe https://github.com/rdmtc/RedMatic/wiki/Safe-Mode)

**Comment by armin34320** [comment]
Habe gerade die Redmatic Version 7.7.1 unter Raspberrymatic 3.53.30.20201024 auf meinem Tinkerboard-S installiert.

Läuft alles ohne Probleme.

Vielen Dank.
