### ISSUE TITLE
Install smartmeter geht nicht

### ISSUE THREAD

**Issue by konne** [rdmtc/RedMatic#416]
Hi,

ich habe smartmeter und serial port über die Packetverwaltung in der aktualsten Version 6.0.4 

![image](https://user-images.githubusercontent.com/1100969/95963945-9529bd80-0e08-11eb-8561-d16f61997e8b.png)

Installiert. Auch nach einem Neustart von Redmatic erscheint kein neuer Flow. Über die Palette werden sie aber angezeigt aber mit einem Ausrufezeichen:

![image](https://user-images.githubusercontent.com/1100969/95964240-e46fee00-0e08-11eb-8298-ce58a15b4f3c.png)

Im Log gibt es folgenden Fehler dazu:
`
Oct 14 10:20:40 ccu3-webui daemon.warn node-red[6710]: [node-red-contrib-smartmeter/smartmeter] Error: /usr/local/addons/redmatic/lib/node_modules/node-red-contrib-smartmeter/node_modules/smartmeter-obis/node_modules/@serialport/bindings/build/Release/bindings.node: wrong ELF class: ELFCLASS64`

**Comment by konne** [comment]
Durch Version 7.1.3 behoben, geht nun

**Comment by dos-ise** [comment]
Hi,

Ich kann das auch nicht installieren über npm.
Sollte diese nicht in redmatic inkludiert sein?

Danke für schonmal für die Hilfe.

Gruß Dennis

**Comment by Sineos** [comment]
https://github.com/rdmtc/RedMatic/wiki/Node-Installation#installation-via-redmatic-package-manager
