### ISSUE TITLE
node red not conected ccu3 over 1000 channels

### ISSUE THREAD

**Issue by mikewolf** [rdmtc/RedMatic#422]
Hallo, habe 2 CCUs (3) eine mit 1300 kanälen und eine mit 50, bei ersteren kann ich bicos,rega,Virt,Cuxd,wired abonieren
kommt aber immer wieder not connected oder partly conected , auf der 2 ccu mit weniger kanälen funktionierts, 
bei der ersten CCU kann ich nur cuxd  abbonieren das conected,sobald ich weiteren egal welchen abboniere partly connected
Verewende node red in letzter version auf linux debian 10, auf beiden HPCL
wäre für jegliche tips oder Lösung dankbar

**Comment by hobbyquaker** [comment]
Da müsste ich mal ein Blick in ein Debug-Log werfen um dazu was sagen zu können (siehe https://github.com/rdmtc/RedMatic/wiki/Loglevel)
