### ISSUE TITLE
Wiki Update zu Deinstallieren von Nodes

### ISSUE THREAD

**Issue by hklages** [rdmtc/RedMatic#424]
Ich habe im Wiki unter: 

# Zusätzliche Node-RED Nodes installieren

folgende Text unter Hinweise eingefügt. Bitte prüfen. 

<update 2020-10-24 - der ursprünglich Text wurde durch folgenden ersetzt>
Falls der Safe mode nicht die erwarteten Ergebnisse liefert und die Node eine Standard Node ist, die über die Palette installiert wurde, kann man versuchen diese Node per Hand zu entfernen. Dazu zuerst einen CCU Backup machen! und sich dann bewusst sein, dass es sich hier um einen kritischen Eingriff in das CCU System handelt.
- ssh einzuloggen unter root und dann source nutzen, um die richtige npm Umgebung zu erhalten (es gibt mindestens 2: eine auf der CCU, die veraltet ist und die von Redmatic, die auf dem aktuellen Stand ist (heute ist 2020-10-24)
`source /usr/local/addons/redmatic/home/.profile`
`cd /usr/local/addons/redmatic/var`
`npm uninstall --no-package-lock --global-style --save-prefix="~" --production`

**Comment by Sineos** [comment]
Zwei Anmerkungen:
1. Die Information WIE man die Node entfernt wäre nützlich
2. Eine deutliche Warnung: Wer mit rm hier rumspielt und das Falsche löscht, der spielt mit dem "Leben" seines Systems

**Comment by hklages** [comment]
... guter Hinweis. Ist korrigiert und zusätzlich auf Backup verwiesen.

**Comment by hklages** [comment]
@Sineos: mit source Befehl geht es anscheinend auch ohne "rw" und das scheint auch der richtige Weg zu sein. Der andere scheint bzgl. uninstall auch zu funktionieren, was aber wohl eher Zufall ist und beim update/install würde er zu Fehlern führen.

**Comment by hklages** [comment]
schließe ich, da gelöst.
