### ISSUE TITLE
Eigener NodeRed-Node wird nicht in Palette angezeigt

### ISSUE THREAD

**Issue by christianrr** [rdmtc/RedMatic#426]
Ich arbeite an einer Visualisierung für Homematic und würde diese vom Prinzip her ähnlich zu hobbyquaker's WebApp jedoch mit Vue.js aufbauen. Ich hätte dazu einen eigenen Node-Red-Node erzeugt, gepackt (npm pack) und dann wie im Redmatic-Wiki beschrieben installiert (npm install aus lokalem Pfad). Das Package scheint auch korrekt in den node_modules in redmatic/var auf, aber in der Config-Oberfläche von Redmatic ist es nicht gelistet (wird auch nicht als installiertes Paket angezeigt).

Habe ich da was übersehen? Wie kann ich meinen Node vorab ordentlich testen - habt ihr da einen Tipp für mich? Danke!

RedMatic Version 6.0.4
Homematic CCU3 3.53.26

**Comment by Sineos** [comment]
Am besten setzt du dir eine lokale Node-Red Installation auf und entwickelst / testest deine Node dort.

**Comment by christianrr** [comment]
Danke @Sineos für den Hinweis. Das ist auf jeden Fall eine gute Idee und hab ich jetzt auch gemacht.

Nur ist es beim Testsystem wieder das gleiche - Node taucht nicht auf. Ich habe jetzt @hobbyquaker's WebApp genommen, gebuildet und so wie [hier ](https://nodered.org/docs/creating-nodes/packaging) beschrieben, lokal hinzugefügt. Auch die WebApp, die ja so mit Redmatic ausgeliefert wird, taucht nicht auf. Was mache ich falsch?

Danke!
