### ISSUE TITLE
Get Value Node kennt meldet keine "Property" ausser "Value" zurück

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/RedMatic#431]
Hallo Zusammen,

ich wollte heute in der "Get Value Node" einmal andere Daten als "Value" auslesen. Ich kann die Felder anwählen, aber es wird immer nur "Value" zurück gegeben. Mache ich was falsch?

Redmatic Version: 7.0.0
Aktuelle Firmwareversion: 3.53.30.20201024

![grafik](https://user-images.githubusercontent.com/44590735/98033648-1e378180-1e16-11eb-8e89-7a9984787fbb.png)

![grafik](https://user-images.githubusercontent.com/44590735/98033506-e9c3c580-1e15-11eb-8fc8-a7165beafc40.png)

![grafik](https://user-images.githubusercontent.com/44590735/98033815-52ab3d80-1e16-11eb-9e24-c8937913dc7b.png)

Lieben Gruß Thomas

**Comment by Sineos** [comment]
Duplikat: https://github.com/rdmtc/RedMatic/issues/345
