### ISSUE TITLE
Kein RedMatic Button in WebUi

### ISSUE THREAD

**Issue by meistermolli** [rdmtc/RedMatic#434]
Bei RedMatic 7.1.1 kein RedMatic Button unter Systemsteuerung der Raspberrymatic 3.53.30.20201024

ist das korrekt so oder fehlt da was ?

Gruß meistermolli

**Comment by hklages** [comment]
Wie sieht deine Datei `/usr/local/etc/config/hm_addons.cfg` aus

**Comment by meistermolli** [comment]
Hallo,

kann ich ggf. heute Nachmittag mal nach schauen.
Oder eher einfach die neue Version drüber installieren?

Gruß

**Comment by hklages** [comment]
Neue Version installieren macht Sinn, geht schnell.
