### ISSUE TITLE
Nach Upgrade von 6.04 auf 7.11 startet RedMatic nicht mehr, nach downgrade auf 6.04 gleicher Fehler 

### ISSUE THREAD

**Issue by samhomatic** [rdmtc/RedMatic#435]
CCU3 mit Version 3.53.30 und addons (siehe Beilage)
![image](https://user-images.githubusercontent.com/74407245/99063881-77857a80-25a5-11eb-823e-201e3df812ee.png)

Downgrade von 7.11 auf 6.04 gleicher Fehler.
Das beiliegende LOG ist von der Version 6.04. 
Mit dieser Version hat RedMatic fehlerfrei funktioniert.
[log_V6.04.txt](https://github.com/rdmtc/RedMatic/files/5536280/log_V6.04.txt)

Start im Safe-Mode  gleicher Fehler.
Bitte um Unterstützung wo der Fehler liegen kann.

**Comment by hobbyquaker** [comment]
Da scheint aus irgendeinem Grund der Context Store kaputt zu sein. Lösch den einfach mal komplett, via SSH oder SCP (Filezilla, WinSCP, o.ä.), Pfad siehst Du in der RedMatic UI

**Comment by hobbyquaker** [comment]
Und noch eine Anmerkung: Mit nur 512MB RAM würde ich dringend davon Abraten 3 Speicherhungrige Addons gleichzeitig zu betreiben (HAP-Homematic, RedMatic, Neo Server). Das wird früher oder später zu Out-of-Memory Kills führen. Eigentlich empfehle ich schon für RedMatic alleine Hardware mit mindestens 1GB RAM.

**Comment by samhomatic** [comment]
Habe den Content Store gelöscht (auf einem USB-Stick   /media/usb1) - und es funktioniert jetzt.

Danke für die rasche und punktgenaue Analyse - das ist eine sehr gute Support-Qualität - sieht man leider immer seltener.

Zu RAM: Habe jetzt mit allen geladenen Addons noch 298Mb von den 1 Gb frei.
Sollte das nicht genug sein?

Trotz allem werde ich (wahrscheinlich)  auf Rasp-Matic migrieren da ich mit Node-Red noch mehr umsetzen möchte, damit RAM kein Thema mehr ist.

Ich werde den Upgrade von RedMatic auf die Version 7.1.1 noch durchführen und  die Info hinterlassen ob dieser fehlerfrei verlief bzw. der RAM - Bedarf sich verändert hat.

**Comment by samhomatic** [comment]
Hallo

Update auf Version 7.1.1 von RedMatic durchgeführt - ohne Probleme.

zu meiner Überraschung sind jetzt 454MB RAM frei, kann das sein?

NEOServer war vorher  bzw. ist derzeit nicht aktiv (Status Offline).

**Comment by hobbyquaker** [comment]
Der RAM bedarf von Node-RED hängt stark davon ab wie Deine Flows gestaltet sind, was für zusätzliche Nodes installiert sind etc, minimal würde ich sagen braucht es so 100MB, aber nach oben gibt's keine Grenze ;-)
