### ISSUE TITLE
Support eingestellt?

### ISSUE THREAD

**Issue by TheBassfly** [rdmtc/RedMatic#436]
Moin

Also, da ich seit einem Monat in meinem Threat hier einen Monolog halte https://github.com/rdmtc/RedMatic/issues/410 , muss ich ja mal die Frage stellen, liegt es an mir, oder hat man das Thema aufgegeben?

lg

**Comment by Sineos** [comment]
Eingestellt auf keinen Fall. @hobbyquaker, das Master-Mind hinter all dem, ist nicht mehr so aktiv wie früher. Woran es liegt, kann ich Dir nicht sagen, vermutlich wie bei so vielen das private Real-Life.
Nichtsdestotrotz kommen regelmäßig Updates und kleinere Verbesserungen, z.B. v7.1.1 vor 8 Tagen.

Was Dein spezielles Problem angeht, kann Dir vermutlich keiner der sonst hier Aktiven/Mitlesenden helfen. Wenn es dann eben der speziellen Aufmerksamkeit des Entwicklers bedarf, bleibt Dir nichts als zu warten und hoffen. Welcome to open-source 😉
