### ISSUE TITLE
Redmatic komplett "Keine Antwort" in HomeKit

### ISSUE THREAD

**Issue by TheBassfly** [rdmtc/RedMatic#439]
Guten Abend

Unabhängig von meinem Problem mit dem WRC6 ist seit heute meine komplette Homematic Installation in Homekit mit "Keine Antwort" versehen.
Einzige Änderung ist aktuell, daß ich das Apple TV und mein Iphine auf IOS 14.3 Public Beta 2 gesetzt habe.

Anbei das Log.
[redmatic.2020-11-19T15_53_03.500Z.log](https://github.com/rdmtc/RedMatic/files/5567950/redmatic.2020-11-19T15_53_03.500Z.log)

**Comment by Tscherno** [comment]
Schonmal die Zentrale aus der Home App gelöscht und neu hinzugefügt?

**Comment by TheBassfly** [comment]
Gerade eben gemacht und von danach ist auch das Log. Keine Änderung.

**Comment by Tscherno** [comment]
Versuch mal die Bridge mit neuer Mac-Adresse anzulegen, damit es Homekit als neues Gerät erkennt.

**Comment by TheBassfly** [comment]
Spannend. Danke, das hat es gelöst.

Bleibt nur noch das andere Problem. Da mach ich den Flow nachher mal  fertig.
