### ISSUE TITLE
Frage: HmIP-BSM - Taster-Event [proposed Label] Question

### ISSUE THREAD

**Issue by djiwondee** [rdmtc/RedMatic#445]
Hallo,

ist es möglich, mit einer der RedMatic CCU-Nodes (RPC-Event hätte ich vermutet) wirklich jeden Tasten-Druck zu erhalten? Das ist mir bisher nicht gelungen. Ich würde gerne eine Double-Press Message generieren, um in Node-Red noch weiter Funktionen daraus zu triggern.

Danke im Voraus für eine Antwort.

**Comment by Sineos** [comment]
Vielleicht hilft https://github.com/rdmtc/RedMatic/wiki/Faq#tastendruck-erzeugt-keine-events

**Comment by djiwondee** [comment]
@Sineos Danke für den schnellen Hinweis! Mal wieder ein Beispiel für "erst suchen, dann fragen" und "wer lesen kann ist klar im Vorteil".

Habe bisher weder was mit CCU-Programmen noch mit dem Homematic Manager  gemacht. Da werde ich wohl mal einen Blick drauf werfen.
