### ISSUE TITLE
Multiple CCU's

### ISSUE THREAD

**Issue by tom-holzwurm** [rdmtc/RedMatic#453]
Trotz Suche im Web, Beitrag im HM-Forum noch keine Rückmeldung bekommen:
Daher Zitat: "
trotz intensiver Suche habe ich kein Beispiel gefunden, wie ich eine 2. CCU ins Node-Red eingebunden bekomme:
Grundsätzlich ist es ja beschrieben, allerdings es funktioniert nicht:
Node-Red läuft in einem Docker Container mit den Standardports 2048 "BINRPC listening port" & 2049 "XMLRPC listening port"
die erste CCU läßt sich problemlos anbinden, bei der 2. kann ich 2048 nutzen, aber "2049 --> Port already is use"
Die Konfig-Node gibt "2050" vor, aber damit bekomme ich "ping timeout BidCos-RF 75" und die Node-Red Nodes zeigen auch "disconnected" an.
Ansonsten sind in den logs keine Fehler angezeigt.
Ich habe kein funktionierendes Beispiel gefunden, nur ziemlich rudimentäre Beschreibungen.
Es muss aber funktionieren, es gibt ja auch erfolgreiche Implementierungen ?!?"
Ich gehe davon aus, dass mir nur ein gutes Beispiel fehlt,
Danke im Voraus
Gruß Thomas

**Comment by Sineos** [comment]
So, es kann sein, dass mein Verständnis völlig panne ist:

- Die `ccu-connection` node von RedMatic öffnet per default zwei Server
  -  BINRPC mit dem LISTEN Port 2047
  - XMLRPC mit dem LISTEN Port 2048
- Die CCU erstellt eine Verbindung von einem zufälligen Port im Bereich 32768 bis 60999 auf die IP:PORT Kombination der `ccu-connection` node von RedMatic
- Auf der CCU laufen ebenfalls zwei (oder ggf auch mehr) Server:
  - BidCos-RF mit dem LISTEN Port 2001
  - HmIP-RF mit dem LISTEN Port 2010
- Hier stellt die `ccu-connection` node die jeweiligen Verbindung von je einem zufälligen Port auf die beiden CCU Ports her
- Über den Init teilt die `ccu-connection` node der CCU mit, auf welche zwei Port sie "hört" (LISTEN), sprich 2047 und 2048
- LISTEN Ports dürfen nicht mehrfach belegt sein

Solltest du also zwei CCUs ansprechen wollen, brauchst zwei unterschiedliche `ccu-connection` Profile:

**Profil 1:**
- IP Adresse der CCU1
- Init IP Adresse der CCU1 (Keine Ahnung warum ich die zweimal angeben muss. Kann mir kein Setting vorstellen, wo die unterschiedlich zur oberen ist)
- Listen Address: 0.0.0.0 
- BINRPC Port 2047 
- XMLRPC Port 2048

**Profil 2:**
- IP Adresse der CCU2
- Init IP Adresse der CCU2 
- Listen Address: 0.0.0.0 
- BINRPC Port 2061 (oder irgendwas anderes, was auf deinem System noch nicht belegt ist)
- XMLRPC Port 2062 (oder irgendwas anderes, was auf deinem System noch nicht belegt ist)


Soweit zur Theorie, getestet habe ich es nicht, weil ich auch keine 2 CCUs habe.

**Comment by Sineos** [comment]
Kleine Ergänzung zu deinem Setting:
Da du das in einem Docker am Laufen hast, musst du natürlich noch auf dieser Ebene tätig werden. Dem Cotainer muss "beigebracht" werden, welche Ports offen sind und welche Ports vom Betriebssystem auf den Docker umgeleitet werden sollen.
Siehe auch https://docs.docker.com/config/containers/container-networking/

Diese Übung überlasse ich aber vollständig Dir, weil das nicht mein Spezialgebiet ist 😉

**Comment by tom-holzwurm** [comment]
Liebe Kollege,

dein Wissen war Gold wert ! 😊

Das mit den zwei Profilen war mir klar, aber der Mechanismus, das sich die CCU Services einfach quasi frei Ports „suchen“, das steht nirgends so richtig.

Im Endeffekt war es total simpel ( wie immer wenn man es weiss ):

Man legt einfach eine Node an und konfiguriert in der Node das 2. CCU-IF. In der Node werden schon zwei freie Ports angegeben, die werden für Docker konfiguriert ( zusätzlich zu den vorhandenen )

und dann läuft es.

Man sollte das dokumentieren --> GitHub ?

Und natürlich meinen ausdrücklichen Dank!

Gruß Thomas

 

Von: Sineos <notifications@github.com> 
Gesendet: Freitag, 18. Dezember 2020 09:39
An: rdmtc/RedMatic <RedMatic@noreply.github.com>
Cc: tom-holzwurm <tom.holzwurm@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [rdmtc/RedMatic] Multiple CCU's (#453)

 

Kleine Ergänzung zu deinem Setting:
Da du das in einem Docker am Laufen hast, musst du natürlich noch auf dieser Ebene tätig werden. Dem Cotainer muss "beigebracht" werden, welche Ports offen sind und welche Ports vom Betriebssystem auf den Docker umgeleitet werden sollen.
Siehe auch https://docs.docker.com/config/containers/container-networking/

Diese Übung überlasse ich aber vollständig Dir, weil das nicht mein Spezialgebiet ist 😉

**Comment by Sineos** [comment]
@hobbyquaker Hast du mir die Originaldateien (die Verbindungsschemas) aus https://github.com/rdmtc/node-red-contrib-ccu/blob/master/README.md#configuration-examples, dann würde ich das ergänzen

**Comment by hobbyquaker** [comment]
Hab mir die leider nur als .png exportiert... Erzeugt hab ich die mit https://draw.io

**Comment by Sineos** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/4459312/102699410-b792e980-4244-11eb-9ab9-521af0429cd6.png)

Ist das verständlich?

**Comment by tom-holzwurm** [comment]
Das sieht sehr gut aus:

Wichtig ist folgendes: init address ist die IP-Adresse des Hosts, resp des Docker Hosts

Und mir wurden beim Einrichten der zweiten Konfig-Node zwei Ports vorgeschlagen, genau die habe ich im Node-red-Container freigeschaltet --> damit lief es sofort.

Gruß Thomas

 

Von: Sineos <notifications@github.com> 
Gesendet: Samstag, 19. Dezember 2020 21:55
An: rdmtc/RedMatic <RedMatic@noreply.github.com>
Cc: tom-holzwurm <tom.holzwurm@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [rdmtc/RedMatic] Multiple CCU's (#453)

 

 <https://user-images.githubusercontent.com/4459312/102699410-b792e980-4244-11eb-9ab9-521af0429cd6.png> 

Ist das verständlich?
