### ISSUE TITLE
Download Code

### ISSUE THREAD

**Issue by dibadodo** [rdmtc/RedMatic#456]
Hallo,

Ich versuche seit zwei -drei Tagen den Code zu laden. Leider ist das nur mit einem Durchsatz von ca. 50-60 KB/s möglich und geht zum Teil bis auf einstellige B/s zurück. Es ist mir also noch nicht gelungen, ein kompletten Download zu bewerkstelligen.
Den Mastercode könnte ich z.B. mit wesentlich höheren Durchsatz laden. Auch andere Downloads von Github gehen deutlich besser. Könnte da mal jemand nachsehen?
Danke

**Comment by Sineos** [comment]
Nope, da hat keiner Einfluss drauf. Das hängt nur an Github. Geht bei mir übrigens mit >20 MB/s

**Comment by dibadodo** [comment]
Mittlerweile hatte ich nun auch Erfolg. Aber trotzdem, der Download ist hier wirklich sehr langsam, während ich bei anderen GitHub Projekten recht fix laden kann. Daher dachte ich, das man da schon irgendwelchen Einfluss hat.
<img width="246" alt="image" src="https://user-images.githubusercontent.com/76758561/103417510-41b74800-4b8b-11eb-8256-d7a6ef352a3f.png">
