### ISSUE TITLE
Integration für M-Bus bereitstellen --> node-red-contrib-m-bus

### ISSUE THREAD

**Issue by Kirsche86** [rdmtc/RedMatic#460]
Hallo zusammen,

zunächst einen ein großes Danke für dieses Projekt hier. Die RedMatic Komponente deckt bei mir mittlerweile ein Großteil der SmartHome-Integration in unserem Eigenheim ab mit einer vielzahl unterschiedlicher Interfaces. Bei der Einbindung unseren Wärmemengezähler von der Heizung via M-Bus Protokoll bin ich allerdings an die Grenzen von RedMatic gekommen.
Der M-Bus Master ([Link](https://m.de.aliexpress.com/item/32755430755.html?trace=wwwdetail2mobilesitedetail&productId=32755430755&productSubject=MBUS-to-USB-master-module-MBUS-device-debugging-dedicated-no-power-supply) hier) soll dabei an den USB-Anschluss der CCU3 angedockt werden.

Es gibt einen Node (node-red-contrib-m-bus) der die erforderlichen Funktionalitäten bereitstellt. Jedoch kann diese unter RedMatic ohne weitere nicht installiert werden. Es erscheinen dann so Fehlermeldungen mit Phython etc im Log während der Installation (den exakten Log kann ich bei Bedarf noch posten). Ich vermute das hier das entsprechende M-Bus Interface als Paket für die RedMatic Integration beregestellt werden müsste, damit alles soweit funktioniert. 

Würde mich sehr freuen wenn dies in einer den kommenden Versionen nachgepflegt werden könnte.
Für weitere Infos und hilfen stehe ich gern zur Verfügung 😄 

Vielen Dank schonmal und beste Grüße,

Kirsche86 🍒

**Comment by sw256** [comment]
Hallo,

ich wäre ebenfalls an dem M-Bus Paket interessiert.

Besten Dank !

**Comment by hobbyquaker** [comment]
Ist in 7.2.0 enthalten

**Comment by Kirsche86** [comment]
Gestet und eingebunden. Funktioniert alles wie erwartet. Vielen vielen Dank!

**Comment by sw256** [comment]
Habe es ebenfalls getestet und es funktioniert wie im Original Node Red. :)
Vielen Dank !
