### ISSUE TITLE
Mehrere Homekit Profile gleichzeitig

### ISSUE THREAD

**Issue by drMaxxi** [rdmtc/RedMatic#462]
Ist es möglich unterschiedliche Homekit Profile zu erstellene (z.B. durch mehrere Homekit Nodes für unterschiedliche Nutzer)? Ich habe gesehen dass der Homematic Node die Auswahl von Geräten erlaubt, aber ich schaffe ihn nicht als neue Wohnung bei Apple
zu konfigurieren. Das Ziel wäre es den Kindern nur bestimmte Geräte bedienen zu lassen.

**Comment by hobbyquaker** [comment]
Ja, das ist machbar. Du kannst beliebig viele Homekit Bridges anlegen, musst dabei aber darauf achten dass jede Bridge einen anderen Port nutzt und diese Ports auch von der CCU Firewall erlaubt werden. Zähl einfach für jede weitere Bridge 1 dazu, also die erste auf dem Default Port `51826`, die zweite auf `51827` usw.
