### ISSUE TITLE
Projekte lassen sich nicht "Pushen", Git Fehlermeldung: ELFCLASS64

### ISSUE THREAD

**Issue by hklages** [rdmtc/RedMatic#468]
Hallo. Meine CCU3 habe ich vorgestern gegen einen Raspberry Pi 4 getauscht. Es funktioniert alles bis auf Node-RED push des Projektes (Node-RED flows). Unten sind die eingesetzten Versionen angehängt. 

Wenn ich über putty gehe und
`source /usr/local/addons/redmatic/home/.profile`
und dann im Projektverzeichnis 
`git status`
eingebe, kommt auch der Hinweis, dass mein "Repository 2 commits" behind ist. 
`git push`

liefet dann die Fehlermeldung: 
`/usr/local/addons/redmatic/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl.so.4: wrong ELF class: ELFCLASS64`

Hat jemand eine Idee, wie das Problem beheben kann?

2021-01-10T2149 Update: sieht sehr nach  #442 

Versionen.
Git version ist 2.16.1
[Versionen - alle aktuell](https://homematic-forum.de/forum/viewtopic.php?f=65&t=64423)

**Comment by hobbyquaker** [comment]
Possible Dup: #461

**Comment by konne** [comment]
Hi, ja ist ein Dup. Habe genau das gleiche Problem.

@hobbyquaker Kann ich hier irgendwie einen Workaround schaffen, kannst du hier kurzfristig helfen. Ich würde
gerne auch mit aktuellen raspberrymatic mein project sauber mit git syncen können.

**Comment by konne** [comment]
Hi, hier ein workaround path. Einfach das Zip file nehmen und den Inhalt in 
/usr/local/addons/redmatic/lib/

[gitFIX.zip](https://github.com/rdmtc/RedMatic/files/6029448/gitFIX.zip)

entpacken. Danach sollte GIT wieder gehen.

@hobbyquaker du müsstest hier einfach sauber eine 64bit Version von git einbinden und wahlweise das richtige verwenden.
Netterweise stellt jensmaus jetzt raspberrymatic schrittweise auf 64bit um und bindet aber nur die Lib in 32bit Versionen ein die
auch für Raspberrymatic notwendig sind.

**Comment by konne** [comment]
@hobbyquaker issue is still in the new 7.2.1 release

**Comment by hobbyquaker** [comment]
@konne was für Hardware und welche RaspberryMatic Version nutzt Du? Mit der aktuellen aarch64 (rpi3/4) RaspberryMatic kann ich das nicht mehr reproduzieren. Und ist der Fehler immer noch betreffs `libcurl.so.4`?
