### ISSUE TITLE
Ändern einer direkten Verknüpfung mit rpc node (putParamset)

### ISSUE THREAD

**Issue by oli906** [rdmtc/RedMatic#470]
Redmatic: 7.1.3
node-red-contrib-ccu: 3.4.0

Hallo,
ich nutze einen HmIP-DRSI4 für die Beleuchtung im Treppenhaus. Dazu sind an den Eingängen mehrere Taster und Bewegungsmelder und an den Ausgängen die Beleuchtung angeschlossen. Über mehrere direkte Verknüpfungen habe ich definiert, welcher Eingang welchen Ausgang für eine bestimmte Zeit einschaltet.

Jetzt möchte ich über das Dashboard die Einschaltzeit in den Verknüpfungen verändern können. Dazu verwende ich einen rpc-node und die Methode "putParamset" und bekomme dann pro übergebenem Parameter eine Warn- und eine Fehlermeldung:

Warnung:
"unknown paramsetDescription  HmIP-RF/HmIP-DRSI4/1.4.2/1/SWITCH_VIRTUAL_RECEIVER/00259BE99503A5:2 SHORT_OFFDELAY_TIME_BASE"

Fehler:
"    < HmIP-RF putParamset Error: XML-RPC fault: Invalid parameter or value"

Das Problem ist also, das für die Verknüpfungen keine Beschreibung der Parameter vorliegt und die Funktion "paramCast" in der Datei "ccu-connection.js" diese somit nicht validieren kann. Für diesen Fall sieht die Funktion vor, dass alle Werte als Zeichenfolge übergeben werden. Das führt dann zu dem eigentlichen Fehler und dazu, dass die Konfiguration nicht an den Aktor gesendet werden kann.

Als Workaround hatte ich versucht, die Werte als "explicitDouble" zu senden. Dann kommt keine Fehlermeldung mehr (Die Warnmeldung bleibt) und die Konfiguration kann auch an den Aktor übertragen werden. Ich habe aber festgestellt, dass ich anschließend die Verknüpfung nicht mehr über die Weboberfläche der CCU bearbeiten kann. Statt die Parameter anzuzeigen wird nur eine leere Seite geladen.

Ich habe das Problem erstmal so "gelöst", dass ich sowohl die Warnmeldung als auch die Umwandlung der Werte in Zeichenfolgen in der Funktion "paramCast" auskommentiert habe (ccu-connection.js; Zeilen 2904-2908). Jetzt kann ich die Verknüpfungen über das Dashboard verändern und alles funktioniert, wie es soll.

Ist es möglich entweder die Beschreibung der Parameter verfügbar zu machen, damit die Werte validiert werden können, oder die Umwandlung in Zeichenfolgen dauerhaft auszuschalten?

**Comment by Konrni** [comment]
CCU Firmware: 3.55.5.20201226

Fehler kann bei HmIP-FSM reproduziert werden.

Mit Folgendem Flow lassen sich die unten stehenden Fehlermeldungen erzeugen. (Der Konfig Node und die SN müssen angepasst werden.)
`[{"id":"dcd73521.21de28","type":"debug","z":"2a2855e3.6a948a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":810,"y":260,"wires":[]},{"id":"e892d807.2e9278","type":"ccu-rpc","z":"2a2855e3.6a948a","name":"","ccuConfig":"6b1b4da7.0c0ba4","iface":"HmIP-RF","method":"putParamset","params":"[\"XXXXXXXXXXXXXX:2\",\"XXXXXXXXXXXXXX:6\",{\"SHORT_ON_TIME_FACTOR\":2,\"SHORT_OFF_TIME_FACTOR\":2}]","topic":"${CCU}/${Interface}/${Method}","x":670,"y":260,"wires":[["dcd73521.21de28"]]},{"id":"c1092bea.d8b078","type":"inject","z":"2a2855e3.6a948a","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":480,"y":260,"wires":[["e892d807.2e9278"]]},{"id":"6b1b4da7.0c0ba4","type":"ccu-connection","name":"homematic-raspi","host":"homematic-raspi","regaEnabled":true,"bcrfEnabled":true,"iprfEnabled":true,"virtEnabled":true,"bcwiEnabled":false,"cuxdEnabled":false,"regaPoll":true,"regaInterval":"30","rpcPingTimeout":"60","rpcInitAddress":"","rpcServerHost":"0.0.0.0","rpcBinPort":"2076","rpcXmlPort":"2077","tls":true,"inSecure":true,"authentication":true,"username":"XXXX","password":"XXXXXXXXXXXXXX","queueTimeout":"5000","queuePause":"250","contextStore":""}]`

> unknown paramsetDescription  HmIP-RF/HmIP-FSM/1.6.2/2/SWITCH_VIRTUAL_RECEIVER/XXXXXXXXXXXXXX:6 SHORT_ON_TIME_FACTOR

>unknown paramsetDescription  HmIP-RF/HmIP-FSM/1.6.2/2/SWITCH_VIRTUAL_RECEIVER/XXXXXXXXXXXXXX:6 SHORT_OFF_TIME_FACTOR

>    < HmIP-RF putParamset Error: XML-RPC fault: Invalid parameter or value

>Error: XML-RPC fault: Invalid parameter or value

Es kann außerdem passieren das die Direktverknüpfung damit nicht mehr über die WebUI zu bearbeiten ist. Hier kann der Homatic Manager helfen oder der Workaround von [oli906](https://github.com/rdmtc/RedMatic/issues/470#issue-784856103).

**Comment by Konrni** [comment]
Bei mir war die lösung
`if(Boolean(psName.match(/[0-9a-f]+:\d+/))) { psName = 'LINK'};` in Zeile 2848 einzufügen.
Die einzelnen Beschreibungen sind alle in der Datei paramsets.json enthalten, jedoch mit (...)/LINK anstelle der Seriennummer + Kanal, welche jedoch durch psName übergeben wird.

Eine Lösung in paramsetName (Zeile 1739) wäre evtl. besser, von mir jedoch nicht einzuschätzen. 

Infos:
`void putParamset(String address, String paramset_key, Paramset set)`

> Der Parameter address ist die Addresses eines logischen Gerätes. Der Parameter
> paramset_key ist „MASTER“, „VALUES“ oder die _Adresse_ eines
> Kommunikationspartners für das entsprechende Link-Parameter-Set (siehe getLinkPeers).
> 

https://www.eq-3.de/downloads/download/homematic/hm_web_ui_doku/HM_XmlRpc_API.pdf (Seite 12)
https://www.eq-3.de/downloads/download/homematic/hm_web_ui_doku/HMIP_XmlRpc_API_Addendum.pdf (Seite 7)
