### ISSUE TITLE
HM IP 6 Fach Wandtaster gibt keinen Event raus

### ISSUE THREAD

**Issue by Stieger81** [rdmtc/RedMatic#476]
Hallo zusammen 

Leider bringe ich es nicht hin das mein Wandtaster  HmIP-WRC6 etwas ausgibt. Dummy Programm habe ich angelegt, welches mir zur Kontrolle eine Lampe schaltete. Dies läuft. 
Auch das ReportValueUsage im Mangel habe ich erledigt. Jedoch alles ohne Erfolg. Was könnte hier noch die Ursache sein= 

Ganz einfache Value Node und der Debugger dran.

**Comment by hobbyquaker** [comment]
Zeig mal ein Screenshot der Konfiguration des Value Node.
