### ISSUE TITLE
Homekit-Paket Installation fehlgeschlagen

### ISSUE THREAD

**Issue by Materie79** [rdmtc/RedMatic#477]
Hallo,
Habe erstmal öffters über das Problem gelesen aber leider gab es dazu keine richtige Antwort wie man das Problem behandeln soll.
Ich habe in meine CCU3 Redmatic installiert gekriegt bis dahin alles gut es läuft auch und lässt sich starten.
Ich kriege aber leider kein Packet installiert egal welchen ich installieren will.
Ich will eigentlich nur Homekit installieren.
Was übersehe ich da?
Danke schonmal im voraus für Hilfe......

**Comment by Materie79** [comment]
----------------------------------------------------------
2021-02-01T07:44:33.659Z installieren : redmatic-homekit 3.2.22021-02-01T07:44:28.437Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production redmatic-homekit@3.2
22021-02-01T07:44:44.471Z [err] npm
2021-02-01T07:44:44.473Z [err]  
2021-02-01T07:44:44.475Z [err] ERR!
2021-02-01T07:44:44.475Z [err]  
2021-02-01T07:44:44.476Z [err] code
2021-02-01T07:44:44.477Z [err]  EAI_AGAIN
2021-02-01T07:44:44.479Z [err] npm
2021-02-01T07:44:44.480Z [err]  
2021-02-01T07:44:44.486Z [err] ERR! errno EAI_AGAIN
2021-02-01T07:44:44.514Z [err] npm 
2021-02-01T07:44:44.515Z [err] ERR! request to https://registry.npmjs.org/redmatic-homekit failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org
2021-02-01T07:44:44.534Z [err] 
2021-02-01T07:44:44.535Z [err] npm ERR! A complete log of this run can be found in:
2021-02-01T07:44:44.535Z [err] npm ERR!
2021-02-01T07:44:44.536Z [err]      /usr/local/addons/redmatic/var/npm-cache/_logs/2021-02-01T07_44_44_518Z-debug.log
2021-02-01T07:44:44.556Z rc=1

**Comment by Materie79** [comment]
Guten Morgen,
Das ist der Log was er mir bei jedem Paket anzeigt.....

**Comment by ptweety** [comment]
Das scheinen Verbindungsprobleme zu sein, die wenig mit nodered selber zu tun haben.

**Comment by Materie79** [comment]
Habe das auch schon bedacht, Netzwerk und Internet funktioniert ja, habe ja noch davor das Update für die CCU3 geladen und installiert. Die Redmatic hab ich ja auch laden und installieren müssen....wie gesagt bis dahin hat alles funktioniert.
Nur leider mit allen Paketen hab ich Probleme und kann nicht nachvollziehen warum....🧐
Danke für die schnelle Antwort.

**Comment by ptweety** [comment]
Es ist ein Unterschied, ob dein PC oder die CCU den jeweiligen Server erreicht. Kannst du dich per ssh einloggen und einen Ping auf registry.npmjs.com absetzen?

**Comment by Materie79** [comment]
Ok, dabei müsstest du mir helfen,
Bin jetzt nicht der Netzwerk Held😅
Also ich habe ein Mac, wie mach ich das am besten?
Muss ich Putty dafür runterladen?
Oder geht das noch anders...
Beschreibe mir das bitte detaillierter...sorry aber ich lerne immer noch dazu.😊

**Comment by ptweety** [comment]
Also, als erstes in der WebUI unter Systemsteuerung - Sicherheit mal SSH aktivieren und ein Passwort vergeben (merken!).
Dann auf dem Mac das Terminal öffnen und per `ssh root@<ip-der-ccu>` und dem obigen Passwort verbinden.
Und zu guter letzt noch `ping registry.npmjs.org` ausführen. (_ctrl+c_ bricht die Ausgabe ab. `exit` sendet die ssh Sitzung.)

**Comment by Materie79** [comment]
![Uploading 106451829...]

**Comment by ptweety** [comment]
Ein neuer Installationsversuch scheitert trotzdem? Wenn ja, dann bitte mal das entsprechende Debug-LOG zeigen ...

**Comment by Materie79** [comment]
Ich habe natürlich es direkt wieder probiert es zu installieren klappt aber leider immer noch nicht.
Einmal normal über redmatic Pakete und einmal NOD-Red gestartet und da es nochmal probiert beides geht nicht per Log zeigt er mir das gleiche an wie oben.
Wie komme ich zu Debug Log?

**Comment by ptweety** [comment]
Das ist von @hobbyquaker schon sehr schön beschrieben worden: https://github.com/rdmtc/RedMatic/wiki/Loglevel

**Comment by Materie79** [comment]
Ok, habe sie fertig...kann ich sie per Mail an Sie schicken?

**Comment by Sineos** [comment]
Probier mal: https://github.com/rdmtc/RedMatic/wiki/Node-Installation#installation-via-npm-auf-der-kommandozeile

**Comment by Materie79** [comment]
Also per via NOD-Red und Paket-Manager funktioniert das ganze nicht.....

**Comment by ptweety** [comment]
Moment, wie versuchst du eigentlich die Installation und hast du dir das schon angesehen: https://github.com/rdmtc/RedMatic/wiki/Homekit

**Comment by Materie79** [comment]
Genau so habe ich auch die Installation gemacht und nach einiger Zeit steigt er aus (Es steht ein Fehler an)
Zweiter Versuch war halt direkt über die Node-RED und beides geht nicht.....🤨
So viele Stunden am rumprobieren ich verzweifle langsam😅
Wäre ja zu einfach wen es einfach nur funktionieren würde😜

**Comment by Materie79** [comment]
So ptweety ich habe das nochmal probiert mit dem Terminal, das hat vorher funktioniert aber wie es aussah war ich nicht mit der CCU3 per ssh verbunden.
Jetzt nochmal alles durchgegangen und wo ich mit der CCU 3 verbunden bin und dann die Adresse Ping registry.bonks.org vergebe.
Sagt mir das Terminal bad adress

**Comment by Materie79** [comment]
Also registry.npmjs.org

**Comment by Materie79** [comment]
Soooo geschafft......
Nach mehreren Tagen und Stunden....
Mein Problem war das auf der CCU3 ich eine falsche DNS IP hatte anstatt 0 hatte ich eine 1 gehabt.
Du hast recht gehabt es war ein Verbindungsproblem trotzdem vielen Dank nochmal für alles.
