### ISSUE TITLE
Paletten Verwaltung weg

### ISSUE THREAD

**Issue by Donni1966** [rdmtc/RedMatic#482]
Hi,

I have a strange effect - see picture. I've been missing the Manage Pallets entry for a few days.

I had to replace the SD card and have to reinstall it quickly. Unfortunately, everything important was not included in the backup. I had previously saved and saved the entire RedMatic Moderner and then simply saved it back again later. Then I changed all of them right to 755 - which I think should be correct. Nevertheless, I no longer get the entry Palette Installation.

Does anyone have an idea?
cu
![Bildschirmfoto 2021-02-07 um 16 49 32](https://user-images.githubusercontent.com/61660957/107151950-b0937800-6965-11eb-9f8b-64e474ad1084.png)

**Comment by hklages** [comment]
usually that means, that npm is not installed or found. 
I suggest to re-install redmatic.

**Comment by Donni1966** [comment]
oh thanx ... really that's help ...
