### ISSUE TITLE
upgrade package node-red-contrib-zigbee

### ISSUE THREAD

**Issue by hnymphius** [rdmtc/RedMatic#485]
Auf PI4 ist raspberrymatic und redmatic installiert.
Unter redmatic habe ich das  "node-red-contrib-zigbee" als package in der Version 0.20.1 installiert. Möchte gerne auf 0.20.2. upgrarden, da dort Aldi Leuchtmittel integriert sind. 
Es gibt aber neben dem Paket nur die Option "Installieren" (dimmed) und "remove", jedoch keine "update". Über Palette ist eine Installation oder Update auch nicht möglich.
Wie muß ich vorgehen, um die neuere Version zu installieren?
Vielen Dank
Hansjoerg

**Comment by Sineos** [comment]
Das Paket kann nicht einzeln installiert werden. Musst warten bis @hobbyquaker eine neue Redmatic baut.

**Comment by hobbyquaker** [comment]
Neues Release ist in Vorbereitung, hoffe es noch dieses Wochenende fertig zu bekommen.

**Comment by hnymphius** [comment]
Danke, das ist super 
Trotzdem erholsames Wochenende 


⁣BlueMail for Android herunterladen ​

**Comment by Lederhaut** [comment]
Oh toll, gibt es dann v0.20.3 von node-red-contrib-zigbee von heute? Dann gibt es auch die aktuelle Version vom zigbee-herdsman-converters, 0.20.2 referenziert ja auch eine ältere...

Und noch vielen, vielen Dank :-)
