### ISSUE TITLE
error while loading shared libraries: libonig.so.4 nach Update auf 7.2.0

### ISSUE THREAD

**Issue by dehsgr** [rdmtc/RedMatic#490]
Nach dem Update auf v7.2.0 kommt bei mir beim Starten von RedMatic o.g. Fehler. Die komplette Fehlerzeile lautet:
`Mar 13 13:47:29 homematic daemon.info redmatic-pkg: /usr/local/addons/redmatic/bin/jq: error while loading shared libraries: libonig.so.4: cannot open shared object file: No such file or directory`

- Verwendete Version: RaspberryMatic (>= 3.53.34.20201121) Varianten rpi3, rpi4, tinkerboard und oci_arm64 (aarch64)
- RedMatic läuft dennoch bei mir (bislang) unauffällig.

**Comment by IT-VBFK** [comment]
Hallo,

sowas ähnliches hab ich auch (bei mir halt beim Installieren von nodes):

bei mir lautet die Fehlermeldung jedoch:

```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/codm/node-lox-ws-api.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:

```

**Comment by hobbyquaker** [comment]
Sollte mit 7.2.1 gefixt sein.

**Comment by dehsgr** [comment]
Lade ich gerade herunter. :-)

**Comment by dehsgr** [comment]
@hobbyquaker ich kann bestätigen, dass mein gemeldeter Fehler korrigiert ist. Ob der Fehler mit libpcre.so.3 ebenfalls weg ist, müsste allerdings @IT-VBFK bestätigen.

**Comment by dehsgr** [comment]
...und natürlich vielen Dank für die wie immer schnelle Korrektur und das immer toller werdende Projekt! Ich wünsche Dir ein schönes Wochenende!

**Comment by IT-VBFK** [comment]
hmm.. bei funktioniert nach dem update leider gar nichts mehr:

node red startet nicht mal

```
Error loading settings file: /usr/local/addons/redmatic/lib/settings.js
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red: /usr/local/addons/redmatic/var/node_modules/request/index.js:84
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red:   
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red: SyntaxError: Unexpected end of input
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red:     at wrapSafe (internal/modules/cjs/loader.js:979:16)
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red:     at Module._compile (internal/modules/cjs/loader.js:1027:27)
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red:     at Module.load (internal/modules/cjs/loader.js:928:32)
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red:     at Module.require (internal/modules/cjs/loader.js:952:19)
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red:     at require (internal/modules/cjs/helpers.js:88:18)
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red:     at Object.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-ccu/node_modules/homematic-rega/index.js:5:17)
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
Mar 13 20:03:04 RaspberryMatic-VBFK daemon.err node-red:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

**Comment by dehsgr** [comment]
Das sieht mir aber dann so aus, als ob es ein separates Issue sein könnte. 🤔

**Comment by IT-VBFK** [comment]
Ich glaube ich kann mir denken woran das gelegen hat:
nach dem Update auf 7.2.0 war meine package.json leer. Habe dann einfach die aus diesem Repository 1:1 reinkopiert. Ich glaube das hat entweder npm oder node-red nicht verkraftet. RedMatic neu installiert --> funktioniert wieder :D

Der Fehler dieses Tickets ist weg, dh nodes installieren funktioniert wieder.
