### ISSUE TITLE
Redmatic 7.2.1 lässt sich auf Tinkerboard S nicht zum laufen bringen

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/RedMatic#492]
Hardware: Asus Tinker S
Raspberry Matic: 3.55.10.20210213
Installierte Version 7.1.3

Nach dem Update auf 
![image](https://user-images.githubusercontent.com/44590735/111043800-da4c2d00-8444-11eb-8cfa-214f4ad532a0.png)

lässt sich Redmatic nicht mehr starten und crashed mit Fehlermeldung das eine Komponente nicht mehr funktioniert. Neustart ist dann durch "stromlos" machen erforderlich. Die Version für CCU3 lässt sich installieren aber es lässt sich keine Node mehr updaten.

![image](https://user-images.githubusercontent.com/44590735/111043840-2008f580-8445-11eb-8609-712c940587c8.png)

Gruß Thomas

**Comment by ThomasLoeffel** [comment]
Zusatz:
Auch die Version 7.2.0 lässt sich auf meinem Tinker S nicht starten.

**Comment by ThomasLoeffel** [comment]
Zusatz:
Nun lassen sich mit Version 7.1.3 die Nodes nicht mehr updaten.

![image](https://user-images.githubusercontent.com/44590735/111044166-1aacaa80-8447-11eb-82c1-939684a27a90.png)

Gruß Thomas

**Comment by hobbyquaker** [comment]
Ich befürchte ich hab die Release Beschreibung hinsichtlich Tinkerboard verbockt, das ist garkein 64Bit System... 🤦‍♂️

@ThomasLoeffel ich würde empfehlen mal die Datei /usr/local/addons/redmatic/var/package.json zu löschen und dann noch mal die 7.2.1 armv7l "drüber" zu installieren.

**Comment by ThomasLoeffel** [comment]
Habe Backup mit 7.1.3 zurückgespielt, dann richtiges Update installiert und nun lassen sich auch die Nodes updaten.
Danke für die schnelle Reaktion :-).
Gruß Thomas

**Comment by dehsgr** [comment]
@hobbyquaker oh, krass! Dann lässt sich ein Wechsel vom PI3 auf TB (und zurück) also nicht mehr so einfach über Wiederherstellen eines CCU-Backups ohne Neuinstallation des Add-Ins bewerkstelligen?
