### ISSUE TITLE
RedMatic Signal.org Messenger

### ISSUE THREAD

**Issue by Andy2020-DE** [rdmtc/RedMatic#494]
Hallo zusammen

mir gelingt es nicht in der Version 7.2.1 eine Festnetznummer für die Signal Node zu aktivieren.

Wenn ich "request-voice" nutze und dort die Festnetznummer angebe wird im debugging auch "Signal client: registration code requested via voice call." angezeigt, es kommt aber kein Anruf an. Trage ich bei "request-voice" eine Handynummer ein, kommt eine SMS (sollte hier nicht auch eine Sprachansage kommen ?)

Wenn ich die Festnetznummer auf einem Handy eintrage, kommt ein Anruf und ich kann die Festnetznummer auf dem Handy aktivieren.

Ein Update von nodered-contrib-signal-client von 2.4.0 auf 2.4.1 ist leider auch nicht möglich.

**Comment by Sineos** [comment]
Lt. changelog von `nodered-contrib-signal-client` hat sich nur die Dokumentation von 2.4.0 auf 2.4.1 geändert.

Am besten stellst du deine Anfrage bei `nodered-contrib-signal-client`. RedMatic integriert diese Node nur, aber entwickelt sie weder noch sind hier die Experten für die Benutzung etc.

**Comment by Andy2020-DE** [comment]
Ok, danke für die schnelle Info.

Hier der Link zum dem nodered-contrib-signal-client Issues
[https://github.com/gausma/nodered-contrib-signal-client/issues/21](url)
