### ISSUE TITLE
Nach update von 7.1.3 auf 7.2.1 keine Knoten über "Palette verwalten" installierbar

### ISSUE THREAD

**Issue by samazw** [rdmtc/RedMatic#501]
Hallo

nach dem update von Redmatic von 7.1.3 auf 7.2.1 kann ich innerhalb von Node Red (über "Palette verwalten" keine neuen Nodes mehr installieren. Der Log spuckt im Grunde immer folgendes aus:

_-----------------------------------------------------------
2021-04-20T13:58:02.425Z installieren : node-red-contrib-homematic 2.0.9

2021-04-20T13:58:02.010Z npm install --no-package-lock --global-style --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production node-red-contrib-homematic@2.0.9
2021-04-20T13:58:04.221Z [err] npm
2021-04-20T13:58:04.223Z [err]  
2021-04-20T13:58:04.224Z [err] ERR! code EJSONPARSE
2021-04-20T13:58:04.224Z [err] npm 
2021-04-20T13:58:04.224Z [err] ERR! path /usr/local/addons/redmatic/var/package.json
2021-04-20T13:58:04.241Z [err] npm ERR!
2021-04-20T13:58:04.241Z [err]  JSON.parse Unexpected end of JSON input while parsing empty string
2021-04-20T13:58:04.241Z [err] npm ERR! 
2021-04-20T13:58:04.241Z [err] JSON.parse Failed to parse JSON data.
2021-04-20T13:58:04.241Z [err] npm ERR!
2021-04-20T13:58:04.241Z [err]  JSON.parse Note: package.json must be actual JSON, not just JavaScript.
2021-04-20T13:58:04.280Z [err] 
2021-04-20T13:58:04.281Z [err] npm ERR! A complete log of this run can be found in:
2021-04-20T13:58:04.281Z [err] npm ERR!     /usr/local/addons/redmatic/var/npm-cache/_logs/2021-04-20T13_58_04_244Z-debug.log
2021-04-20T13:58:04.298Z rc=1
--------------------------------------------------------------_

Unabhängig davon laufen die vorhanden Knoten und Verknüpfungen. Ebenso können über die Knoten installiert werden, die unter REDMATIC->Pakete angeboten werden. Vor dem Update auf 7.2.1 konnte ich jedoch auch direkt in node-red über die Palettenverwaltung Knoten installieren. Das schlägt jetzt fehl.

meine Raspberrymatic Firmware ist 3.53.30.20201024
Raspberry Pi 3 Model B Rev 1.2

Danke und Grüße
sam

**Comment by Sineos** [comment]
Poste mal bitte den Inhalt von `/usr/local/addons/redmatic/var/package.json`

**Comment by jgrete** [comment]
Ich möchte den Thread hier keinesfalls kapern, habe aber dasselbe Problem.
Mein package.json sieht so aus:
`{
  "name": "node-red-project",
  "description": "A Node-RED Project",
  "version": "0.0.1",
  "dependencies": {
    "@kuehnelbs/node-red-contrib-nextcloud": "~0.1.3",
    "bootstrap-vue": "~2.21.2",
    "node-red-contrib-1wire": "0.0.1",
    "node-red-contrib-advanced-ping": "~1.2.0",
    "node-red-contrib-astrodata": "0.0.4",
    "node-red-contrib-bigssh": "~1.2.4",
    "node-red-contrib-blindcontroller-v2": "~1.0.8",
    "node-red-contrib-boolean-logic": "0.0.3",
    "node-red-contrib-boolean-logic-ultimate": "~1.0.23",
    "node-red-contrib-ccu": "3.4.2",
    "node-red-contrib-combine": "1.8.1",
    "node-red-contrib-compass": "~1.0.1",
    "node-red-contrib-controltimer": "~0.1.0",
    "node-red-contrib-convert": "~1.0.5",
    "node-red-contrib-edge-detecter": "0.0.1",
    "node-red-contrib-email-out": "~0.1.1",
    "node-red-contrib-fritz": "~1.4.3",
    "node-red-contrib-fritzapi": "~0.2.14",
    "node-red-contrib-fritzbox-presence": "~2.0.1",
    "node-red-contrib-heater-controller": "~2.0.2",
    "node-red-contrib-homematic": "~2.0.9",
    "node-red-contrib-homematic-rpc": "~1.0.1",
    "node-red-contrib-ical-events": "~0.23.0",
    "node-red-contrib-influxdb": "~0.5.2",
    "node-red-contrib-log4nr": "~1.0.3",
    "node-red-contrib-logger": "0.0.4",
    "node-red-contrib-machine-learning-v2": "~1.0.9",
    "node-red-contrib-multipart-stream-decoder": "~0.0.4",
    "node-red-contrib-nextcloud-info": "~0.6.2",
    "node-red-contrib-nighttime": "~1.0.35",
    "node-red-contrib-node-email-state-notification": "0.0.1",
    "node-red-contrib-norelite": "~2.8.0",
    "node-red-contrib-nut-ups": "~1.1.0",
    "node-red-contrib-presence-faker": "~1.8.4",
    "node-red-contrib-presenchecker": "~0.1.0",
    "node-red-contrib-smartfritz": "~0.2.0",
    "node-red-contrib-state": "~1.5.0",
    "node-red-contrib-state-machine": "~1.2.0",
    "node-red-contrib-stoptimer2": "~0.1.1",
    "node-red-contrib-sun-position": "1.2.4",
    "node-red-contrib-tcp-ping": "0.0.3",
    "node-red-contrib-timeouttrigger": "0.0.2",
    "node-red-contrib-timerswitch": "~1.3.0",
    "node-red-contrib-tradfri": "~1.2.0",
    "node-red-contrib-ui-clock": "~1.0.0",
    "node-red-contrib-ui-led-fork": "~0.3.1",
    "node-red-contrib-uibuilder": "~3.0.1",
    "node-red-contrib-vacation-timer": "~2.2.8",
    "node-red-dashboard": "2.28.1",
    "node-red-node-base64": "~0.3.0",
    "node-red-node-email": "1.8.3",
    "node-red-node-openweathermap": "~0.3.2",
    "node-red-node-rbe": "0.4.0",
    "node-red-node-ui-iframe": "~0.2.1",
    "node-red-node-ui-webcam": "~0.3.0",
    "redmatic-led": "1.1.0",
    "redmatic-webapp": "0.3.1",
    "thingzi-logic-timers": "~1.1.3",
    "vue": "~2.6.12"
  }
}
`
Ein Tipp wäre sehr nett!
Jürgen

**Comment by samazw** [comment]
Guten Abend, 
sorry - etwas verspätet.

Warum auch immer war die package.json (hier: /usr/local/addons/redmatic/var/package.json) leer.
Hier der Weg, wie ich es gelöst habe:

1) Über putty per SSH Verbindung (root / passwort)
2) in das Verzeichnis /usr/local/addons/redmatic/var/ wechseln
3) npm init -y ausführen

Somit wird die package.json neu aufgebaut und es lassen sich auch wieder Pakete installieren. 

Grüße
sam

**Comment by samazw** [comment]
geschlossen - Lösung siehe oben

sam
