### ISSUE TITLE
Datenrestor nach Update

### ISSUE THREAD

**Issue by tobiasjaeger78** [rdmtc/RedMatic#524]
Ich habe das Thema ein paar mal gefunden, aber ich verstehe die beschriebenen Schritte nicht.
Ich habe heute meine CCU auf die neueste Firmware gehoben und davor natürlich alle Zusatzsoftware auch geupdated somit auch redmatic.
Jetzt sind alle meine Flows nicht mehr vorhanden.
Kann mir bitte jemand sagen ob es hier eine Anleitung gibt wie ich an meine Flows komme?
Lassen die sich aus einem backup von vor dem update extrahieren?
Danke Euch vorab.

**Comment by Tscherno** [comment]
Ich bin mir gerade nicht sicher wo, aber sie sind sicher im Backup. Lad dir die mal runter und entpacke sie. Die Datei müsst flows.json heißen.
