### ISSUE TITLE
Probleme beim Update node-red-contrib-virtual-smart-home (RedMatic Version 7.2.1)

### ISSUE THREAD

**Issue by BaltiP** [rdmtc/RedMatic#559]
Leider habe seit gut einer Woche Probleme beim Update des Packages: node-red-contrib-virtual-smart-home

Das Problem ist dem Entwickler des Packages bereits bekannt (https://github.com/csuermann/node-red-contrib-virtual-smart-home/issues/152). Das Problem ist scheinbar die veraltete Version des Packages node-red.

Kennt jemand Alternativen um meine Aktoren mittels Sprachbefehle mittels Alexa steuern zu können?

Ich war eigentlich bis jetzt sehr zufrieden mit der Funktion.

**Comment by csuermann** [comment]
@BaltiP, es scheint auch möglich zu sein, Node-RED von Hand zu aktualisieren: https://github.com/rdmtc/RedMatic/issues/550#issuecomment-1228423177

**Comment by lucasradon** [comment]
Konnte mithilfe besagter Anleitung Node-red von Redmatic updaten. 
Nach dem Neustart waren alle bisherigen Nodes von virtual-smart-home noch vorhanden.
Bedienung über Alexa funktioniert wieder.

**Comment by BaltiP** [comment]
@BaltiP bin nun auch der Anleitung gefolgt und konnte damit die Funktionalität wiederherstellen.

Vielen Dank für die Hilfe.
