### ISSUE TITLE
HmIP-BBL-2 wird nicht als Gerät erkannt.

### ISSUE THREAD

**Issue by thostef** [rdmtc/RedMatic#570]
Hallo,

ich versuche den Jalousieaktor HmIP-BBL-2 in RedMatic Homekit zu verknüpfen.
Leider erscheint dieses Gerät nicht in der Geräte-Liste.

Ich habe jetzt viel im Netz gesucht und bin immer auf "HmIP-BBL" gestoßen.
Daher meine Vermutung das es eine neue Version des Schalters gibt?

In der Geräteliste hier ist auch nur "HmBL-BBL" aufgelistet.

Danke

**Comment by TheBassfly** [comment]
Sowas ähnliches hatte ich auch schon mildem PS-2.
Da gab es im Homematic Forum folgende Lösung:

https://homematic-forum.de/forum/viewtopic.php?t=75131

Eventuell hilft das auch dir.

**Comment by thostef** [comment]
> Sowas ähnliches hatte ich auch schon mildem PS-2. Da gab es im Homematic Forum folgende Lösung:
> 
> https://homematic-forum.de/forum/viewtopic.php?t=75131
> 
> Eventuell hilft das auch dir.

Super! Das hat geklappt 

Danke
